/* GENERATED by tools/seeds.js: vetted simulation seeds (not secret). Do not edit. */
(function (root) {
  'use strict';
  var SEEDS = {"coin":[3,5,8,9,11,12,15,16,22,26,28,30,34,35,38,41,42,46,49,55,57,61,62,63,64,66,69,71,73,74,85,93,94,95,98,100,102,109,110,115,127,130,132,134,135,137,139,141,148,154,159,160,162,168,170,173,174,176,183,185,188,189,190,191],"house":[1,5,6,7,16,11,12,13,18,17,19,22,24,29,23,30,33,34,36,25,38,40,41,43,27,45,54,55,56,32,57,58,60,61,35,62,63,64,65,44,66,69,70,71,48,72,75,76,78,50,81,82,86,91,51,92,95,96,97,68,99,100,104,107]};
  if (typeof module === 'object' && module && module.exports) module.exports = SEEDS;
  root.U5_SEEDS = SEEDS;
})(typeof globalThis !== 'undefined' ? globalThis : (typeof self !== 'undefined' ? self : this));
