#!/usr/bin/env node
'use strict';
/*
 * Build the content.
 *
 *   authoring/            (gitignored: content + answer keys)   -> content/items.json   (public, no keys)
 *                                                               -> content/alignment.json (public: objectives -> items)
 *                                                               -> private/itembank.json, private/ItemBankSeed.gs, private/ANSWER_KEY.md  (gitignored)
 *   content/demo/authoring.js (public demo / test fixture)      -> content/demo/items.json, content/demo/bank.json
 *
 * If authoring/ is missing (fresh clone) the live build is skipped and the demo build still runs. Restore the real
 * authoring source with `node tools/vault.js unlock` (needs the passphrase).
 *
 *   node tools/build-content.js          build everything available
 *   node tools/build-content.js --check  lint only, write nothing
 */
const fs = require('fs');
const path = require('path');
const { build } = require('./lib/builder.js');
const answerkey = require('./lib/answerkey.js');

const root = path.join(__dirname, '..');
const checkOnly = process.argv.includes('--check');
const write = (rel, data) => {
  if (checkOnly) return;
  const p = path.join(root, rel);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, typeof data === 'string' ? data : JSON.stringify(data, null, 2) + '\n');
};

function report(name, r) {
  console.log('\n== ' + name + ' ==');
  console.log('items: ' + r.report.itemCount + '   points: ' + r.report.totalPoints + '   structureHash: ' + r.structureHash.slice(0, 12));
  console.log('cognitive points: ' + Object.keys(r.report.cog).map((k) => k + ' ' + r.report.cog[k]).join(' | '));
  console.log('chapter time (est vs target): ' + Object.keys(r.report.chapterTime).map((k) => k + ' ' + Math.round(r.report.chapterTime[k].est / 6) / 10 + '/' + r.report.chapterTime[k].target / 60 + ' min (' + (r.report.chapterTime[k].pct > 0 ? '+' : '') + r.report.chapterTime[k].pct + '%)').join(' | '));
  console.log('reading level (Flesch-Kincaid): mean ' + r.report.readingMean + ', max ' + r.report.readingMax);
  r.warnings.forEach((w) => console.log('  warn  ' + w));
  r.errors.forEach((e) => console.log('  ERROR ' + e));
}

let failed = false;

/* ---------- demo ---------- */
{
  const demo = build(require(path.join(root, 'content/demo/authoring.js')), { demo: true });
  report('demo', demo);
  if (demo.errors.length) failed = true;
  else {
    write('content/demo/items.json', demo.publicContent);
    write('content/demo/bank.json', demo.bank);
  }
}

/* ---------- live ---------- */
const authoringIndex = path.join(root, 'authoring/index.js');
if (!fs.existsSync(authoringIndex)) {
  console.log('\n(authoring/ not present: live content build skipped. Run `node tools/vault.js unlock` to restore it.)');
} else {
  const src = require(authoringIndex);
  const live = build(src, {});
  report('live', live);
  if (live.errors.length) failed = true;
  else {
    write('content/items.json', live.publicContent);
    // public, keyless alignment data for the teacher Reference panel and docs
    const items = [];
    src.chapters.forEach((ch) => ch.units.forEach((u) => u.items.forEach((it) => {
      const basis = it.obj.some((o) => src.objectives[o].basis === 'district') ? 'district' : (it.obj.some((o) => src.objectives[o].basis === 'standard') ? 'standard' : 'blueprint');
      items.push({ id: it.id, chapter: ch.id, topic: it.topic, type: it.type + (it.mode ? '/' + it.mode : ''), points: it.points, cog: it.cog, obj: it.obj, secs: it.secs, basis });
    })));
    write('content/alignment.json', { objectives: live.publicContent.objectives, items, chapters: src.chapters.map((c) => ({ id: c.id, n: c.n, title: c.title, targetMinutes: c.targetMinutes })) });
    write('private/itembank.json', live.bank);
    write('private/ItemBankSeed.gs',
      '// GENERATED by tools/build-content.js. PRIVATE: contains the answer keys.\n' +
      '// Paste into a second script file in the Apps Script editor, run seedItemBank(), then DELETE this file from the editor.\n' +
      'var ITEM_BANK_SEED = ' + JSON.stringify(live.bank) + ';\n');
    write('private/ANSWER_KEY.md', answerkey.render(src));
    if (!checkOnly) console.log('\nwrote content/items.json, content/alignment.json, private/itembank.json, private/ItemBankSeed.gs, private/ANSWER_KEY.md');
  }
}

if (failed) { console.error('\nBuild FAILED: fix the errors above.'); process.exit(1); }
console.log(checkOnly ? '\nLint passed.' : '\nBuild complete.');
