#!/usr/bin/env node
'use strict';
/*
 * Generate the three data-driven docs from the built content:
 *   docs/BLUEPRINT.md, docs/ALIGNMENT_MATRIX.md, docs/QA_REPORT.md
 *
 * Inputs: content/items.json + content/alignment.json (public, no keys) and tools/lib/qa-notes.js.
 * If authoring/ is present (it is gitignored) the builder's own report is used for the lint statistics; otherwise
 * those numbers are read from the public data only and the lint section says so.
 * Everything else in docs/ is written by hand.
 */
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const items = require(path.join(root, 'content/items.json'));
const align = require(path.join(root, 'content/alignment.json'));
const qa = require('./lib/qa-notes.js');
const { COG_GROUP, COG_TARGET } = require('./lib/builder.js');

let report = null;
if (fs.existsSync(path.join(root, 'authoring/index.js'))) {
  report = require('./lib/builder.js').build(require(path.join(root, 'authoring/index.js')), {}).report;
}

const TYPE_NAME = {
  'single': 'Single-answer MC', 'multi': 'Select all that apply', 'order': 'Ordering', 'numeric': 'Numeric entry',
  'assign/label': 'Label a diagram', 'assign/match': 'Match', 'assign/classify': 'Classify / tag'
};
const COG_NAME = { remember: 'Remember', understand: 'Understand', apply: 'Apply', analyze: 'Analyze', evaluate: 'Evaluate' };
const BASIS_NAME = {
  district: 'District overview (a Criteria-for-Success bullet)',
  standard: 'Course standard from the top of the overview. Standards 3, 4 and 5 are also listed for the Family Life and Sexuality lessons. Standard 8 (advocacy) is a course standard but is NOT listed for lessons 1 to 3.',
  blueprint: 'Build brief only (NOT found in the district overview; confirm against your slides)'
};
const esc = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const table = (head, rows) => '| ' + head.join(' | ') + ' |\n|' + head.map(() => '---').join('|') + '|\n' + rows.map((r) => '| ' + r.map(esc).join(' | ') + ' |').join('\n') + '\n';
const mins = (s) => (Math.round(s / 6) / 10).toFixed(1);
const stamp = 'Generated by `node tools/gen-docs.js` from the built content (structure hash `' + items.structureHash.slice(0, 12) + '`, content version ' + items.meta.version + '). Do not edit by hand; edit the source and regenerate.';

const byId = {}; align.items.forEach((i) => { byId[i.id] = i; });
const chapterOf = {}; items.chapters.forEach((c) => c.units.forEach((u) => u.items.forEach((i) => { chapterOf[i.id] = c; })));

/* ------------------------------------------------------------------ BLUEPRINT */
function blueprint() {
  const out = [];
  out.push('# Blueprint\n\n' + stamp + '\n');
  out.push('**Life Decisions: The Health & Relationships Investigation** · Unit 8 Family Life & Sexuality · Grade 10 Health · ' + align.items.length + ' items · ' + items.points + ' points · 90-minute server-enforced limit.\n');
  out.push('Time estimates below are **my estimates from item type and length. They were not measured with students.** See TEACHER_REVIEW.md. The target times come from your build brief; all six chapters are within the +/-15% the build enforces.\n');

  const ch = items.chapters.map((c) => {
    let n = 0, p = 0, s = 0, r = 0;
    c.units.forEach((u) => { r += u.readSecs || 0; u.items.forEach((i) => { n++; p += i.points; s += i.secs; }); });
    return { c, n, p, est: s + r };
  });
  out.push('## Chapters\n');
  out.push(table(['#', 'Chapter', 'Items', 'Points', 'Target min', 'Estimated min', 'Difference'],
    ch.map((x) => [x.c.n, x.c.title, x.n, x.p, x.c.targetMinutes, mins(x.est), (x.est / (x.c.targetMinutes * 60) - 1 >= 0 ? '+' : '') + Math.round((x.est / (x.c.targetMinutes * 60) - 1) * 1000) / 10 + '%'])
      .concat([['', '**Total**', ch.reduce((a, x) => a + x.n, 0), ch.reduce((a, x) => a + x.p, 0), ch.reduce((a, x) => a + x.c.targetMinutes, 0), mins(ch.reduce((a, x) => a + x.est, 0)), '']])));
  out.push('Total estimated working time is about ' + mins(ch.reduce((a, x) => a + x.est, 0)) + ' minutes. The 90-minute limit leaves a large margin for reading, hints, retries and slower students. Per-student accommodations (extra time) are set in Teacher Mode.\n');

  const cog = {}; align.items.forEach((i) => { const g = COG_GROUP[i.cog]; cog[g] = (cog[g] || 0) + i.points; });
  out.push('## Cognitive level\n');
  out.push(table(['Group', 'Points', 'Share', 'Brief target'], Object.keys(COG_TARGET).map((g) => [g, cog[g] || 0, (cog[g] || 0) + '%', COG_TARGET[g] + '%'])));
  const fine = {}; align.items.forEach((i) => { fine[i.cog] = (fine[i.cog] || 0) + i.points; });
  out.push('Finer split: ' + Object.keys(COG_NAME).map((k) => COG_NAME[k] + ' ' + (fine[k] || 0)).join(', ') + ' points. The build warns if any group is more than 3 points from its target. Each item has one cognitive tag, chosen by what the student must do (recall a label = Remember; sort statements by evidence = Analyze; judge a response against criteria = Evaluate).\n');

  const ty = {}; align.items.forEach((i) => { ty[i.type] = ty[i.type] || { n: 0, p: 0 }; ty[i.type].n++; ty[i.type].p += i.points; });
  out.push('## Item types\n');
  out.push(table(['Type', 'Items', 'Points'], Object.keys(ty).map((k) => [TYPE_NAME[k] || k, ty[k].n, ty[k].p])));
  out.push('Every single-answer item has at least five options. There are no true/false items and no free-text answers. Click-to-place alternatives exist for every drag interaction.\n');

  out.push('## Items by chapter\n');
  items.chapters.forEach((c) => {
    out.push('### Chapter ' + c.n + ': ' + c.title + ' (' + c.targetMinutes + ' min target)\n');
    const rows = [];
    c.units.forEach((u) => {
      u.items.forEach((i) => {
        const a = byId[i.id];
        rows.push([i.id, TYPE_NAME[a.type] || a.type, a.topic, i.points, COG_NAME[i.cog], i.obj.join(', '), i.secs + ' s',
          (i.unlockAfter ? 'Opens after ' + i.unlockAfter : '') + (u.gate ? (i.unlockAfter ? '; ' : '') + 'Evidence must be read first' : '')]);
      });
    });
    out.push(table(['Item', 'Type', 'Topic', 'Pts', 'Level', 'Objectives', 'Est. time', 'Gating'], rows));
  });
  out.push('## Scoring\n\n- Every item may be tried three times. Correct on the 1st try earns 100% of the item\'s points, the 2nd try 85%, the 3rd try 75%, and 0 after three misses. Points are kept to two decimal places (for example 85% of a 3-point item is 2.55).\n- Hint 1 is released after the first miss and hint 2 after the second. Hints never name the answer. After the third miss the item locks and the explanation is shown.\n- Items with several parts (labels, sorting, ordering, select-all) are all-or-nothing per attempt: every part must be right for the attempt to count. There is no partial credit.\n- Grading happens only on the server. The page never receives an answer key.\n');
  return out.join('\n');
}

/* ------------------------------------------------------------------ ALIGNMENT */
function alignment() {
  const out = [];
  out.push('# Alignment matrix\n\n' + stamp + '\n');
  out.push('## How to read the "basis" column\n');
  out.push('The curriculum zip named in your build brief was **not available** in the build environment (see CURRICULUM_AUDIT.md), so this alignment is **provisional**. Each objective is tagged with where it came from:\n');
  out.push(table(['Basis', 'Meaning'], Object.keys(BASIS_NAME).map((k) => [k, BASIS_NAME[k]])));
  out.push('Nothing here has been checked against your Unit 8 slides, so please read the **blueprint**-basis rows and TEACHER_REVIEW.md before you rely on it.\n');

  out.push('## Objective to items\n');
  const rows = Object.keys(align.objectives).map((k) => {
    const its = align.items.filter((i) => i.obj.includes(k));
    const pts = its.reduce((a, i) => a + i.points, 0);
    const lv = {}; its.forEach((i) => { lv[COG_NAME[i.cog]] = (lv[COG_NAME[i.cog]] || 0) + 1; });
    return [k, align.objectives[k].basis, align.objectives[k].text, its.map((i) => i.id).join(', '), its.length, pts, Object.keys(lv).map((x) => x + ' ' + lv[x]).join(', ')];
  });
  out.push(table(['ID', 'Basis', 'Objective', 'Items', 'No.', 'Item points*', 'Cognitive levels'], rows));
  out.push('\\* An item aligned to several objectives counts its full points under each, so this column adds up to more than 100. The per-item table below counts each item once.\n');

  out.push('## Points by strongest basis (each item counted once)\n');
  const bp = {}; align.items.forEach((i) => { bp[i.basis] = bp[i.basis] || { n: 0, p: 0 }; bp[i.basis].n++; bp[i.basis].p += i.points; });
  out.push(table(['Basis', 'Items', 'Points', 'Share'], ['district', 'standard', 'blueprint'].map((k) => [k, (bp[k] || { n: 0 }).n, (bp[k] || { p: 0 }).p, (bp[k] || { p: 0 }).p + '%'])));
  out.push('"Strongest basis" means: an item counts as **district** if any of its objectives is a district bullet, else **standard** if any is a course standard, else **blueprint**. Blueprint items test skills requested in the build brief (puberty myths, text-thread analysis, STI classification, chart reading, source credibility, the integrated case) that I could not confirm were taught in this unit. If you did not teach one of these, you can switch it off per item in Teacher Mode (Settings). The switch applies to students who begin afterward: each student\'s score is points earned out of the points possible for the items that were on when they began, and the percent is calculated from that. It does not rescale anyone who has already started.\n');

  out.push('## Item to objectives\n');
  out.push(table(['Item', 'Chapter', 'Topic', 'Pts', 'Level', 'Objectives', 'Basis'],
    align.items.map((i) => [i.id, 'Ch ' + chapterOf[i.id].n, i.topic, i.points, COG_NAME[i.cog], i.obj.join(', '), i.basis])));

  out.push('## Coverage gaps and notes\n');
  const gaps = Object.keys(align.objectives).filter((k) => !align.items.some((i) => i.obj.includes(k)));
  out.push(gaps.length ? '- Objectives with no item: ' + gaps.join(', ') + '.\n' : '- Every listed objective has at least one item (the build fails otherwise).\n');
  const thin = Object.keys(align.objectives).filter((k) => align.items.filter((i) => i.obj.includes(k)).length === 1);
  out.push('- **Thin coverage (exactly one item):** ' + thin.join(', ') + '. One item cannot show mastery of an objective, so treat a miss there as a prompt for a conversation, not a conclusion. FL2.2 and FL2.3 share a single item (C2-03, a family-communication thread); there is deliberately no item about the student\'s own family structure.\n- The district overview names the **benefits of abstinence** as the framing for HIV prevention. Chapter 3 and 4 items follow that framing and also state, accurately, that condoms reduce but do not eliminate risk and that HIV can spread in non-sexual ways.\n- No item asks a student what they have done, what they would do, or about their own family. Decision items grade the *process* with fictional characters.\n');
  return out.join('\n');
}

/* ------------------------------------------------------------------ QA */
function qaReport() {
  const out = [];
  out.push('# QA report\n\n' + stamp + ' The per-item notes come from `tools/lib/qa-notes.js`, which I wrote by hand during the QA pass.\n');
  out.push('## What this report does and does not claim\n');
  out.push('- **Curriculum check: NOT POSSIBLE.** The Unit 8 curriculum zip was not available (CURRICULUM_AUDIT.md). I could not check any item against your slides, so no item below is marked "verified against the curriculum".\n- **Source check: NOT POSSIBLE.** Every approved health domain returned HTTP 403 from the build environment, so no web page was opened, and `content/sources.json` lists no accessed pages. The health claims are listed there as NEEDS VERIFICATION. No statistic, study or URL was invented.\n- **"Pass" means:** the item passes the automated build rules below and I judged it consistent with the accuracy points in your build brief (section 2). It does not mean a content expert signed off. That is your job, and TEACHER_REVIEW.md lists what to look at first.\n');

  out.push('## Automated checks (run on every build; the build fails if any fails)\n');
  out.push('- Exactly ' + items.points + ' points; every item has a positive whole-number point value.\n- Every item has a prompt, topic, cognitive tag, one or more objectives, a time estimate, **exactly two non-empty hints**, and an explanation.\n- Single-answer MC has **at least five options** and exactly one correct. Select-all items have at least two correct and two incorrect. Classification needs at least five cards, spread across at least two groups. Ordering needs at least four steps.\n- Every objective has at least one item. Every chapter is within +/-15% of its time target.\n- **Length-bias rule:** in each single-answer item the correct option must be 80-120% of the average distractor length, and it may not be the longest (or shortest) in more than 40% of single-answer items. In select-all items the correct statements must average 75-130% of the wrong ones.\n- No `<` or `>` in learner-facing text; hints may not be empty or very long. Reading level (Flesch-Kincaid) is reported per item and warned above 11.5.\n- Figures: every label target has a marker in the SVG.\n');

  out.push('## Statistics for this build\n');
  const st = [];
  st.push(['Items / points', align.items.length + ' / ' + items.points]);
  if (report) {
    st.push(['Reading level (Flesch-Kincaid grade)', 'mean ' + report.readingMean + ', max ' + report.readingMax + ' (the build warns above 11.5)']);
    st.push(['Single-answer items where the correct option is the longest', report.lengthBias.correctIsLongest + ' of ' + report.lengthBias.singleItems + ' (rule: at most 40%)']);
    st.push(['Single-answer items where the correct option is the shortest', report.lengthBias.correctIsShortest + ' of ' + report.lengthBias.singleItems + ' (rule: at most 40%)']);
  } else {
    st.push(['Lint statistics', 'not regenerated: `authoring/` was not present when this file was generated. Run `node tools/vault.js unlock` and then `node tools/gen-docs.js`.']);
  }
  out.push(table(['Measure', 'Result'], st));

  out.push('## Findings from the QA pass and what I did about them\n');
  out.push(table(['#', 'Finding', 'Evidence', 'Action'], [
    ['1', 'Length bias: the correct answer was the longest option', 'In 11 of 12 single-answer items the correct option was the longest, by a factor of 1.9 to 3.8. In select-all items the correct statements were 1.4 to 2 times longer than the wrong ones. A student who picks the longest option would have scored well without knowing the content.', 'Rewrote distractors in 19 items so they are parallel in length and detail. Added the length-bias rule to the builder so it cannot return. Now the correct option is the longest in 2 of 12 items, with ratios near 1.0.'],
    ['2', 'Limiting-word cue', 'Wrong options contained limiting words (absolutes such as "never" or "always", and words such as "only" or "all") far more often than correct options: 61% of wrong options against 22% of correct ones, using a fixed list of limiting words.', 'Rephrased factual distractors so wrong statements are wrong for a reason, not because of a limiting word. After the rewrite the same measure is 40% of wrong options (35 of 87) against 22% of correct ones (9 of 41); counting only the strongest absolutes it is 21% (18 of 87) against 15% (6 of 41). **Reduced, not eliminated.** The words that drive the remaining gap are listed in `private/REVIEW_DETAIL.md` (kept out of this public file on purpose). A test-wise student could still lean on it. Listed under weaknesses in TEACHER_REVIEW.md.'],
    ['3', 'Hints that gave the answer away', 'C3-02, C4-04, C5-03 and C6-02 had a hint that pointed straight at the answer, explained why distractors were wrong, or revealed how many options were decoys.', 'Reworded the hints so they point to a way of thinking, not to an option.'],
    ['4', 'Garbled explanation', 'C4-07 had a run-on sentence that merged three separate points.', 'Rewritten.'],
    ['5', 'Demo practice set', 'D2-01 and D2-02 options were unbalanced (same length-bias issue).', 'Rebalanced.'],
    ['6', 'Male anatomy diagram', 'The first drawing had a floating penis and vas deferens that did not connect to the other structures.', 'Redrawn. Both anatomy diagrams (and the demo house) still need your approval (TEACHER_REVIEW.md).'],
    ['7', 'Accessibility: contrast', 'The automated contrast test found the Resources chapter header at 4.25:1.', 'Darkened to pass 4.5:1. All six chapter palettes are now checked by a unit test.']
    ,['8', 'Answers in the text alternative of the labeling diagrams', 'Found while writing these docs. The "Text description of this diagram" under each labeling figure (and the same text in `items.json`, `content/figures.js` and inside the SVG files, including XML comments) named the structure beside every marker. Any student who opened the description, or the page source, could read the answers to C1-01 and C1-02.', 'The descriptions now describe shapes and positions only. The builder fails if a figure\'s alt text, description or SVG source contains any of the labels for an item that uses it, and `tests/unit/content.test.js` checks the same on the public files. **The earlier commits on this feature branch still contain the old text in their history** (SECURITY.md, "What is in git history").']
  ]));

  out.push('## Per-item results\n');
  out.push('Legend: **Pass** = passes the automated rules and my accuracy check against the build brief. **Fixed** = changed during the QA pass (now passes). **Flag** = needs your attention (see TEACHER_REVIEW.md).\n');
  out.push('For every item I checked that: there is one defensible answer; there are exactly two hints and neither names the answer; the explanation agrees with the key; the wording stays within the fiction-only, no-personal-questions, no-guaranteed-confidentiality rules. The item-specific accuracy notes say which answers are correct, so they are **not** in this public file. They are in `private/REVIEW_DETAIL.md`, delivered to you with the answer key.\n');
  const rows = [];
  let nPass = 0, nFix = 0, nFlag = 0;
  align.items.forEach((i) => {
    const n = qa[i.id];
    if (!n) rows.push([i.id, 'NOT REVIEWED', '', '']);
    else {
      const res = n.fix ? (n.flag ? 'Fixed; flagged' : 'Fixed; now passes') : (n.flag ? 'Passes; flagged' : 'Pass');
      if (!n.fix && !n.flag) nPass++; if (n.fix) nFix++; if (n.flag) nFlag++;
      rows.push([i.id, res, n.fix || '', n.flag || '']);
    }
  });
  out.push(table(['Item', 'Result', 'What changed', 'Flag for you'], rows));
  out.push('Summary: ' + nPass + ' pass with no change and no flag; ' + nFix + ' were changed during the QA pass; ' + nFlag + ' carry a flag for you. Items with both a change and a flag appear in both counts.\n');
  out.push('## Not done\n\n- No item was checked against a cited source, because no source page could be opened.\n- No item was checked against your slides, because they were not available.\n- No student has taken this. The time estimates, the reading level and the difficulty are unmeasured. After the first class, the Teacher Mode analytics (percent correct on first try, hint use, time per item) will show which items are too easy, too hard or confusing.\n');
  return out.join('\n');
}

const outDir = path.join(root, 'docs');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'BLUEPRINT.md'), blueprint());
fs.writeFileSync(path.join(outDir, 'ALIGNMENT_MATRIX.md'), alignment());
fs.writeFileSync(path.join(outDir, 'QA_REPORT.md'), qaReport());
console.log('wrote docs/BLUEPRINT.md, docs/ALIGNMENT_MATRIX.md, docs/QA_REPORT.md' + (report ? '' : ' (without lint statistics)'));
