/* ============================================================
   DATA — sliders, presets, organ + metric explanations
   Zones: good (green) · warn (amber) · bad (red) · info (blue)
   Slider tiers: [upToValue, label, zone, short effect text]
   ============================================================ */
const GROUPS = [
  { id: 'profile', icon: '🧍', title: 'Who is this person?', open: true },
  { id: 'move', icon: '🏃', title: 'Movement', open: true },
  { id: 'rest', icon: '😴', title: 'Sleep & Mind', open: false },
  { id: 'food', icon: '🥗', title: 'Food & Drink', open: false },
  { id: 'subs', icon: '🚭', title: 'Substances', open: false },
  { id: 'env', icon: '☀️', title: 'Environment', open: false },
  { id: 'habits', icon: '🧼', title: 'Daily Habits & Health History', open: false },
];

const SLIDERS = [
  /* ---------- profile ---------- */
  { id: 'age', group: 'profile', label: 'Age', unit: 'yrs', min: 13, max: 80, step: 1, def: 16,
    tiers: [[17, 'Teen', 'info', 'Still growing! Bones are racing toward their peak strength.'],
            [25, 'Young adult', 'info', 'Bones reach peak density around age 25–30.'],
            [40, 'Adult', 'info', 'Metabolism slowly starts to slow down.'],
            [60, 'Midlife', 'info', 'Muscle and bone slowly fade unless you train them. Arteries stiffen.'],
            [999, 'Older adult', 'info', 'Aging is natural — but habits decide how fast the body wears.']] },
  { id: 'height', group: 'profile', label: 'Height', unit: 'cm', min: 140, max: 200, step: 1, def: 170,
    tiers: [[999, 'Height', 'info', 'Used to calculate BMI. Taller bodies are scaled up in 3D.']] },
  { id: 'years', group: 'profile', label: 'Years living this way', unit: 'yrs', min: 0, max: 30, step: 0.5, def: 5,
    tiers: [[0.6, 'Just started', 'info', 'Mostly short-term effects: heart rate, breathing, mood.'],
            [3, 'A few years', 'info', 'Early changes start to show in the body.'],
            [10, 'About a decade', 'info', 'Long-term damage — or benefits — are clearly building.'],
            [999, 'Decades', 'info', 'Habits have shaped the body for a very long time.']] },

  /* ---------- movement ---------- */
  { id: 'cardio', group: 'move', label: 'Aerobic activity', unit: 'min/day', min: 0, max: 120, step: 5, def: 40,
    tiers: [[5, 'Inactive', 'bad', 'Heart & lungs get no training. Muscles and bones weaken.'],
            [30, 'Light', 'warn', 'A start! Teens need about 60 minutes a day.'],
            [75, 'Active', 'good', 'Stronger heart, lower resting heart rate, denser bones.'],
            [999, 'Very active', 'good', 'Athlete-level endurance: big, efficient heart & lungs.']] },
  { id: 'strength', group: 'move', label: 'Strength training', unit: 'days/wk', min: 0, max: 7, step: 1, def: 1,
    tiers: [[0, 'None', 'warn', 'No signal for muscles or bones to grow.'],
            [2, 'Some', 'good', 'Muscle fibers grow and bones add mineral.'],
            [4, 'Regular', 'good', 'Muscles get bigger & stronger; bones get denser.'],
            [999, 'Heavy', 'warn', 'Great gains — but rest days are when muscles actually rebuild.']] },
  { id: 'sitting', group: 'move', label: 'Sitting / screen time', unit: 'hrs/day', min: 0, max: 16, step: 0.5, def: 7,
    tiers: [[4, 'Low', 'good', 'Plenty of movement breaks keep blood and posture healthy.'],
            [8, 'Typical', 'warn', 'Long sitting slows blood sugar control and slumps posture.'],
            [11, 'High', 'bad', 'Muscles idle, posture slumps, blood sugar & cholesterol drift up.'],
            [999, 'Very high', 'bad', 'Very little movement — heart, bones and mood all pay for it.']] },

  /* ---------- sleep & mind ---------- */
  { id: 'sleep', group: 'rest', label: 'Sleep', unit: 'hrs/night', min: 3, max: 12, step: 0.5, def: 8,
    tiers: [[5.5, 'Severe shortage', 'bad', 'Brain can’t clear waste or store memories. Heart, mood & immunity suffer.'],
            [7, 'Short', 'warn', 'Foggy focus, higher stress hormones, cravings for sugar.'],
            [10, 'Healthy', 'good', 'Repair time! Brain files memories, muscles rebuild, hormones reset.'],
            [999, 'Very long', 'warn', 'Very long sleep can signal poor sleep quality or other health issues.']] },
  { id: 'stress', group: 'rest', label: 'Stress level', unit: '/10', min: 0, max: 10, step: 1, def: 3,
    tiers: [[2, 'Calm', 'good', 'Relaxed body: steady heart rate and blood pressure.'],
            [5, 'Normal', 'good', 'Some stress is normal and can even help you focus.'],
            [7, 'High', 'warn', 'Stress hormones raise heart rate, blood pressure and blood sugar.'],
            [999, 'Overloaded', 'bad', 'Constant stress hormones strain the heart, gut, skin & immune system.']] },
  { id: 'social', group: 'rest', label: 'Friends & support', unit: '/10', min: 0, max: 10, step: 1, def: 7,
    tiers: [[3, 'Isolated', 'bad', 'Loneliness raises stress hormones and weakens mood and immunity.'],
            [6, 'Some', 'warn', 'Having someone to talk to buffers stress.'],
            [999, 'Strong', 'good', 'Good support softens stress and lifts mood.']] },
  { id: 'relax', group: 'rest', label: 'Relaxation / mindfulness', unit: 'min/day', min: 0, max: 60, step: 5, def: 0,
    tiers: [[0, 'None', 'warn', 'No dedicated downtime for the nervous system.'],
            [15, 'A little', 'good', 'Slow breathing calms heart rate and stress hormones.'],
            [999, 'Daily habit', 'good', 'Calms the “fight-or-flight” system and lowers blood pressure.']] },

  { id: 'screens', group: 'rest', label: 'Screens in the hour before bed', unit: 'hrs', min: 0, max: 4, step: 0.5, def: 1,
    tiers: [[0.5, 'None', 'good', 'A dark, calm hour lets the sleep hormone melatonin rise.'],
            [1.5, 'Some', 'warn', 'Bright screens delay melatonin, so you fall asleep later.'],
            [999, 'A lot', 'bad', 'Late-night light delays and shortens sleep — less deep, restful sleep.']] },

  /* ---------- food & drink ---------- */
  { id: 'fruitveg', group: 'food', label: 'Fruits & vegetables', unit: 'servings/day', min: 0, max: 10, step: 1, def: 3,
    tiers: [[1, 'Rarely', 'bad', 'Few vitamins, minerals and fiber for cells to use.'],
            [3, 'Some', 'warn', 'Better than none — aim for 5 or more.'],
            [999, 'Plenty', 'good', 'Fiber, potassium and antioxidants protect arteries, gut and skin.']] },
  { id: 'sugar', group: 'food', label: 'Added sugar', unit: 'g/day', min: 0, max: 200, step: 5, def: 50,
    tiers: [[25, 'Low', 'good', 'Steady blood sugar; teeth and liver are happy.'],
            [60, 'Typical', 'warn', 'One soda ≈ 39 g. Daily spikes make the pancreas work hard.'],
            [110, 'High', 'bad', 'Blood sugar swings, fat builds in the liver, teeth decay faster.'],
            [999, 'Very high', 'bad', 'Insulin overworked; liver fat, cavities and weight gain rise.']] },
  { id: 'sodium', group: 'food', label: 'Sodium (salt)', unit: 'mg/day', min: 500, max: 6000, step: 100, def: 3200,
    tiers: [[1500, 'Very low', 'info', 'Your body needs some sodium for nerves and muscles.'],
            [2300, 'Recommended', 'good', 'Under 2,300 mg keeps fluid and blood pressure in balance.'],
            [3500, 'Above limit', 'warn', 'Extra salt holds water in the blood, raising pressure.'],
            [999, 'Very high', 'bad', 'Kidneys and arteries strain under constant high pressure.']] },
  { id: 'fried', group: 'food', label: 'Fried & fatty foods', unit: 'servings/day', min: 0, max: 6, step: 1, def: 1,
    tiers: [[0, 'None', 'good', 'No extra saturated fat to raise “bad” LDL cholesterol.'],
            [1, 'Occasional', 'good', 'A treat now and then is fine.'],
            [3, 'Frequent', 'warn', 'LDL cholesterol climbs and can start to stick inside arteries.'],
            [999, 'Constant', 'bad', 'LDL, triglycerides and liver fat rise — arteries clog sooner.']] },
  { id: 'fiber', group: 'food', label: 'Fiber (whole grains, beans)', unit: 'g/day', min: 0, max: 50, step: 1, def: 15,
    tiers: [[10, 'Low', 'bad', 'Gut bacteria go hungry; cholesterol & blood sugar rise.'],
            [25, 'Moderate', 'warn', 'Getting there! Aim for 25–35 g.'],
            [999, 'High', 'good', 'Feeds good gut bacteria and lowers cholesterol & blood sugar.']] },
  { id: 'protein', group: 'food', label: 'Protein', unit: 'g/day', min: 20, max: 200, step: 5, def: 60,
    tiers: [[45, 'Low', 'bad', 'Muscles and bones lack building blocks to repair.'],
            [110, 'Good', 'good', 'Amino acids rebuild muscle after exercise.'],
            [999, 'Very high', 'info', 'More than needed is simply burned or stored — no extra muscle.']] },
  { id: 'energy', group: 'food', label: 'Calories eaten vs. burned', unit: 'kcal/day', min: -500, max: 1000, step: 50, def: 0,
    tiers: [[-300, 'Big shortfall', 'bad', 'Not enough fuel: low energy, weaker bones and muscle, poor growth.'],
            [-100, 'Small shortfall', 'warn', 'Slow weight loss — your body still needs enough fuel.'],
            [150, 'Balanced', 'good', 'Energy in ≈ energy out keeps weight steady.'],
            [450, 'Surplus', 'warn', 'Extra energy is stored as body fat.'],
            [999, 'Big surplus', 'bad', 'Large surplus builds body fat, including around organs.']] },
  { id: 'water', group: 'food', label: 'Water', unit: 'cups/day', min: 0, max: 14, step: 1, def: 6,
    tiers: [[3, 'Dehydrated', 'bad', 'Blood thickens, urine turns dark, focus and skin suffer.'],
            [6, 'A bit low', 'warn', 'Kidneys are concentrating urine to save water.'],
            [999, 'Well hydrated', 'good', 'Blood flows easily; kidneys flush waste; skin stays plump.']] },
  { id: 'caffeine', group: 'food', label: 'Caffeine', unit: 'mg/day', min: 0, max: 800, step: 25, def: 100,
    tiers: [[100, 'Low', 'good', 'About 1 cola or ½ coffee. Teens should stay under ~100 mg.'],
            [250, 'Moderate', 'warn', 'Heart rate & blood pressure tick up; sleep may be shortened.'],
            [999, 'High', 'bad', 'Jitters, racing heart, anxiety — and lost sleep (energy drinks!).']] },
  { id: 'fish', group: 'food', label: 'Fish & healthy fats (nuts, olive oil)', unit: 'servings/wk', min: 0, max: 6, step: 1, def: 1,
    tiers: [[0, 'None', 'warn', 'Missing omega-3 fats that help calm inflammation.'],
            [2, 'Some', 'good', 'Omega-3 fats help lower triglycerides.'],
            [999, 'Plenty', 'good', 'Healthy fats lower triglycerides and inflammation.']] },
  { id: 'calcium', group: 'food', label: 'Calcium foods (dairy, greens)', unit: 'servings/day', min: 0, max: 5, step: 1, def: 2,
    tiers: [[1, 'Low', 'bad', 'Bones borrow calcium from themselves to run the body.'],
            [3, 'Good', 'good', 'Calcium is the main building mineral for bone.'],
            [999, 'High', 'good', 'Plenty of mineral supply for strong bones.']] },

  /* ---------- substances ---------- */
  { id: 'cigs', group: 'subs', label: 'Cigarettes', unit: 'per day', min: 0, max: 40, step: 1, def: 0,
    tiers: [[0, 'None', 'good', 'Lungs, heart and skin are not exposed to tobacco smoke.'],
            [5, 'Light', 'bad', 'Even a few a day damage arteries and cilia in the lungs.'],
            [15, 'Moderate', 'bad', 'Tar darkens lungs; arteries stiffen; skin wrinkles early.'],
            [999, 'Heavy', 'bad', 'Severe lung, heart and skin damage. Quitting helps at any age.']] },
  { id: 'vape', group: 'subs', label: 'Vaping (nicotine)', unit: 'pods/wk', min: 0, max: 10, step: 1, def: 0,
    tiers: [[0, 'None', 'good', 'No aerosol or nicotine reaching lungs and brain.'],
            [3, 'Light', 'bad', 'Nicotine raises heart rate and rewires the teen brain.'],
            [999, 'Heavy', 'bad', 'Airway irritation, strong addiction, and a racing heart.']] },
  { id: 'packyrs', group: 'subs', label: 'Past smoking (before quitting)', unit: 'pack-years', min: 0, max: 40, step: 1, def: 0,
    tiers: [[0, 'Never', 'good', 'No history of tobacco damage.'],
            [10, 'Some', 'warn', 'Past smoking left some damage. (1 pack-year = a pack a day for a year.)'],
            [999, 'A lot', 'bad', 'A long smoking history leaves lasting lung and artery damage.']] },
  { id: 'quitYrs', group: 'subs', label: 'Years since quitting', unit: 'yrs', min: 0, max: 30, step: 1, def: 0,
    tiers: [[0, 'Just quit / still smoking', 'info', 'Cilia start recovering within weeks, and heart risk begins to drop.'],
            [5, 'A few years', 'good', 'Heart-attack risk is dropping and lung function has partly recovered.'],
            [999, 'Many years', 'good', 'Much of the heart risk is gone — some lung damage can last forever.']] },
  { id: 'alcohol', group: 'subs', label: 'Alcohol (education only)', unit: 'drinks/wk', min: 0, max: 30, step: 1, def: 0,
    tiers: [[0, 'None', 'good', 'Alcohol is illegal and risky for teens. Liver and brain stay clear.'],
            [7, 'Some', 'warn', 'The liver works overtime; sleep and judgment suffer.'],
            [14, 'Frequent', 'bad', 'Fat builds in the liver; blood pressure and mood worsen.'],
            [999, 'Heavy', 'bad', 'Liver scarring, brain fog, weaker muscles and bones.']] },

  /* ---------- environment ---------- */
  { id: 'pollution', group: 'env', label: 'Polluted air / secondhand smoke', unit: '/10', min: 0, max: 10, step: 1, def: 1,
    tiers: [[2, 'Clean air', 'good', 'Lungs can clear themselves easily.'],
            [5, 'Some', 'warn', 'Tiny particles irritate airways and enter blood.'],
            [999, 'Heavy', 'bad', 'Particles inflame lungs and arteries — just like light smoking.']] },
  { id: 'sun', group: 'env', label: 'Midday sun (unprotected)', unit: 'hrs/day', min: 0, max: 6, step: 0.5, def: 1,
    tiers: [[0.5, 'Almost none', 'good', 'Little UV reaching skin DNA. (Some sun makes vitamin D.)'],
            [2, 'Some', 'warn', 'Skin cells repair most UV damage — not all of it.'],
            [999, 'A lot', 'bad', 'UV mutates skin DNA, breaks collagen and raises skin-cancer risk.']] },
  { id: 'sunscreen', group: 'env', label: 'Sunscreen / shade / clothing', unit: '%', min: 0, max: 100, step: 10, def: 50,
    tiers: [[30, 'Rarely', 'bad', 'UV photons hit skin cells directly.'],
            [70, 'Sometimes', 'warn', 'Partial protection.'],
            [999, 'Always', 'good', 'Sunscreen (SPF 30+) and shade block most UV light.']] },
];

const TOGGLES = [
  { id: 'brush', group: 'habits', label: 'Brushes & flosses 2× a day', def: true, on: 'Plaque bacteria are cleared before acid eats enamel.', off: 'Sticky plaque lets bacteria make acid that dissolves enamel.' },
  { id: 'vaccines', group: 'habits', label: 'Vaccines up to date', def: true, on: 'Immune memory cells recognize dangerous germs fast.', off: 'Immune system meets dangerous germs “cold.”' },
  { id: 'handwash', group: 'habits', label: 'Washes hands often', def: true, on: 'Fewer germs reach mouth, nose and eyes.', off: 'More germs get a free ride into the body.' },
  { id: 'asthma', group: 'habits', label: 'Has asthma (fictional history)', def: false, on: 'Airways inflame and narrow in a flare-up; breathing is harder.', off: '' },
  { id: 'famDM', group: 'habits', label: 'Family history of diabetes', def: false, on: 'Genes make blood-sugar problems more likely — habits matter even more.', off: '' },
  { id: 'famHeart', group: 'habits', label: 'Family history of high cholesterol', def: false, on: 'Genes can raise LDL no matter the diet — screening is important.', off: '' },
  { id: 'sick', group: 'habits', label: 'Sick with the flu today', def: false, on: 'Fever, fast pulse & breathing: the immune system is fighting viruses.', off: '' },
];

const SKIN_TONES = ['#f6d7bf', '#e8b99a', '#d09b74', '#b07a52', '#8a5a3a', '#5d3b27'];

/* ---------- presets: partial state overrides ---------- */
const PRESETS = [
  { id: 'default', name: 'Typical teen', icon: '🙂', note: 'A balanced starting point.', set: {} },
  { id: 'athlete', name: 'Student athlete', icon: '🏅', note: 'Daily training, great food, strong sleep.',
    set: { cardio: 90, strength: 4, sitting: 4, sleep: 9, stress: 3, fruitveg: 6, sugar: 25, sodium: 2200, fried: 0, fiber: 30, protein: 100, energy: 100, water: 10, caffeine: 0, calcium: 3, years: 4 } },
  { id: 'couch', name: 'Couch & snacks', icon: '🛋️', note: 'Low movement, sugary and salty food.',
    set: { cardio: 0, strength: 0, sitting: 12, sleep: 6, sugar: 130, sodium: 4800, fried: 4, fiber: 6, fruitveg: 1, energy: 450, water: 2, caffeine: 150, years: 10 } },
  { id: 'quitter', name: 'Quit smoking 5 years ago', icon: '🌱', note: 'Past smoker whose body has been healing.',
    set: { age: 45, packyrs: 20, quitYrs: 5, cigs: 0, years: 5, cardio: 40, sleep: 7.5, fruitveg: 4 } },
  { id: 'justquit', name: 'Just quit smoking', icon: '🚭', note: 'Same history, zero recovery time yet.',
    set: { age: 45, packyrs: 20, quitYrs: 0, cigs: 0, years: 5, cardio: 40, sleep: 7.5, fruitveg: 4 } },
  { id: 'smoker', name: 'Pack-a-day smoker', icon: '🚬', note: 'Shows lungs, heart & skin damage from tobacco.',
    set: { age: 38, cigs: 20, years: 18, cardio: 15, sleep: 6.5, stress: 6, caffeine: 250, pollution: 3, fruitveg: 2 } },
  { id: 'vaper', name: 'Vaping teen', icon: '💨', note: 'Nicotine aerosol, energy drinks, short sleep.',
    set: { vape: 7, years: 2, caffeine: 300, sleep: 6, stress: 6, cardio: 20, sugar: 90, sitting: 9 } },
  { id: 'allnighter', name: 'All-nighter', icon: '🌙', note: 'Short sleep, caffeine and high stress.',
    set: { sleep: 4, caffeine: 400, stress: 9, sitting: 12, cardio: 10, sugar: 100, water: 3, relax: 0, social: 4, years: 1 } },
  { id: 'fastfood', name: 'Fast-food diet', icon: '🍔', note: 'Fried food, soda, little fiber.',
    set: { fried: 5, sugar: 140, sodium: 5000, fiber: 5, fruitveg: 0, energy: 600, cardio: 20, water: 2, years: 12 } },
  { id: 'sun', name: 'Sun worshipper', icon: '🏖️', note: 'Hours of unprotected UV exposure.',
    set: { sun: 5, sunscreen: 0, water: 4, years: 15, age: 30 } },
  { id: 'champion', name: 'Heart-healthy champion', icon: '💚', note: 'Gold-standard choices across the board.',
    set: { cardio: 75, strength: 3, sitting: 4, sleep: 9, stress: 2, social: 9, relax: 15, fruitveg: 8, sugar: 20, sodium: 1900, fried: 0, fiber: 35, protein: 90, energy: 0, water: 9, caffeine: 0, calcium: 3, sunscreen: 90, sun: 0.5, pollution: 0, years: 10 } },
  { id: 'elderfit', name: 'Active 70-year-old', icon: '🚶', note: 'Aging well: walks, lifts, eats well.',
    set: { age: 70, years: 20, cardio: 50, strength: 3, sitting: 5, sleep: 7.5, stress: 2, social: 8, fruitveg: 7, sugar: 20, sodium: 1900, fiber: 30, protein: 90, water: 8, caffeine: 50, calcium: 3, sun: 1, sunscreen: 80, pollution: 1 } },
  { id: 'elderlow', name: 'Inactive 70-year-old', icon: '🪑', note: 'Same age, very different body.',
    set: { age: 70, years: 25, cardio: 0, strength: 0, sitting: 12, sleep: 6, stress: 6, social: 3, fruitveg: 1, sugar: 100, sodium: 4200, fried: 3, fiber: 8, protein: 40, energy: 250, water: 3, calcium: 0, cigs: 0 } },
  { id: 'sick', name: 'Flu day', icon: '🤒', note: 'See fever and immune response.',
    set: { sick: true, sleep: 7, water: 4, stress: 5 } },
];

/* ---------- body parts: what you can point the microscope at ---------- */
const ORGANS = {
  lungs: { name: 'Lungs', emoji: '🫁', role: 'Bring oxygen into the blood and remove carbon dioxide. About 480 million tiny air sacs (alveoli) swap gases with blood.',
    affected: 'Smoking & vaping · polluted air · asthma · aerobic exercise · infections' },
  heart: { name: 'Heart', emoji: '❤️', role: 'A muscle that pumps about 5 liters of blood every minute. Exercise makes it stronger; stress, smoking and high pressure make it work harder.',
    affected: 'Exercise · blood pressure · stress · caffeine & nicotine · sleep · cholesterol' },
  vessels: { name: 'Arteries & Blood Vessels', emoji: '🩸', role: 'Flexible tubes that carry blood everywhere. Healthy walls are smooth and stretchy; plaque (cholesterol, fat, cells) narrows and stiffens them.',
    affected: 'LDL / HDL cholesterol · smoking · salt · blood sugar · exercise · inflammation' },
  muscle: { name: 'Skeletal Muscle', emoji: '💪', role: 'Muscle fibers contract using actin and myosin filaments. Training causes tiny tears; with protein and rest, fibers repair thicker and stronger.',
    affected: 'Strength training · protein · sleep · calories · alcohol · inactivity · age' },
  bone: { name: 'Bones', emoji: '🦴', role: 'Living tissue! Bone cells constantly rebuild a honeycomb of calcium minerals. Impact exercise and calcium make bone denser; smoking and inactivity thin it.',
    affected: 'Weight-bearing exercise · calcium & vitamin D · smoking · alcohol · age · low calories' },
  skin: { name: 'Skin', emoji: '🧴', role: 'The body’s largest organ: a waterproof, germ-blocking shield. Collagen and elastin in the dermis keep it firm and stretchy.',
    affected: 'UV light · smoking · hydration · sleep · sugar · age · nutrition' },
  brain: { name: 'Brain & Nerves', emoji: '🧠', role: 'Billions of neurons talk across tiny gaps (synapses) using chemical messengers. Sleep lets the brain store memories and flush waste.',
    affected: 'Sleep · stress · caffeine · nicotine · alcohol · exercise · nutrition' },
  liver: { name: 'Liver', emoji: '🟤', role: 'Filters blood, stores energy, makes bile, and breaks down toxins. Too much sugar, fat or alcohol makes fat droplets build up in liver cells.',
    affected: 'Alcohol · added sugar · body fat · fried food · exercise' },
  stomach: { name: 'Stomach', emoji: '🫃', role: 'A muscular bag that churns food with acid and enzymes. Stress and alcohol can irritate its protective lining.',
    affected: 'Stress · alcohol · caffeine · diet' },
  gut: { name: 'Intestines & Microbiome', emoji: '🦠', role: 'Where nutrients are absorbed. Trillions of gut bacteria help digest fiber, train the immune system and influence mood.',
    affected: 'Fiber · fruits & veg · sugar · stress · sleep · alcohol' },
  kidney: { name: 'Kidneys', emoji: '🫘', role: 'Filter about 180 liters of blood a day, balancing water, salt and waste. They also help control blood pressure.',
    affected: 'Water · salt · blood pressure · blood sugar' },
  pancreas: { name: 'Pancreas', emoji: '🔶', role: 'Releases insulin — a “key” that lets sugar (glucose) move from blood into cells. Constant sugar spikes tire it out; cells may stop responding (insulin resistance).',
    affected: 'Sugar · body fat · exercise · sleep · genes' },
  teeth: { name: 'Teeth', emoji: '🦷', role: 'Enamel is the hardest substance in the body, but bacteria in plaque turn sugar into acid that dissolves it.',
    affected: 'Sugar · brushing & flossing · smoking · water' },
  fat: { name: 'Body Fat', emoji: '🟡', role: 'Fat cells store energy, cushion organs and release hormones. Some fat is essential; extra fat around the organs (visceral) raises inflammation and disease risk.',
    affected: 'Calories · activity · sleep · stress · sugar · genes' },
  blood: { name: 'Blood', emoji: '🩸', role: 'Red cells carry oxygen, white cells fight germs, platelets seal cuts, and plasma carries sugar, fats and hormones.',
    affected: 'Lungs & smoking · glucose · hydration · infection · iron & nutrition' },
};

/* ---------- metric explanations (mirrors the student worksheet columns) ---------- */
const METRIC_INFO = {
  rhr: { name: 'Resting Heart Rate', icon: '💓', tab: 'vitals',
    range: 'Teens & adults at rest: about 60–100 beats per minute (bpm). Well-trained athletes may be 40–60.',
    what: 'How many times your heart beats in one minute while you are calm and seated.',
    helps: 'Aerobic exercise, good sleep, relaxation, hydration, not smoking.',
    hurts: 'Inactivity, stress, nicotine, caffeine/energy drinks, dehydration, poor sleep, fever.',
    why: 'A lower resting rate usually means a stronger heart that pumps more blood each beat. A persistently high rate means the heart is working harder.',
    teach: 'A stronger heart beats less often because each beat moves more blood.' },
  bp: { name: 'Blood Pressure', icon: '🩺', tab: 'vitals',
    range: 'Normal: below 120 / 80 mmHg. Elevated: 120–129 / <80. Stage 1: 130–139 or 80–89. Stage 2: 140+ or 90+. (Systolic / diastolic.)',
    what: 'The force of blood pushing against artery walls — when the heart squeezes (systolic) and when it relaxes (diastolic).',
    helps: 'Exercise, less salt, fruits & vegetables (potassium), healthy weight, sleep, stress management.',
    hurts: 'Salt, smoking & vaping, heavy alcohol, stress, excess body weight, inactivity, stiff arteries.',
    why: 'High pressure silently damages arteries, heart, kidneys and brain over years. One reading is only a snapshot — doctors look for repeated readings.',
    teach: 'Blood pressure is often “silent” — you can’t feel it, so you have to measure it.' },
  rr: { name: 'Respiratory Rate', icon: '🌬️', tab: 'vitals',
    range: 'At rest: about 12–20 breaths per minute (teens often 12–18).',
    what: 'The number of breaths you take in one minute.',
    helps: 'Aerobic fitness, clean air, calm breathing, healthy lungs.',
    hurts: 'Lung damage (smoking, vaping), asthma flare-ups, infection/fever, anxiety, polluted air.',
    why: 'Breathing faster is the body’s way of getting more oxygen. A high resting rate can be an early sign something is wrong.',
    teach: 'Fast breathing at rest is a clue your body needs more oxygen — or is stressed or sick.' },
  temp: { name: 'Body Temperature', icon: '🌡️', tab: 'vitals',
    range: 'Typical: 97–99 °F (36.1–37.2 °C). Fever: 100.4 °F (38 °C) or higher.',
    what: 'The internal temperature of your body, tightly controlled by the brain.',
    helps: 'Rest, fluids, healthy immune function, vaccines, hand washing (fewer infections).',
    hurts: 'Infections (fever), dehydration, overheating during exercise in hot weather.',
    why: 'Fever is part of the immune response: heat slows some germs. Normal temperature varies by time of day and how it is measured.',
    teach: 'Fever isn’t the illness — it’s the immune system turning up the heat.' },
  spo2: { name: 'Oxygen Saturation (SpO₂)', icon: '🫧', tab: 'vitals',
    range: 'Normal at rest: about 95–100%. Below 92% needs medical attention.',
    what: 'The percent of hemoglobin (the oxygen carrier in red blood cells) that is currently carrying oxygen, measured by a clip on the finger.',
    helps: 'Healthy lungs, clean air, not smoking, treating asthma.',
    hurts: 'Lung damage, asthma attacks, infections, high altitude. Note: carbon monoxide from smoke can fool a pulse oximeter!',
    why: 'Every cell needs oxygen. Low saturation means not enough oxygen is reaching the body.',
    teach: 'SpO₂ tells you how loaded up your red blood cells are with oxygen.' },
  sleepdur: { name: 'Sleep Duration', icon: '🛌', tab: 'vitals',
    range: 'Teens (13–18): 8–10 hours. Adults: 7–9 hours. Older adults: 7–8 hours.',
    what: 'Total hours of sleep in a 24-hour period.',
    helps: 'Regular schedule, dark cool room, screens off before bed, daytime exercise, limiting caffeine.',
    hurts: 'Late-night screens, caffeine, stress, irregular schedule, alcohol.',
    why: 'During sleep the brain stores memories and clears waste; muscles repair; growth and immune hormones are released.',
    teach: 'Sleep is when your body does its repair work.' },
  sv: { name: 'Stroke Volume', icon: '🫀', tab: 'vitals',
    range: 'Typical at rest: 60–100 mL of blood per beat. Trained athletes: 90–120 mL.',
    what: 'How much blood the left ventricle pushes out with each heartbeat (resting cardiac output ÷ heart rate).',
    helps: 'Endurance training, which enlarges and strengthens the heart muscle.',
    hurts: 'Inactivity, very high blood pressure over time, damaged heart muscle.',
    why: 'This is why athletes have low resting heart rates: each beat moves more blood, so fewer beats are needed.',
    teach: 'Bigger stroke volume = fewer beats needed.' },
  glucose: { name: 'Fasting Blood Glucose', icon: '🍬', tab: 'labs',
    range: 'Normal: 70–99 mg/dL after fasting ≥8 hours. Prediabetes: 100–125. Diabetes: 126 or higher on repeated tests.',
    what: 'The amount of sugar in the blood after not eating for at least 8 hours.',
    helps: 'Exercise, fiber, healthy weight, sleep, less added sugar.',
    hurts: 'Lots of added sugar, excess body fat, inactivity, sleep loss, chronic stress, family history.',
    why: 'Over time high blood sugar damages blood vessels, nerves, eyes and kidneys. Prediabetes can often be reversed with habits.',
    teach: 'When cells stop answering insulin, sugar piles up in the blood.' },
  a1c: { name: 'HbA1c (3-month blood sugar)', icon: '📆', tab: 'labs',
    range: 'Normal: below 5.7%. Prediabetes: 5.7–6.4%. Diabetes: 6.5% or higher.',
    what: 'The percent of hemoglobin coated with sugar — an average of blood sugar over about 3 months.',
    helps: 'Same habits that lower fasting glucose: activity, fiber, less sugar, healthy weight.',
    hurts: 'Chronic high blood sugar, inactivity, excess body fat.',
    why: 'Sugar slowly sticks to red blood cells (“glycation”). A1c shows the long-term story that one fasting number can’t.',
    teach: 'A1c is a 3-month average — a movie, not a snapshot.' },
  tc: { name: 'Total Cholesterol', icon: '🧪', tab: 'labs',
    range: 'Youth (<20): below 170 mg/dL desirable. Adults: below 200 mg/dL desirable.',
    what: 'All the cholesterol carried in the blood: LDL + HDL + part of triglycerides.',
    helps: 'Fiber, fruits & vegetables, exercise, healthy weight, not smoking.',
    hurts: 'Saturated & trans fat, excess body fat, inactivity, smoking, genetics.',
    why: 'Cholesterol is needed to build cells, but too much of the wrong kind builds plaque in arteries.',
    teach: 'Total cholesterol is a sum — look at the parts (LDL, HDL) to understand it.' },
  ldl: { name: 'LDL Cholesterol (“bad”)', icon: '🟡', tab: 'labs',
    range: 'Youth: below 110 mg/dL. Adults: below 100 mg/dL optimal; 130+ high.',
    what: 'Low-density lipoprotein carries cholesterol to tissues. Extra LDL can stick in artery walls.',
    helps: 'Fiber, fruits & vegetables, healthy fats (fish, nuts), exercise, healthy weight.',
    hurts: 'Fried & fatty foods, saturated/trans fat, excess weight, smoking, family history.',
    why: 'LDL that gets oxidized inside artery walls starts the plaque that causes heart attacks and strokes.',
    teach: 'LDL drops cholesterol off in artery walls; lower is better.' },
  hdl: { name: 'HDL Cholesterol (“good”)', icon: '🟢', tab: 'labs',
    range: 'Youth: above 45 mg/dL. Adults: 40+ mg/dL; 60+ is protective.',
    what: 'High-density lipoprotein carries extra cholesterol away from arteries back to the liver.',
    helps: 'Regular aerobic exercise, not smoking, healthy weight, healthy fats.',
    hurts: 'Smoking, inactivity, excess body fat, very high sugar intake.',
    why: 'HDL works like a cleanup crew for artery walls. Low HDL means fewer cleaners.',
    teach: 'HDL is the cleanup crew — exercise and not smoking boost it.' },
  tg: { name: 'Triglycerides', icon: '🧈', tab: 'labs',
    range: 'Youth 10–19: below 90 mg/dL. Adults: below 150 mg/dL. 200+ is high.',
    what: 'A type of fat in the blood that stores extra calories from food, especially sugar and alcohol.',
    helps: 'Less sugar and alcohol, aerobic exercise, healthy weight, fiber.',
    hurts: 'Sugary drinks, refined carbs, alcohol, excess body fat, inactivity.',
    why: 'High triglycerides add to artery plaque risk and can inflame the pancreas when very high.',
    teach: 'Extra sugar you don’t burn can become blood fat.' },
  crp: { name: 'Inflammation (hs-CRP)', icon: '🔥', tab: 'labs',
    range: 'Low risk: below 1 mg/L. Moderate: 1–3. High: above 3 (infection can raise it temporarily).',
    what: 'A protein the liver makes when the body has inflammation.',
    helps: 'Exercise, sleep, fruits & vegetables, healthy weight, not smoking.',
    hurts: 'Smoking, excess body fat, poor sleep, chronic stress, infection, heavy alcohol.',
    why: 'Quiet, long-lasting inflammation contributes to artery plaque, diabetes and other conditions.',
    teach: 'Chronic low-level inflammation is the “smoke” behind many diseases.' },
  cohb: { name: 'Carbon Monoxide in Blood (COHb)', icon: '☁️', tab: 'labs',
    range: 'Non-smokers: under 2%. Smokers commonly 3–10%.',
    what: 'The percent of hemoglobin stuck to carbon monoxide (CO) instead of oxygen. CO comes from cigarette smoke and vapor.',
    helps: 'Not smoking, avoiding secondhand smoke and polluted air.',
    hurts: 'Smoking, secondhand smoke, heavy traffic fumes.',
    why: 'CO grabs hemoglobin ~200× tighter than oxygen. Red blood cells carry less oxygen — even though a pulse oximeter may still read “normal.”',
    teach: 'Smoke steals the seats on your red blood cells’ oxygen bus.' },
  bmi: { name: 'Body Mass Index (BMI)', icon: '⚖️', tab: 'body',
    range: 'Adults: 18.5–24.9 is the screening “healthy” range. For teens, BMI is read as a percentile for age and sex.',
    what: 'Weight ÷ height² — a quick screening number. It is NOT a diagnosis and cannot tell muscle from fat.',
    helps: 'Balanced eating, regular activity, enough sleep.',
    hurts: 'Long-term calorie surplus or shortage, inactivity, poor sleep, chronic stress.',
    why: 'BMI helps screen large groups, but a muscular athlete can have a “high” BMI with low body fat. Always consider other measures.',
    teach: 'BMI is a screening tool, not a verdict — it can’t see muscle, fat or fitness.' },
  bodyfat: { name: 'Body Fat Percentage', icon: '🧈', tab: 'body',
    range: 'Roughly 10–30% for teens and adults, varying by sex, age and sport. Some fat is essential.',
    what: 'The share of your body weight that is fat tissue.',
    helps: 'Activity, strength training, balanced calories, sleep, fiber.',
    hurts: 'Calorie surplus, inactivity, sleep loss, chronic stress, sugary drinks.',
    why: 'Fat around the organs (visceral fat) releases inflammatory signals. Too little fat is also unhealthy.',
    teach: 'Where fat is stored — and how much — matters more than weight alone.' },
  muscle: { name: 'Muscle Mass', icon: '💪', tab: 'body',
    range: 'Shown relative to a typical person of your height (100%). Higher usually means more strength and a better metabolism.',
    what: 'How much skeletal muscle tissue you have compared with an average build.',
    helps: 'Strength training, protein, sleep, enough calories.',
    hurts: 'Inactivity, low protein, big calorie shortfalls, alcohol, aging without training.',
    why: 'Muscle supports joints, burns blood sugar, and protects against falls as we age.',
    teach: 'Use it or lose it — muscle grows only when challenged.' },
  bone: { name: 'Bone Density (T-score estimate)', icon: '🦴', tab: 'body',
    range: 'Healthy: T-score −1.0 or higher. Low bone mass: −1.0 to −2.5. Osteoporosis: −2.5 or lower.',
    what: 'How much mineral (mostly calcium) is packed into your bones compared with a healthy young adult.',
    helps: 'Weight-bearing & strength exercise, calcium, vitamin D, protein, enough calories.',
    hurts: 'Inactivity, smoking, heavy alcohol, low calories, low calcium, aging.',
    why: 'You build most of your lifetime bone before about age 30 — the teen years are a one-time “bone bank” opportunity.',
    teach: 'Teen years are when you make deposits in your bone bank.' },
  vo2: { name: 'Aerobic Fitness (VO₂ max)', icon: '🏃', tab: 'body',
    range: 'Typical young people: 35–45 mL/kg/min. Fit: 45–55. Elite endurance athletes: 60+.',
    what: 'The most oxygen your body can use during all-out exercise, per kilogram per minute.',
    helps: 'Regular aerobic exercise, healthy lungs, healthy weight.',
    hurts: 'Inactivity, smoking & vaping, excess body fat, aging.',
    why: 'VO₂ max is one of the strongest predictors of long-term health and lifespan.',
    teach: 'Fitness is how much oxygen your body can put to work.' },
  fev1: { name: 'Lung Function (FEV₁)', icon: '🫁', tab: 'body',
    range: 'At least 80% of the predicted value for your age, height and sex is considered normal.',
    what: 'The amount of air you can blow out in 1 second after a deep breath (shown as % of predicted).',
    helps: 'Aerobic exercise, not smoking, clean air, asthma treatment.',
    hurts: 'Smoking & vaping, polluted air, asthma flare-ups, infections.',
    why: 'Lung tissue lost to smoking doesn’t grow back; quitting slows further loss.',
    teach: 'Lungs peak in your 20s — protect them early.' },
  hydration: { name: 'Hydration (Urine Color)', icon: '💧', tab: 'body',
    range: 'Pale yellow (like lemonade) = well hydrated. Dark amber (like apple juice) = drink water.',
    what: 'How much water your body has, shown by how concentrated your urine is.',
    helps: 'Drinking water through the day, eating fruits & vegetables.',
    hurts: 'Too little water, heavy sweating, caffeine & alcohol, illness.',
    why: 'Water keeps blood flowing, regulates temperature, and lets kidneys flush waste.',
    teach: 'Pale yellow is a quick hydration check.' },
  focus: { name: 'Focus & Memory', icon: '🧠', tab: 'systems',
    range: 'Score 0–100: higher is sharper. (A simulation score, not a medical test.)',
    what: 'A simple indicator of attention and memory, which depend on sleep, stress, nutrition and exercise.',
    helps: 'Sleep, aerobic exercise, balanced food, hydration, calm mind.',
    hurts: 'Sleep loss, stress, alcohol, nicotine, dehydration, too much caffeine.',
    why: 'Sleep and exercise physically change how well neurons connect.',
    teach: 'A rested, moving body has a sharper brain.' },
  mood: { name: 'Mood & Energy', icon: '😊', tab: 'systems',
    range: 'Score 0–100: higher is better. (A simulation score.)',
    what: 'How good and energetic you feel, shaped by sleep, activity, stress and support.',
    helps: 'Exercise, sleep, friends, sunlight, relaxation.',
    hurts: 'Sleep loss, chronic stress, isolation, illness.',
    why: 'Exercise releases mood-boosting chemicals; poor sleep and stress drain them.',
    teach: 'Mind and body are a team — each affects the other.' },
  immune: { name: 'Immune Readiness', icon: '🛡️', tab: 'systems',
    range: 'Score 0–100: higher means a more ready defense. (A simulation score.)',
    what: 'How ready white blood cells and antibodies are to defend you.',
    helps: 'Sleep, fruits & vegetables, moderate exercise, vaccines, hand washing, low stress.',
    hurts: 'Sleep loss, chronic stress, smoking, heavy alcohol, high sugar.',
    why: 'A strong immune system sees and removes germs early.',
    teach: 'Sleep and vaccines are two of the best immune boosters.' },
  skin: { name: 'Skin Health', icon: '🧴', tab: 'systems',
    range: 'Score 0–100: higher is healthier. (A simulation score.)',
    what: 'How firm, hydrated and protected from UV and toxins your skin is.',
    helps: 'Sunscreen, hydration, sleep, vitamin-rich foods, not smoking.',
    hurts: 'Unprotected sun, smoking, dehydration, sleep loss, aging.',
    why: 'Skin damage from UV adds up over a lifetime and raises skin-cancer risk.',
    teach: 'UV damage adds up — protect skin early.' },
  liver: { name: 'Liver Fat', icon: '🟤', tab: 'systems',
    range: 'Healthy liver: under about 5% fat by weight.',
    what: 'The share of liver weight that is fat. Too much is called fatty liver disease.',
    helps: 'Healthy weight, exercise, less sugar, no alcohol.',
    hurts: 'Alcohol, high added sugar, excess body fat, fried food, insulin resistance.',
    why: 'Fatty liver can progress to inflammation and scarring — and it is mostly reversible early.',
    teach: 'Liver cells can fill up with fat droplets — but they can empty again.' },
  kidney: { name: 'Kidney Strain', icon: '🫘', tab: 'systems',
    range: 'Score 0–100: lower strain is better. (A simulation score.)',
    what: 'How hard the kidneys have to work to filter blood.',
    helps: 'Water, low salt, healthy blood pressure and blood sugar.',
    hurts: 'Salt, dehydration, high blood pressure, high blood sugar.',
    why: 'Kidneys can lose function without symptoms until damage is advanced.',
    teach: 'Water and less salt = happy kidneys.' },
  gut: { name: 'Gut Health', icon: '🦠', tab: 'systems',
    range: 'Score 0–100: higher is healthier. (A simulation score.)',
    what: 'Balance of good gut bacteria, fed by fiber and plants.',
    helps: 'Fiber, fruits & vegetables, water, sleep, low stress.',
    hurts: 'Sugar, alcohol, stress, fried food, low fiber.',
    why: 'Gut bacteria help digestion, immunity and even mood.',
    teach: 'Feed the good bacteria with fiber.' },
  dental: { name: 'Dental Health', icon: '🦷', tab: 'systems',
    range: 'Score 0–100: higher is healthier. (A simulation score.)',
    what: 'How well enamel is protected from acid made by mouth bacteria.',
    helps: 'Brushing & flossing, water, less sugar, fluoride, not smoking.',
    hurts: 'Frequent sugar, skipping brushing, smoking.',
    why: 'Cavities are a bacterial disease fueled by sugar.',
    teach: 'Bacteria + sugar = acid. Brush the bacteria away.' },
};

const METRIC_TABS = [
  { id: 'vitals', label: 'Vitals' },
  { id: 'labs', label: 'Blood tests' },
  { id: 'body', label: 'Body' },
  { id: 'systems', label: 'Systems' },
];
