import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
import { start } from '../../tools/serve.js';
import { playAll } from './driver.mjs';
const shots = process.argv[2];
const srv = await start(8124);
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 1366, height: 768 } });
const p = await ctx.newPage();
const errs = []; p.on('pageerror', (e) => errs.push('PAGEERR ' + e.message)); p.on('console', (m) => { if (m.type() === 'error') errs.push('CONSOLE ' + m.text()); });
const t0 = Date.now();
const seen = await playAll(p, { url: 'http://localhost:8124/index.html', shots, shotEvery: !!shots });
console.log('answered', seen.length, 'questions in', Math.round((Date.now() - t0) / 1000), 's');
await p.getByRole('button', { name: 'Submit final answers' }).click();
await p.getByRole('button', { name: 'Yes, submit' }).click();
await p.waitForSelector('text=Summative complete');
await p.waitForTimeout(2200);
if (shots) await p.screenshot({ path: shots + '/results.png', fullPage: true });
console.log((await p.locator('.bigscore').textContent()), (await p.locator('.big-sub').textContent()));
console.log(errs.join('\n') || 'no console errors');
await b.close(); srv.close();
