// MISSION 7: HEALTH DECISION CHALLENGE (integrated)  -  domain "integrated"  -  9 points
const snack = (id, ctx, prods, best, evidence, why) => ({ kind: 'q', block: 'm7b', q: {
  id: 'i-fuel-' + id, slot: 'i-fuel', domain: 'integrated', concept: 'int-snack', skill: 'integrate', difficulty: 3, qt: 'integrated scenario: labels + claims', lvl: 'AN', pts: 2, sec: 110, major: true,
  type: 'slots', stim: { title: ctx, table: { cap: 'Nutrition Facts excerpt, per serving, with the front-of-package claim', cols: ['', ...prods.map((p) => p.name)], rows: [['Front claim', ...prods.map((p) => p.claim)], ['Calories', ...prods.map((p) => p.cal)], ['Protein', ...prods.map((p) => p.pro)], ['Added sugars', ...prods.map((p) => p.add)], ['Sodium', ...prods.map((p) => p.sod)]] } },
  prompt: 'Choose the snack that best fits {N1}\'s need and the strongest reason for your choice.',
  slots: [{ k: 'prod', label: 'Best snack for {N1}', opts: prods.map((p, i) => ['p' + i, p.name]) }, { k: 'why', label: 'Strongest reason', opts: evidence }],
  ans: { prod: 'p' + best, why: 'w1' }, hints: ['Use the label numbers that match the stated need. The front claim does not tell you whether the need is met.'], explain: why
} });

export default {
  id: 'm7', num: 7, title: 'Health Decision Challenge', theme: 'final', est: 7, kicker: 'MISSION 7',
  blurb: 'Jordan\'s week. Combine nutrition, activity, marketing literacy, goals and evidence to make decisions that fit real life.',
  stages: [
    { kind: 'choice', id: 'focus', block: 'm7a', title: 'Jordan\'s week', paras: ['Jordan is a fictional 10th grader who plays on the school soccer team, has a busy schedule, and wants to build a few healthy routines. Jordan can start with one focus this week.'], prompt: 'Where should Jordan start? (Both are reasonable. Your choice shapes the next scenario and is not scored.)', opts: [['fuel', 'Fuel: plan snacks and meals around practice'], ['move', 'Movement: plan the week\'s activity around the team schedule']] },
    { kind: 'pool', id: 'i-branch', by: 'focus', groups: [
      { when: 'fuel', pick: 1, items: [
        snack('1', 'After practice, Jordan has $3 and a vending machine with three snacks. Jordan needs a snack with at least 8 g of protein and 10 g or less of added sugars.', [{ name: 'Fruity Bites', claim: 'Made with real fruit!', cal: '90', pro: '1 g', add: '12 g', sod: '10 mg' }, { name: 'Protein Crunch Bar', claim: 'Fuel your day', cal: '190', pro: '10 g', add: '5 g', sod: '180 mg' }, { name: 'Salty Snack Mix', claim: 'Only 110 calories!', cal: '110', pro: '3 g', add: '0 g', sod: '420 mg' }], 1, [['w1', 'The Protein Crunch Bar has 10 g protein and 5 g added sugars, matching both requirements.'], ['w2', 'Fruity Bites says "real fruit" on the front, which shows it meets the protein requirement.'], ['w3', 'Salty Snack Mix has the fewest calories on the front, which makes it the best match.'], ['w4', 'The bar with the biggest brand on the front must be the strongest choice.']], 'Only the Protein Crunch Bar meets both the 8 g protein and the 10 g added-sugar limits. Front claims (real fruit, only 110 calories) do not show whether the need is met.'),
        snack('2', 'Before an early game, Jordan needs a quick energy snack with at least 25 g of carbohydrate and no more than 150 mg of sodium. Jordan does not need extra protein.', [{ name: 'Banana Oat Cup', claim: 'Simple energy', cal: '210', pro: '4 g', add: '8 g', sod: '90 mg' }, { name: 'Cheese Puff Pack', claim: 'Bold flavor', cal: '160', pro: '3 g', add: '0 g', sod: '380 mg' }, { name: 'Zero Sugar Fizz Bar', claim: 'Zero sugar!', cal: '70', pro: '12 g', add: '0 g', sod: '200 mg' }], 0, [['w1', 'The Banana Oat Cup is the only one with enough energy for the need while staying within the 150 mg sodium limit (90 mg).'], ['w2', 'The Zero Sugar Fizz Bar has the most protein, so it is the best choice for quick energy.'], ['w3', 'The Cheese Puff Pack has "bold" flavor, so it must provide more usable energy.'], ['w4', 'The lowest-calorie snack is always the healthiest for an athlete.']], 'The Banana Oat Cup supplies the energy (210 calories) and keeps sodium low (90 mg). The Zero Sugar Fizz Bar is high in protein but has only 70 calories; the puffs exceed the sodium limit.')
      ] },
      { when: 'move', pick: 1, items: [
        { kind: 'q', block: 'm7b', q: {
          id: 'i-move-1', slot: 'i-move', domain: 'integrated', concept: 'int-plan', skill: 'integrate', difficulty: 3, qt: 'integrated scenario: FITT adjustment', lvl: 'AN', pts: 2, sec: 100, major: true,
          type: 'slots', stim: { title: 'Jordan\'s current week', paras: ['Soccer practice: Monday, Wednesday and Friday, 60 minutes, vigorous. Other days: none. No muscle-strengthening activity. Jordan wants to meet the national teen recommendation and has 30 minutes free on Tuesday, Thursday and the weekend.'] },
          prompt: 'Choose the FITT change that most directly closes the biggest gap, and the reason that supports it.',
          slots: [{ k: 'chg', label: 'Best change', opts: [['c1', 'Add 30 minutes of brisk walking or a bodyweight circuit on Tuesday, Thursday and the weekend'], ['c2', 'Make Monday\'s practice longer and skip other days'], ['c3', 'Switch soccer to a lighter intensity to avoid soreness'], ['c4', 'Only stretch gently on the free days']] }, { k: 'why', label: 'Strongest reason', opts: [['w1', 'It adds moderate-to-vigorous minutes on the empty days and can include muscle-strengthening, addressing both gaps.'], ['w2', 'Stretching counts fully as moderate-to-vigorous activity.'], ['w3', 'Teens only need activity on days with team practice.'], ['w4', 'One very long day can replace the rest of the week.']] }],
          ans: { chg: 'c1', why: 'w1' }, hints: ['Compare the week to the recommendation: which days are missing activity, and what type of activity is absent?'],
          explain: 'Jordan has vigorous days but no activity on four days and no muscle-strengthening. Adding 30-minute moderate sessions on the empty days, including bodyweight work, increases Frequency and changes Type.' } },
        { kind: 'q', block: 'm7b', q: {
          id: 'i-move-2', slot: 'i-move', domain: 'integrated', concept: 'int-plan', skill: 'integrate', difficulty: 3, qt: 'integrated scenario: FITT adjustment', lvl: 'AN', pts: 2, sec: 100, major: true,
          type: 'slots', stim: { title: 'Jordan\'s current week', paras: ['Jordan walks slowly with a friend for 30 minutes after school on five days. During the walks Jordan can easily sing along to music. Jordan does no muscle-strengthening activity and wants to meet the national teen recommendation.'] },
          prompt: 'Choose the FITT change that most directly closes the biggest gaps, and the reason that supports it.',
          slots: [{ k: 'chg', label: 'Best change', opts: [['c1', 'Walk faster or add hills until talking is possible but singing is not, lengthen some walks toward 60 minutes, and add a bodyweight circuit on three days'], ['c2', 'Keep the same easy pace and add 5 minutes to each walk'], ['c3', 'Replace some walks with gentle stretching'], ['c4', 'Walk even more slowly for a longer time']] }, { k: 'why', label: 'Strongest reason', opts: [['w1', 'It raises intensity and time toward 60 minutes of moderate-to-vigorous activity and adds a muscle-strengthening type.'], ['w2', 'Singing during exercise shows the effort is already vigorous.'], ['w3', 'Light activity counts fully toward the daily 60 moderate-to-vigorous minutes.'], ['w4', 'Muscle-strengthening is only needed by athletes in the weight room.']] }],
          ans: { chg: 'c1', why: 'w1' }, hints: ['If Jordan can sing easily, what intensity is that? Compare the week to each recommendation.'],
          explain: 'Being able to sing means the walks are light intensity, which does not count toward the daily moderate-to-vigorous minutes. Raising the intensity, lengthening some sessions and adding muscle-strengthening closes the gaps.' } }
      ] }
    ] },
    { kind: 'q', block: 'm7c', q: {
      id: 'i-env', domain: 'integrated', concept: 'int-env', skill: 'evaluate', difficulty: 3, qt: 'integrated scenario: individual vs systemic', lvl: 'AN', pts: 2, sec: 80, major: true,
      type: 'mc', stim: { title: 'Around the field', paras: ['Near Jordan\'s field there are two fast-food restaurants and a convenience store. The closest supermarket is 4 miles away. A soda company sponsors the league and posts ads at the field. Jordan\'s coach says, "Health is all personal responsibility."'] },
      prompt: 'Which statement best describes how Jordan\'s food and activity choices are shaped?',
      opts: [['a', 'Personal choices matter, and they are also shaped by what is available, affordable, convenient and marketed nearby, so both individual and system-level changes can help.'], ['b', 'Only personal willpower matters, so surroundings, prices and marketing have no real effect on what teens end up choosing to eat or do.'], ['c', 'Only the surroundings matter, so Jordan\'s own strategies, knowledge and decisions make no difference to what Jordan eats or does.'], ['d', 'Marketing affects adults but never teens, so the soda sponsorship at the field is not worth examining or discussing with the team.']],
      ans: 'a', hints: ['Look for the option that holds BOTH individual choices and the food environment as influences.'],
      explain: 'Health choices are made by individuals inside a food environment. Availability, price, convenience and marketing all shape what is easy to choose, so individual strategies and system-level changes both matter.' } },
    { kind: 'q', block: 'm7c', q: {
      id: 'i-claim', domain: 'integrated', concept: 'int-claims', skill: 'integrate', difficulty: 3, qt: 'integrated scenario: PQVD', lvl: 'AP', pts: 2, sec: 90, major: true,
      type: 'mc', stim: { title: 'Jordan\'s feed', paras: ['A teammate shares an influencer video: "This powder fixes your recovery in 24 hours!" There is a discount code in the caption and no ingredient list. Jordan has $25 of savings.'] },
      prompt: 'Which plan best applies PAUSE, QUESTION, VERIFY, DECIDE?',
      opts: [['a', 'Wait before buying, ask who profits and what evidence is shown, check the claim with the FDA, CDC or a registered dietitian, then decide using that evidence.'], ['b', 'Buy the powder right away while the discount code still works, then look for research only if it does not seem to work.'], ['c', 'Ignore the video because influencers are never right about anything, and do not look into the claim or the ingredients at all.'], ['d', 'Ask the teammate how many views and likes the video has, and decide based on how popular the post is with other teens.']],
      ans: 'a', hints: ['The best plan follows all four steps in order and ends with a decision based on evidence.'],
      explain: 'The strongest plan pauses, questions who profits and what evidence exists, verifies with credible sources, and decides from evidence. Buying first, rejecting everything, or relying on popularity skips key steps.' } },
    { kind: 'q', block: 'm7d', q: {
      id: 'i-goal', domain: 'integrated', concept: 'int-goal', skill: 'create', difficulty: 3, qt: 'integrated scenario: build a plan', lvl: 'SY', pts: 3, sec: 140, major: true,
      type: 'slots', goalPreview: true,
      stim: { title: 'Jordan builds a plan', paras: ['Jordan lives in a neighborhood where the closest full-service grocery store is 3 miles away and there is no car in the household. Jordan wants to eat more vegetables with dinner and be active for 20 minutes after school.'] },
      prompt: 'Build a realistic plan for Jordan by choosing one piece for each part.',
      slots: [
        { k: 'goal', label: 'The SMART goal', opts: [['g1', 'Eat one serving of vegetables with dinner on 4 nights a week and walk briskly for 20 minutes after school on 3 days a week, for the next 4 weeks'], ['g2', 'Eat perfectly and exercise every day from now on'], ['g3', 'Be healthier by next month']] },
        { k: 'barrier', label: 'A strategy for the access barrier', opts: [['b1', 'Buy frozen or canned vegetables (no added salt) from the corner store or a monthly bus trip, and keep them stocked'], ['b2', 'Skip vegetables unless a car becomes available'], ['b3', 'Wait for the neighborhood to add a supermarket']] },
        { k: 'evid', label: 'How Jordan checks a new claim about a "miracle" supplement', opts: [['v1', 'Pause, ask who profits, and verify with credible sources such as the FDA or a registered dietitian'], ['v2', 'Trust it if it has many likes'], ['v3', 'Try it first and look for evidence later']] },
        { k: 'track', label: 'How Jordan tracks progress', opts: [['k1', 'A weekly check of nights with vegetables and days walked, then adjust the plan'], ['k2', 'Only decide at the end of the year'], ['k3', 'Rely on remembering how it felt']] }
      ],
      ans: { goal: 'g1', barrier: 'b1', evid: 'v1', track: 'k1' }, hints: ['Check each choice for SMART qualities and for fit with Jordan\'s real situation, including the food environment.', 'Plans that depend on a change Jordan cannot control, or that have no way to track progress, are weaker.'],
      explain: 'The strongest plan is specific, measurable, achievable and time-bound; it works around the access barrier with frozen or canned vegetables; it uses PAUSE, QUESTION, VERIFY, DECIDE for new claims; and it tracks progress weekly.' } }
  ]
};
