// Source registry. Every statistic or guideline used in the assessment is listed here (shown in "Sources / Learn More").
// Only government, public-health and peer-reviewed sources are used as authority. See docs/SOURCES.md for details and verification notes.
export const SOURCES = [
  { id: 'pag', org: 'U.S. Dept. of Health and Human Services (HHS)', title: 'Physical Activity Guidelines for Americans, 2nd edition (2018)', url: 'https://health.gov/our-work/nutrition-physical-activity/physical-activity-guidelines/current-guidelines', used: 'Teen recommendations: 60 min/day moderate-to-vigorous; vigorous, muscle- and bone-strengthening on at least 3 days/week' },
  { id: 'cdc-intensity', org: 'CDC', title: 'Measuring Physical Activity Intensity (talk test and perceived exertion)', url: 'https://www.cdc.gov/physical-activity-basics/measuring/index.html', used: 'Talk test; 0 to 10 effort scale (moderate 5 to 6, vigorous 7 to 8)' },
  { id: 'yrbs-pa', org: 'CDC, Youth Risk Behavior Survey', title: 'Data Summary & Trends Report: Dietary, Physical Activity, and Sleep Behaviors, 2013 to 2023', url: 'https://www.cdc.gov/yrbs/dstr/dietary-physical-sleep-behaviors.html', used: 'Percent of high school students active 60 minutes on all 7 days (about 27% in 2013, about 25% in 2023; 17% of females and 32% of males in 2023)' },
  { id: 'mmwr-fv', org: 'CDC, MMWR (Jan 2021)', title: 'Percentage of Adolescents Meeting Federal Fruit and Vegetable Intake Recommendations, YRBSS, 2017', url: 'https://www.cdc.gov/mmwr/volumes/70/wr/mm7003a1.htm', used: '7.1% of students met the fruit recommendation; 2.0% met the vegetable recommendation' },
  { id: 'ers-fs', org: 'USDA Economic Research Service', title: 'Household Food Security in the United States in 2023', url: 'https://www.ers.usda.gov/topics/food-nutrition-assistance/food-security-in-the-u-s/', used: 'Share of households that were food insecure: 10.2% (2021), 12.8% (2022), 13.5% (2023)' },
  { id: 'jama-upf', org: 'JAMA (peer reviewed)', title: 'Wang L, et al. Trends in Consumption of Ultraprocessed Foods Among US Youths Aged 2-19 Years, 1999-2018', url: 'https://doi.org/10.1001/jama.2021.10238', used: 'Ultra-processed foods: about 61% of youth calories in 1999, about 67% in 2018; minimally processed foods fell from 28.8% to 23.5%' },
  { id: 'nih-upf', org: 'NIH Research Matters', title: 'Highly processed foods form bulk of U.S. youths\' diets', url: 'https://www.nih.gov/news-events/nih-research-matters/highly-processed-foods-form-bulk-us-youths-diets', used: 'Plain-language summary of the JAMA study' },
  { id: 'ers-meat', org: 'USDA Economic Research Service', title: 'Concentration in U.S. Meatpacking Industry and How It Affects Competition and Cattle Prices (2024)', url: 'https://www.ers.usda.gov/amber-waves/2024/january/concentration-in-u-s-meatpacking-industry-and-how-it-affects-competition-and-cattle-prices', used: 'Four largest packers handled about 85% of steer and heifer purchases (2015 data)' },
  { id: 'coates', org: 'Pediatrics (peer reviewed)', title: 'Coates AE, et al. Social Media Influencer Marketing and Children\'s Food Intake: A Randomized Trial (2019)', url: 'https://doi.org/10.1542/peds.2018-2554', used: 'Children shown influencer posts with unhealthy snacks ate about 26% more total snack calories in a lab session' },
  { id: 'fda-label', org: 'U.S. Food and Drug Administration', title: 'How to Understand and Use the Nutrition Facts Label', url: 'https://www.fda.gov/food/nutrition-facts-label/how-understand-and-use-nutrition-facts-label', used: 'Serving size, servings per container, % Daily Value (5% or less is low, 20% or more is high), dual-column labels' },
  { id: 'fda-dv', org: 'U.S. Food and Drug Administration', title: 'Daily Value on the Nutrition and Supplement Facts Labels', url: 'https://www.fda.gov/food/nutrition-facts-label/daily-value-nutrition-and-supplement-facts-labels', used: 'Daily Values: sodium 2,300 mg; added sugars 50 g; saturated fat 20 g; fiber 28 g (2,000-calorie reference)' },
  { id: 'dga', org: 'USDA and HHS', title: 'Dietary Guidelines for Americans, 2020 to 2025', url: 'https://www.dietaryguidelines.gov/', used: 'Balanced eating patterns; limit added sugars, sodium and saturated fat' },
  { id: 'myplate', org: 'USDA', title: 'MyPlate', url: 'https://www.myplate.gov/', used: 'Five food groups; make half your plate fruits and vegetables' },
  { id: 'ftc', org: 'Federal Trade Commission', title: 'Disclosures 101 for Social Media Influencers', url: 'https://www.ftc.gov/business-guidance/resources/disclosures-101-social-media-influencers', used: 'Sponsorships must be clearly and conspicuously disclosed' },
  { id: 'fda-supp', org: 'U.S. Food and Drug Administration', title: 'Dietary Supplements', url: 'https://www.fda.gov/food/dietary-supplements', used: 'Supplements are not approved by the FDA for safety or effectiveness before they are sold' },
  { id: 'nrcs', org: 'USDA Natural Resources Conservation Service', title: 'Soil Health', url: 'https://www.nrcs.usda.gov/conservation-basics/natural-resource-concerns/soil/soil-health', used: 'Cover crops, reduced tillage, rotational grazing and crop diversity as soil-health practices' }
];
export const sourceById = Object.fromEntries(SOURCES.map((s) => [s.id, s]));
