'use strict';
// Builds: dist/web (portable frontend, talks to /api), dist/demo (in-browser demo), dist/apps-script (Code.gs + Index.html + appsscript.json)
const fs = require('fs');
const path = require('path');
const split = require('./split');
const ROOT = path.join(__dirname, '..');
const read = p => fs.readFileSync(path.join(ROOT, p), 'utf8');
const write = (p, s) => { const f = path.join(ROOT, p); fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, s); };
const jsonSafe = o => JSON.stringify(o).replace(/</g, '\\u003c').replace(new RegExp('\\u2028', 'g'), '\\u2028').replace(new RegExp('\\u2029', 'g'), '\\u2029');

const css = ['tokens', 'app', 'visuals'].map(n => read('web/css/' + n + '.css')).join('\n');
const FRONT = ['00-util', '10-transport', '30-map', '40-fields', '50-explorers-a', '51-explorers-b', '60-app', '65-final', '70-teacher'].map(n => read('web/js/' + n + '.js')).join('\n');
const grading = read('server/grading.js');
const core = read('server/core.js');
const memory = read('server/stores/memory.js');
const sha = read('server/sha256.js');
const tpl = read('web/index.template.html');

function page(config, pub, extra) {
  return tpl.replace('/*CSS*/', () => css).replace('/*CONFIG*/', () => jsonSafe(config)).replace('/*CONTENT*/', () => jsonSafe(pub))
    .replace('/*EXTRA*/', () => extra || '').replace('/*JS*/', () => FRONT.replace(/<\/script/gi, '<\\/script') + '\nCHM.boot();');
}

function main() {
  const { pub, priv } = split.load();
  if (split.HAVE_SRC) {     // refresh the committed public bundle and the private key file from the private sources
    write('content/generated/public.json', JSON.stringify(pub, null, 1)); write('private/keys.json', JSON.stringify(priv));
  }
  // 1) portable frontend (HTTP transport to /api; used with tools/dev-server.js or any host that implements POST /api)
  write('dist/web/index.html', page({ transport: 'http' }, pub, '<script>\n' + grading + '\n</script>'));

  // 2) Apps Script project
  const adapter = read('server/apps-script/adapter.js');
  if (!priv) console.log('NOTE: private/keys.json not found, so dist/apps-script/Code.gs was NOT built (it contains the answer key).');
  const code = !priv ? null : [
    '// Community Health Mission: Google Apps Script backend (GENERATED by tools/build.js; edit the sources, not this file).',
    '// Contains the PRIVATE answer key. Never publish this file or put it in a public repository.',
    'var CHM_PUB = ' + JSON.stringify(pub) + ';', 'var CHM_PRIV = ' + JSON.stringify(priv) + ';', grading, core, adapter].join('\n');
  if (code) write('dist/apps-script/Code.gs', code);
  write('dist/apps-script/Index.html', page({ transport: 'appsScript' }, pub, '<script>\n' + grading + '\n</script>'));
  write('dist/apps-script/appsscript.json', JSON.stringify({ timeZone: 'America/New_York', exceptionLogging: 'STACKDRIVER', runtimeVersion: 'V8',
    oauthScopes: ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/script.container.ui', 'https://www.googleapis.com/auth/userinfo.email'],
    webapp: { executeAs: 'USER_DEPLOYING', access: 'ANYONE' } }, null, 2));

  // 2b) Static "play" build (teacher-approved: answer key is embedded in the page). Engine runs in the browser; results post to a Sheet receiver.
  if (priv) {
    const crypto = require('crypto');
    const pass = process.env.CHM_TEACHER_PASSCODE || 'WALK-TEACHER', salt = 'chm-static';
    const teacher = JSON.stringify({ salt: salt, hash: crypto.createHash('sha256').update(salt + pass).digest('hex'), emails: [] });
    const playExtra = ['<script src="config.js"></script>', '<script>', grading, sha, core, read('server/stores/memory.js'), read('server/stores/browser.js').replace(/require\('\.\/memory'\)/g, 'null'),
      'var CHM_PRIVATE = ' + jsonSafe(priv) + ';',
      '(function(){var env={sha256:CHM_sha256,randomId:function(n){var a=new Uint8Array(n);crypto.getRandomValues(a);return Array.prototype.map.call(a,function(b){return "abcdefghijklmnopqrstuvwxyz0123456789"[b%36]}).join("")}};',
      'var storage=null;try{storage=window.localStorage;storage.setItem("chm.t","1");storage.removeItem("chm.t")}catch(e){storage=null}',
      'var teacher=' + teacher + ';',
      'var store=new CHM_BrowserStore({pub:CHM_CONTENT,storage:storage,key:"chm.store."+CHM_CONTENT.version,teacher:teacher});store.teacher=teacher;',
      'var engine=CHM_core.createEngine({pub:CHM_CONTENT,priv:CHM_PRIVATE,store:store,env:env});',
      'function url(){return (window.CHM_RESULTS_URL||"").trim()}',
      'function post(body){var c=typeof AbortController!=="undefined"?new AbortController():null,t=c&&setTimeout(function(){c.abort()},20000);',
      ' return fetch(url(),{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(body),signal:c?c.signal:undefined}).then(function(r){if(!r.ok)throw new Error("HTTP "+r.status);return r.json()}).then(function(j){if(t)clearTimeout(t);return j},function(e){if(t)clearTimeout(t);throw e})}',
      'function deliver(id){var p=store.outbox[id];if(!p||!url())return Promise.resolve(false);',
      ' return post({action:"submit",payload:p}).then(function(j){if(j&&j.ok){store.markAcked(id);return true}return j&&j.reason==="bad-code"?"bad-code":false},function(){return false})}',
      'window.CHM_STATIC_HANDLE=function(a,p){',
      ' if(a==="join"&&url()){return post({action:"start",classCode:p.classCode}).then(function(j){if(j&&j.ok===false&&j.reason==="bad-code")return{ok:false,code:"BAD_CLASS",message:"That class code was not found. Check it with your teacher."};return engine.handle(a,p)},function(){return engine.handle(a,p)})}',
      ' var r=engine.handle(a,p);',
      ' if((a==="finalize"||a==="retryGradebook")&&r&&r.ok&&r.final&&r.final.gradebook==="pending"){',
      '  return deliver(p.sessionId).then(function(ok){if(ok===true)return engine.handle("retryGradebook",Object.assign({},p,{requestId:"rg-"+Date.now()}));',
      '   r.final.error=ok==="bad-code"?"That class code is not set up in the teacher sheet. Tell your teacher.":!url()?"Delivery is not turned on yet (no results link set).":"Could not reach the teacher sheet. Check Wi-Fi and press Retry.";return r})}',
      ' return r};})();', '</script>'].join('\n');
    write('play/index.html', page({ transport: 'static' }, pub, playExtra).replace('CHM.boot();', 'CHM.staticHandle = window.CHM_STATIC_HANDLE;\nCHM.boot();'));
    if (!fs.existsSync(path.join(ROOT, 'play/config.js'))) write('play/config.js', '// Paste your Google Apps Script web app link (ends in /exec) between the quotes. Leave empty to run without delivering results.\nwindow.CHM_RESULTS_URL = "";\n');
    const units = []; pub.modules.forEach(m => m.units.forEach(u => units.push({ id: u.id, module: m.id, points: u.points })));
    write('play/SheetReceiver.gs', read('receiver/SheetReceiver.gs').replace('/*UNITS*/[]', JSON.stringify(units)));
  }

  // 3) Demo (separate fictional demo content; the graded answer key is NOT included)
  const d = split.buildDemo();
  const demoExtra = ['<script>', grading, sha, core, memory,
    'var CHM_DEMO = ' + jsonSafe({ priv: d.priv }) + ';',
    '(function(){var env={sha256:CHM_sha256,randomId:function(n){var a=new Uint8Array(n);crypto.getRandomValues(a);return Array.prototype.map.call(a,function(b){return "abcdefghijklmnopqrstuvwxyz0123456789"[b%36]}).join("")}};',
    'var salt="demo";var store=new CHM_MemoryStore({teacher:{salt:salt,hash:env.sha256(salt+"demo-teacher"),emails:[]}});',
    'store.saveClass({code:"DEMO",name:"Demo class",section:"DEMO",version:CHM_CONTENT.version,status:"open",opensAt:"",closesAt:"",requireRoster:false,revealMode:"final",pacingFactor:1});',
    'var engine=CHM_core.createEngine({pub:CHM_CONTENT,priv:CHM_DEMO.priv,store:store,env:env});',
    'window.CHM_DEMO_HANDLE=function(a,p){return engine.handle(a,p)};})();', '</script>'].join('\n');
  write('dist/demo/index.html', page({ transport: 'demo' }, d.pub, demoExtra).replace('window.CHM_DEMO_HANDLE', 'window.CHM_DEMO_HANDLE') + '');
  // demoHandle shim must exist before boot: append binding inside the page via a tiny script injected before main JS
  let demo = fs.readFileSync(path.join(ROOT, 'dist/demo/index.html'), 'utf8');
  demo = demo.replace('<script>\nwindow.CHM', '<script>\nwindow.CHM');
  fs.writeFileSync(path.join(ROOT, 'dist/demo/index.html'), demo.replace('CHM.boot();', 'CHM.demoHandle = window.CHM_DEMO_HANDLE;\nCHM.boot();'));
  console.log('built: dist/web, dist/demo, dist/apps-script (Code.gs ' + (code ? Math.round(code.length / 1024) + ' KB' : 'skipped') + ')');
}
main();
