'use strict';
// Builds: dist/web (portable frontend, talks to /api), dist/demo (in-browser demo), dist/apps-script (Code.gs + Index.html + appsscript.json)
const fs = require('fs');
const path = require('path');
const split = require('./split');
const ROOT = path.join(__dirname, '..');
const read = p => fs.readFileSync(path.join(ROOT, p), 'utf8');
const write = (p, s) => { const f = path.join(ROOT, p); fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, s); };
const jsonSafe = o => JSON.stringify(o).replace(/</g, '\\u003c').replace(new RegExp('\\u2028', 'g'), '\\u2028').replace(new RegExp('\\u2029', 'g'), '\\u2029');

const css = ['tokens', 'app', 'visuals'].map(n => read('web/css/' + n + '.css')).join('\n');
const FRONT = ['00-util', '10-transport', '30-map', '40-fields', '50-explorers-a', '51-explorers-b', '60-app', '65-final', '70-teacher'].map(n => read('web/js/' + n + '.js')).join('\n');
const grading = read('server/grading.js');
const core = read('server/core.js');
const memory = read('server/stores/memory.js');
const sha = read('server/sha256.js');
const tpl = read('web/index.template.html');

function page(config, pub, extra) {
  return tpl.replace('/*CSS*/', () => css).replace('/*CONFIG*/', () => jsonSafe(config)).replace('/*CONTENT*/', () => jsonSafe(pub))
    .replace('/*EXTRA*/', () => extra || '').replace('/*JS*/', () => FRONT.replace(/<\/script/gi, '<\\/script') + '\nCHM.boot();');
}

function main() {
  const { pub, priv } = split.load();
  if (split.HAVE_SRC) {     // refresh the committed public bundle and the private key file from the private sources
    write('content/generated/public.json', JSON.stringify(pub, null, 1)); write('private/keys.json', JSON.stringify(priv));
  }
  // 1) portable frontend (HTTP transport to /api; used with tools/dev-server.js or any host that implements POST /api)
  write('dist/web/index.html', page({ transport: 'http' }, pub, '<script>\n' + grading + '\n</script>'));

  // 2) Apps Script project
  const adapter = read('server/apps-script/adapter.js');
  if (!priv) console.log('NOTE: private/keys.json not found, so dist/apps-script/Code.gs was NOT built (it contains the answer key).');
  const code = !priv ? null : [
    '// Community Health Mission: Google Apps Script backend (GENERATED by tools/build.js; edit the sources, not this file).',
    '// Contains the PRIVATE answer key. Never publish this file or put it in a public repository.',
    'var CHM_PUB = ' + JSON.stringify(pub) + ';', 'var CHM_PRIV = ' + JSON.stringify(priv) + ';', grading, core, adapter].join('\n');
  if (code) write('dist/apps-script/Code.gs', code);
  write('dist/apps-script/Index.html', page({ transport: 'appsScript' }, pub, '<script>\n' + grading + '\n</script>'));
  write('dist/apps-script/appsscript.json', JSON.stringify({ timeZone: 'America/New_York', exceptionLogging: 'STACKDRIVER', runtimeVersion: 'V8',
    oauthScopes: ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/script.container.ui', 'https://www.googleapis.com/auth/userinfo.email'],
    webapp: { executeAs: 'USER_DEPLOYING', access: 'ANYONE' } }, null, 2));

  // 3) Demo (separate fictional demo content; the graded answer key is NOT included)
  const d = split.buildDemo();
  const demoExtra = ['<script>', grading, sha, core, memory,
    'var CHM_DEMO = ' + jsonSafe({ priv: d.priv }) + ';',
    '(function(){var env={sha256:CHM_sha256,randomId:function(n){var a=new Uint8Array(n);crypto.getRandomValues(a);return Array.prototype.map.call(a,function(b){return "abcdefghijklmnopqrstuvwxyz0123456789"[b%36]}).join("")}};',
    'var salt="demo";var store=new CHM_MemoryStore({teacher:{salt:salt,hash:env.sha256(salt+"demo-teacher"),emails:[]}});',
    'store.saveClass({code:"DEMO",name:"Demo class",section:"DEMO",version:CHM_CONTENT.version,status:"open",opensAt:"",closesAt:"",requireRoster:false,revealMode:"final",pacingFactor:1});',
    'var engine=CHM_core.createEngine({pub:CHM_CONTENT,priv:CHM_DEMO.priv,store:store,env:env});',
    'window.CHM_DEMO_HANDLE=function(a,p){return engine.handle(a,p)};})();', '</script>'].join('\n');
  write('dist/demo/index.html', page({ transport: 'demo' }, d.pub, demoExtra).replace('window.CHM_DEMO_HANDLE', 'window.CHM_DEMO_HANDLE') + '');
  // demoHandle shim must exist before boot: append binding inside the page via a tiny script injected before main JS
  let demo = fs.readFileSync(path.join(ROOT, 'dist/demo/index.html'), 'utf8');
  demo = demo.replace('<script>\nwindow.CHM', '<script>\nwindow.CHM');
  fs.writeFileSync(path.join(ROOT, 'dist/demo/index.html'), demo.replace('CHM.boot();', 'CHM.demoHandle = window.CHM_DEMO_HANDLE;\nCHM.boot();'));
  console.log('built: dist/web, dist/demo, dist/apps-script (Code.gs ' + (code ? Math.round(code.length / 1024) + ' KB' : 'skipped') + ')');
}
main();
