/* Content for "Stress & the Brain Lab": brain/body regions, stressors, coping tools, lessons, questions.
   Fictional, simplified model for a high school health class — not medical advice. */
const SB = {};

/* ---------- Regions (hover = real-world one-liner, click = full card) ---------- */
SB.REGIONS = {
  prefrontal: { name: 'Prefrontal cortex', nick: 'The planner', group: 'Cortex', color: '#6aa7ff',
    real: 'Planning your week, thinking before you text back, choosing not to snap at a friend.',
    does: 'The front of the brain handles planning, decisions, focus and self-control. It is the "thinking brain" that weighs options before you act.',
    life: ['Planning how to study for a test', 'Pausing before you say something you will regret', 'Saying no to your phone so you can finish homework'],
    stress: 'Adrenaline and cortisol turn this region\'s "volume" down so the faster survival circuits can take over. That is why your mind goes blank during a test, or why you blurt something out when upset. When you calm down, it comes back online.',
    tryit: 'Add a surprise pop quiz in the Lab and watch this region dim.' },
  motor: { name: 'Motor cortex', nick: 'The mover', group: 'Cortex', color: '#4be3a0',
    real: 'Sends the "move now!" orders to your muscles: throwing, typing, sprinting away.',
    does: 'A strip across the top of the brain that plans and sends movement commands down the spinal cord to the muscles.',
    life: ['Kicking a ball', 'Typing a text', 'Running from a barking dog'],
    stress: 'During fight/flight it is primed for fast action. Leftover tension shows up as a clenched jaw, tight shoulders and shaky hands.',
    tryit: 'Trigger "Dog charges at you" and watch the arms tense up.' },
  parietal: { name: 'Parietal lobe', nick: 'The body sensor', group: 'Cortex', color: '#ffd166',
    real: 'Lets you feel touch and body position, so you notice a racing heart or a tight stomach.',
    does: 'Processes touch, pressure, pain and where your body is in space. It also helps you notice signals from inside your body.',
    life: ['Catching a ball without looking at your hand', 'Noticing butterflies in your stomach', 'Feeling your shoulders tighten at your desk'],
    stress: 'Stress makes you more aware of body signals (pounding heart, sweaty hands). Noticing the signal is step 1 of coping: Notice, Regulate, Choose, Recover.',
    tryit: 'Turn on a stressor and read the Body effects list in the monitor.' },
  temporal: { name: 'Temporal lobe', nick: 'The listener', group: 'Cortex', color: '#ff9f5a',
    real: 'Understanding what your teacher says, recognizing a friend\'s voice, hearing a car horn.',
    does: 'Handles hearing, language and recognizing faces and voices. The amygdala and hippocampus are tucked deep inside it.',
    life: ['Following a conversation', 'Recognizing a song', 'Jumping at a sudden loud noise'],
    stress: 'A harsh tone or a loud bang is passed to the amygdala within a blink, so sounds and words can feel louder and more threatening when you are stressed.',
    tryit: 'Trigger an embarrassing moment and watch how fast the alarm lights up.' },
  occipital: { name: 'Occipital lobe', nick: 'The vision center', group: 'Cortex', color: '#c28bff',
    real: 'Turns light into sight: reading, spotting a ball, noticing a face in the hallway.',
    does: 'The back of the brain processes what your eyes see: shapes, color, motion and depth.',
    life: ['Reading the board', 'Tracking a fast ball', 'Noticing a friend wave'],
    stress: 'Under threat, attention narrows ("tunnel vision"). You see the threat clearly but can miss things at the edges, like the answer on the board or a friend saying hi.',
    tryit: 'Max out the stress and watch the Attention meter narrow.' },
  cerebellum: { name: 'Cerebellum', nick: 'The balance & smoothness', group: 'Cortex', color: '#ff7aa8',
    real: 'Keeps you balanced and your movements smooth: riding a bike, a basketball shot, handwriting.',
    does: 'Tucked at the back and bottom, it fine-tunes movement, balance and timing.',
    life: ['Riding a bike', 'Hitting a serve', 'Writing neatly'],
    stress: 'Under stress, fine movements get jerky or shaky, like hands trembling before a presentation or fumbling a lock when you are rushed.',
    tryit: 'Trigger a presentation and watch the muscle tension rise.' },
  brainstem: { name: 'Brainstem', nick: 'The autopilot', group: 'Deep brain', color: '#9aa8c8',
    real: 'Runs your heartbeat, breathing and sleep without you thinking about it.',
    does: 'Connects the brain to the spinal cord. It controls automatic life support like heart rate, breathing and wake/sleep, and it is where the vagus nerve (the brake) begins.',
    life: ['Breathing while you sleep', 'Heart speeding up when you jump', 'Slowing your heart with a long exhale'],
    stress: 'Alarm signals travel through here to speed up heart and breathing. The slow-down orders (the vagus nerve) also start here, which is why long slow exhales help you calm down.',
    tryit: 'Turn on "Slow breathing" and watch the teal brake signals leave the brainstem.' },
  amygdala: { name: 'Amygdala', nick: 'The smoke detector', group: 'Deep brain', color: '#ffb347',
    real: 'Spots possible danger (a snarling dog, a sudden shout, a pop quiz) before you have even thought about it.',
    does: 'Two almond-sized clusters that scan everything you sense and ask, "Could this be danger?" They fire first and fast, then recruit the rest of the stress system.',
    life: ['Jumping at a stick that looks like a snake', 'Heart pounding when a teacher calls your name', 'A scary movie moment'],
    stress: 'Sets off the alarm chain. With long-lasting stress the smoke detector can become more sensitive, so small things start to feel big. With recovery it can calm back down.',
    tryit: 'Add any stressor and watch it light up and grow. Then add chronic stress and skip ahead a few weeks.' },
  hippocampus: { name: 'Hippocampus', nick: 'The memory filer', group: 'Deep brain', color: '#5ad1ff',
    real: 'Files new memories and remembers context, like vocabulary words or where you left your bag.',
    does: 'A seahorse-shaped structure that turns experiences into memories and tags them with where and when. It is packed with stress-hormone receptors.',
    life: ['Studying vocabulary', 'Remembering where you parked your bike', 'Recalling what happened yesterday'],
    stress: 'A short burst can sharpen the memory of an event, but months of high cortisol can make learning and remembering harder and shrink this region. The brain is adaptable: sleep, exercise and support help it recover.',
    tryit: 'Turn on chronic stressors, skip ahead 4 weeks, and watch it shrink. Add coping and watch it recover.' },
  hypothalamus: { name: 'Hypothalamus', nick: 'The control center', group: 'Deep brain', color: '#ff8a3d',
    real: 'Keeps your body in balance: temperature, hunger, thirst, sleep. It also starts the stress hormone chain.',
    does: 'A tiny region that links the brain to the body\'s hormone system. It is step 2 of the alarm chain.',
    life: ['Sweating when you are hot', 'Feeling hungry', 'Getting sleepy at night'],
    stress: 'When the amygdala sounds the alarm, the hypothalamus switches on two systems at once: the fast nerve route (sympathetic) and the slower hormone route (HPA axis: hypothalamus, pituitary, adrenal glands).',
    tryit: 'Press "Run the alarm" in Lesson 2 and follow the signal.' },
  pituitary: { name: 'Pituitary gland', nick: 'The master gland', group: 'Deep brain', color: '#f5d76e',
    real: 'A pea-sized gland that sends hormone messages through the blood to tell other glands what to do.',
    does: 'Hangs just below the hypothalamus and releases hormones into the bloodstream.',
    life: ['Growth during the teen years', 'Controlling your body\'s balance of water', 'Telling the adrenals to work'],
    stress: 'It releases a hormone (ACTH) into the blood that tells the adrenal glands to make cortisol. That is the slow stress route, taking minutes instead of seconds.',
    tryit: 'Watch the gold hormone message travel from here down to the adrenals.' },
  thalamus: { name: 'Thalamus', nick: 'The relay station', group: 'Deep brain', color: '#b58bff',
    real: 'Sorts everything you sense and sends it to the right place: your name being called, a flash of light.',
    does: 'A central relay hub: most sensory signals pass through here on their way to the cortex.',
    life: ['Hearing your name in a noisy cafeteria', 'Feeling a tap on the shoulder', 'Seeing a flash'],
    stress: 'It sends a fast, rough copy of what you sensed straight to the amygdala (the "fast road") while a detailed copy goes to the cortex (the "slow road"). That is why you can jump before you realize it was only a stick.',
    tryit: 'Press "Run the alarm" and watch the fast road beat the slow road.' },
  adrenals: { name: 'Adrenal glands', nick: 'The hormone release', group: 'Body', color: '#ffb347',
    real: 'Sit on top of the kidneys and release adrenaline in seconds and cortisol in minutes.',
    does: 'Two small glands that respond to the brain\'s signals by releasing stress hormones into the blood.',
    life: ['The jolt of energy when you are startled', 'Staying alert during a big game', 'The slow wave of "wired" feeling after'],
    stress: 'Adrenaline raises heart rate and breathing in seconds. Cortisol releases energy, and in the short run helps you cope. Staying high for weeks without recovery is what wears the system down.',
    tryit: 'Add a stressor and watch adrenaline particles spray out.' },
  heart: { name: 'Heart', nick: 'The pump', group: 'Body', color: '#ff5a6e',
    real: 'Beats faster to send oxygen to your muscles, the pounding heart before a speech.',
    does: 'Pumps blood around the body. The sympathetic system speeds it up; the parasympathetic (vagus nerve) slows it down.',
    life: ['Heart pounding before you present', 'Heart slowing during a long exhale', 'Feeling your pulse after a sprint'],
    stress: 'Heart rate and blood pressure rise during stress. If that stays high for long periods, it can strain the cardiovascular system over the years.',
    tryit: 'Watch the beat speed up when you add stress and slow when you add Slow breathing.' },
  lungs: { name: 'Lungs', nick: 'The air exchange', group: 'Body', color: '#7fd0ff',
    real: 'Breathe faster and shallower when you are stressed; a slow exhale tells the brake to engage.',
    does: 'Bring oxygen in and carry carbon dioxide out. Breathing is the one automatic system you can also control on purpose.',
    life: ['Quick shallow breaths before a test', 'A deep sigh of relief', 'Box breathing or 4-6 breathing'],
    stress: 'Quick, shallow breathing is part of "body ready". Long, slow exhales stimulate the vagus nerve and help shift toward recovery.',
    tryit: 'Turn on Slow breathing and match the pacing circle.' },
  stomach: { name: 'Stomach & gut', nick: 'The digester', group: 'Body', color: '#ff9a8a',
    real: 'Digestion slows in an emergency: butterflies, a knot in the stomach, or no appetite before a big test.',
    does: 'Digests food. It also has its own big network of nerves that talks to the brain through the vagus nerve.',
    life: ['Butterflies before a performance', 'Not feeling hungry when nervous', 'A stomachache during a stressful week'],
    stress: 'Sympathetic activation slows digestion because energy is sent to the muscles. Recovery (the parasympathetic "rest and digest" mode) gets digestion going again.',
    tryit: 'Watch the Digestion meter drop when stress goes up.' },
  muscles: { name: 'Muscles', nick: 'The movers', group: 'Body', color: '#ff7a59',
    real: 'Tense up and get ready to move: shaky hands, a tight neck, sore shoulders after a hard week.',
    does: 'Contract to move your body. Stress hormones increase blood flow and readiness in large muscles.',
    life: ['Clenching your jaw', 'Shoulders creeping up to your ears', 'Legs jittering before an exam'],
    stress: 'Short-term: muscles are primed for action. Long-term: constant tension can lead to headaches, neck and shoulder pain, and feeling worn out.',
    tryit: 'Trigger the dog stressor and watch the arms tense and tremble.' },
  spine: { name: 'Spinal cord (sympathetic highway)', nick: 'The gas pedal wiring', group: 'Body', color: '#ffa94d',
    real: 'The fast nerve route that carries the "go!" signal from the brain to organs all over the body.',
    does: 'Carries messages between the brain and the body. Sympathetic nerves leave the spinal cord to reach the heart, lungs, gut, adrenals and muscles.',
    life: ['Instant reaction to a hot stove', 'Heart racing within a second of a scare'],
    stress: 'The sympathetic "gas pedal" speeds up body systems within seconds of the brain detecting a threat.',
    tryit: 'Watch the orange pulses travel down the spinal cord when stress is on.' },
  vagus: { name: 'Vagus nerve (brake highway)', nick: 'The brake pedal wiring', group: 'Body', color: '#2de2c8',
    real: 'The main parasympathetic route that tells the heart, lungs and gut to slow down and recover.',
    does: 'A long nerve from the brainstem to the heart, lungs and gut. It carries "rest and recover" signals.',
    life: ['Heart slowing as you exhale', 'Appetite returning after a scare', 'Feeling calm after a good laugh or a walk'],
    stress: 'Recovery skills such as slow breathing, sleep, movement and support help this brake engage.',
    tryit: 'Turn on Slow breathing and watch the teal pulses speed up.' }
};

SB.CORTEX_IDS = ['prefrontal', 'motor', 'parietal', 'temporal', 'occipital'];

/* ---------- Stressors: acute ones are events that end; chronic ones persist until removed ---------- */
SB.STRESSORS = [
  { id: 'quiz', name: 'Surprise pop quiz', cat: 'Academic', acute: true, dur: 16, w: 0.60, icon: '📝',
    log: 'A pop quiz! The amygdala reads it as a demand, adrenaline spikes, and the thinking brain gets quieter.',
    say: 'Wait… did I study this?! My mind is going blank.' },
  { id: 'speech', name: 'Presentation in front of class', cat: 'Academic / Social', acute: true, dur: 18, w: 0.70, icon: '🎤',
    log: 'Presentation time: heart races, hands shake. This is a normal, short-term stress response.',
    say: 'Everyone is looking at me. My hands are shaking.' },
  { id: 'dog', name: 'Dog charges at you', cat: 'Physical danger', acute: true, dur: 12, w: 1.40, icon: '🐕',
    log: 'A real threat! The alarm chain fires at full speed: heart pounding, muscles ready to run.',
    say: 'RUN! Heart pounding, legs ready.' },
  { id: 'embarrass', name: 'Embarrassing moment', cat: 'Social', acute: true, dur: 16, w: 0.50, icon: '😳',
    log: 'Social stress: your brain treats embarrassment as a threat to belonging, so the alarm fires.',
    say: 'Everyone saw that. I want to disappear.' },
  { id: 'game', name: 'Big game or performance', cat: 'Physical / Social', acute: true, dur: 20, w: 0.40, icon: '🏀',
    log: 'A challenge. Moderate stress can sharpen focus and boost performance: the "sweet spot".',
    say: 'Okay. Game time. I am fired up and ready.' },
  { id: 'sleep', name: 'Sleeping only 4 hours a night', cat: 'Physical', acute: false, w: 0.38, icon: '😴',
    log: 'Chronic: short sleep is a physical stressor and also lowers your ability to recover.',
    say: 'I am so tired, and everything feels harder.' },
  { id: 'deadlines', name: 'Nonstop deadlines and overload', cat: 'Academic', acute: false, w: 0.48, icon: '📚',
    log: 'Chronic: the demand never lets up, so the brain keeps the system on alert.',
    say: 'There is always something due. I can\'t keep up.' },
  { id: 'conflict', name: 'Weeks of conflict (friends or home)', cat: 'Social', acute: false, w: 0.56, icon: '💬',
    log: 'Chronic: ongoing conflict keeps the alarm sensitive. Talking to a trusted adult matters here.',
    say: 'I never know when the next argument will start.' },
  { id: 'worry', name: 'Constant "what if?" worry', cat: 'Internal', acute: false, w: 0.36, icon: '💭',
    log: 'Chronic: the brain can trigger the alarm from thoughts and memories, not just events.',
    say: 'What if I fail? What if they all hate me?' },
  { id: 'scroll', name: 'Late-night scrolling and comparison', cat: 'Internal / Social', acute: false, w: 0.30, icon: '📱',
    log: 'Chronic: late-night scrolling cuts recovery time and feeds comparison and worry.',
    say: 'Just one more scroll… everyone else has it figured out.' }
];

/* ---------- Coping: "recovery" tools raise recovery capacity; "demand" tools shrink the demand ---------- */
SB.COPING = [
  { id: 'breath', name: 'Slow breathing (in 4, out 6)', type: 'recovery', rec: 0.45, dur: 40, icon: '🌬️',
    log: 'Long slow exhales stimulate the vagus nerve, the brake pedal engages, and the heart slows.' },
  { id: 'walk', name: 'Walk or move your body', type: 'recovery', rec: 0.22, icon: '🚶',
    log: 'Movement burns off stress hormones and helps your system return to balance.' },
  { id: 'sleepgood', name: 'Protect 8-9 hours of sleep', type: 'recovery', rec: 0.28, icon: '🛌',
    log: 'Sleep is when the brain recovers. It also cancels the short-sleep stressor.' },
  { id: 'friend', name: 'Talk to someone you trust', type: 'recovery', rec: 0.20, dem: 0.10, icon: '🤝',
    log: 'Support helps the threat feel smaller and the body settle down.' },
  { id: 'plan', name: 'Break it into small steps', type: 'demand', dem: 0.25, icon: '🪜',
    log: 'A clear plan shrinks the demand your brain has to deal with.' },
  { id: 'ask', name: 'Ask for help or an extension', type: 'demand', dem: 0.20, icon: '🙋',
    log: 'Reducing the load is a legitimate coping strategy, not weakness.' },
  { id: 'unplug', name: 'Set a limit (say no, phone away)', type: 'demand', dem: 0.15, icon: '🔕',
    log: 'Cutting extra demands leaves more room to recover.' },
  { id: 'reframe', name: 'Reframe: "I can handle this step"', type: 'demand', dem: 0.15, icon: '🔁',
    log: 'A more balanced thought lowers how big the brain judges the threat to be.' }
];

/* ---------- Lessons (adapted from the "Stress and the Brain" slides) ---------- */
SB.LESSONS = [
  { id: 'L1', title: 'What is a stressor?', sub: 'A stressor is anything your brain reads as a demand.',
    view: 'brain', xray: false, focus: 'prefrontal',
    html: `<p class="big">A stressor is not always "bad." It is anything that asks your brain and body to adjust.</p>
      <div class="flow"><span class="fl a">STRESSOR</span><i>›</i><span class="fl b">BRAIN INTERPRETS</span><i>›</i><span class="fl c">BODY RESPONDS</span></div>
      <div class="cats"><div><b>Physical</b> injury, illness, lack of sleep</div><div><b>Academic</b> tests, deadlines, performances</div>
      <div><b>Social</b> conflict, embarrassment, pressure</div><div><b>Internal</b> worry, memories, expectations</div></div>
      <p>Today's big idea: <b>stress is a body-brain signal, not a character flaw.</b></p>`,
    tries: [{ t: '📝 Try a pop quiz', a: 'stress:quiz' }, { t: '🏀 Try a big game (a "good" stressor)', a: 'stress:game' }, { t: 'Clear stress', a: 'clear' }],
    qs: ['q_stressor', 'q_cats'] },
  { id: 'L2', title: 'Fight / flight response', sub: 'The fast survival system.',
    view: 'brain', xray: true, focus: 'amygdala',
    html: `<p class="big">When the brain detects possible danger, it shifts resources toward action.</p>
      <ol class="chain"><li><b>Amygdala</b> "Could this be danger?"</li><li><b>Hypothalamus</b> activates stress pathways</li>
      <li><b>Adrenal glands</b> release adrenaline + cortisol</li><li><b>Body ready</b> heart, breath, muscles</li></ol>
      <p>Sensory input takes two roads: a <b>fast road</b> (thalamus straight to amygdala) and a <b>slow road</b> (through the cortex). That is why you can jump before you know it was only a stick.</p>
      <p>This response is useful for short bursts, since your body is trying to protect you. <b>The problem is not activation. The problem is staying activated with no recovery.</b></p>`,
    tries: [{ t: '⚡ Run the alarm', a: 'alarm' }, { t: '🐕 Dog charges at you', a: 'stress:dog' }, { t: 'Clear stress', a: 'clear' }],
    qs: ['q_chain', 'q_amyg', 'q_horm', 'q_fftf'] },
  { id: 'L3', title: 'Sympathetic activation', sub: 'The "gas pedal" of the nervous system.',
    view: 'body', xray: false, focus: 'heart',
    html: `<p class="big">The sympathetic nervous system presses the gas.</p>
      <ul class="dots"><li><b>Heart</b> beats faster</li><li><b>Breathing</b> gets quicker</li><li><b>Muscles</b> prepare to move</li>
      <li><b>Digestion</b> slows down</li><li><b>Attention</b> locks onto the threat</li></ul>
      <p class="key">Key idea: stress changes the whole body, not just mood.</p>`,
    tries: [{ t: '🎤 Press the gas (presentation)', a: 'stress:speech' }, { t: 'Clear stress', a: 'clear' }],
    qs: ['q_gas', 'q_symp', 'q_mood'] },
  { id: 'L4', title: 'Recovery', sub: 'Your body also has a brake pedal.',
    view: 'body', xray: false, focus: 'vagus',
    html: `<p class="big">After the stressor passes, the nervous system should shift toward recovery.</p>
      <div class="two"><div class="act"><b>Activation</b><br>mobilize energy</div><span>➜</span><div class="rec"><b>Recovery</b><br>restore balance</div></div>
      <p>The parasympathetic system is the <b>brake pedal</b>. It slows the heart, steadies breathing and restarts digestion.</p>
      <p><b>Recovery is a skill:</b> sleep, breathing, movement, support, and time can help the "brake" engage.</p>`,
    tries: [{ t: '🎤 Add stress first', a: 'stress:speech' }, { t: '🌬️ Press the brake (slow breathing)', a: 'cope:breath' }, { t: 'Clear stress', a: 'clear' }],
    qs: ['q_brake', 'q_help'] },
  { id: 'L5', title: 'Acute vs. chronic stress', sub: 'Same system, very different outcome.',
    view: 'brain', xray: true, focus: 'hippocampus',
    html: `<div class="cmp"><div class="ac"><b>ACUTE</b><small>short-term demand</small><ul><li>quick activation</li><li>clear challenge</li><li>recovery follows</li><li>can build confidence</li></ul><em>speech, quiz, a game</em></div>
      <div class="ch"><b>CHRONIC</b><small>activation without enough recovery</small><ul><li>ongoing pressure</li><li>worry continues</li><li>sleep may suffer</li><li>body stays on alert</li></ul><em>weeks of conflict, nonstop overload</em></div></div>
      <p class="key">The question is not "Do I have stress?" It is: <b>"Am I recovering?"</b></p>`,
    tries: [{ t: '🎤 Acute: give a speech', a: 'stress:speech' }, { t: '⏩ Chronic: 4 weeks of overload', a: 'chronic4' }, { t: 'Clear + reset', a: 'reset' }],
    qs: ['q_acch', 'q_amq', 'q_chrfx'] },
  { id: 'L6', title: 'Why coping matters', sub: 'Coping changes the stress cycle.',
    view: 'brain', xray: false, focus: 'prefrontal',
    html: `<p class="big">Coping is not "pretending everything is fine."</p>
      <p>It is a way to help the brain and body return to a workable state.</p>
      <div class="steps4"><div><i>1</i><b>Notice</b>name the signal</div><div><i>2</i><b>Regulate</b>slow the body</div><div><i>3</i><b>Choose</b>take next step</div><div><i>4</i><b>Recover</b>restore energy</div></div>
      <p class="key">Useful coping does one of two things: <b>reduces the demand</b> OR <b>improves recovery</b>.</p>`,
    tries: [{ t: '📚 Add overload', a: 'stress:deadlines' }, { t: '🪜 Reduce the demand', a: 'cope:plan' }, { t: '🛌 Improve recovery', a: 'cope:sleepgood' }, { t: 'Clear', a: 'clear' }],
    qs: ['q_cope', 'q_two', 'q_steps'] },
  { id: 'L7', title: 'Student practice', sub: 'Use the neuroscience lens.',
    view: 'brain', xray: true, focus: 'amygdala',
    html: `<p class="big">For each situation, decide what is happening in the stress cycle (stressor, activation, recovery) and choose the coping action that would actually help.</p>
      <p>Then write your <b>exit ticket</b> at the bottom: one stressor, one body signal, and one recovery strategy.</p>`,
    tries: [],
    qs: ['q_s1', 'q_s2', 'q_s3'], exit: true }
];

/* ---------- Checks for understanding. Types: mc, multi, match, order, find, mission ---------- */
SB.Q = {
  q_stressor: { lesson: 'L1', type: 'mc', topic: 'Stressors',
    prompt: 'Which statement best describes a stressor?',
    opts: ['Only a bad event that makes you upset', 'Anything your brain reads as a demand that asks your brain and body to adjust', 'A sign that someone cannot handle life', 'Only a physical danger like a car crash'], ans: 1,
    why: 'A stressor is not always "bad": a big game or a performance is a demand too. The brain interprets the demand, then the body responds.' },
  q_cats: { lesson: 'L1', type: 'match', topic: 'Stressors',
    prompt: 'Sort each stressor into its category.',
    rows: [{ t: 'Sleeping too little for a week', o: ['Physical', 'Academic', 'Social', 'Internal'], a: [0] },
           { t: 'A project due on Friday', o: ['Physical', 'Academic', 'Social', 'Internal'], a: [1] },
           { t: 'An argument in the group chat', o: ['Physical', 'Academic', 'Social', 'Internal'], a: [2] },
           { t: 'Worrying "what if I fail?"', o: ['Physical', 'Academic', 'Social', 'Internal'], a: [3] }],
    why: 'Physical (sleep, illness), Academic (tests, deadlines), Social (conflict, pressure), Internal (worry, memories, expectations).' },
  q_chain: { lesson: 'L2', type: 'order', topic: 'Fight / flight',
    prompt: 'Put the alarm chain in order, first step to last.',
    items: ['Amygdala asks: "Could this be danger?"', 'Hypothalamus activates stress pathways', 'Adrenal glands release adrenaline + cortisol', 'Body is ready: heart, breath, muscles'],
    why: 'Amygdala, then hypothalamus, then adrenal glands, then body ready.' },
  q_amyg: { lesson: 'L2', type: 'mc', topic: 'Fight / flight',
    prompt: 'Which part of the brain works like a smoke detector, asking "Could this be danger?"',
    opts: ['Hippocampus', 'Amygdala', 'Cerebellum', 'Occipital lobe'], ans: 1,
    why: 'The amygdala scans for possible danger and fires first and fast.' },
  q_horm: { lesson: 'L2', type: 'mc', topic: 'Fight / flight',
    prompt: 'Which stress hormones do the adrenal glands release?',
    opts: ['Insulin and melatonin', 'Adrenaline and cortisol', 'Oxygen and glucose', 'Calcium and iron'], ans: 1,
    why: 'Adrenaline works in seconds; cortisol works over minutes.' },
  q_fftf: { lesson: 'L2', type: 'mc', topic: 'Fight / flight',
    prompt: 'True or false: the fight/flight response is always harmful.',
    opts: ['True', 'False'], ans: 1,
    why: 'False. It is useful for short bursts. The problem is staying activated with no recovery.' },
  q_gas: { lesson: 'L3', type: 'mc', topic: 'Sympathetic',
    prompt: 'The sympathetic nervous system acts like which pedal?',
    opts: ['The brake pedal', 'The gas pedal', 'The clutch', 'The parking brake'], ans: 1,
    why: 'Sympathetic = gas: it mobilizes energy for action.' },
  q_symp: { lesson: 'L3', type: 'match', topic: 'Sympathetic',
    prompt: 'During sympathetic activation, what happens?',
    rows: [{ t: 'Heart', o: ['Beats faster', 'Beats slower'], a: [0] },
           { t: 'Breathing', o: ['Gets quicker', 'Gets slower'], a: [0] },
           { t: 'Digestion', o: ['Speeds up', 'Slows down'], a: [1] },
           { t: 'Muscles', o: ['Prepare to move', 'Go limp'], a: [0] },
           { t: 'Attention', o: ['Spreads out evenly', 'Locks onto the threat'], a: [1] }],
    why: 'The gas pedal sends energy to muscles and away from digestion, and narrows attention to the threat.' },
  q_mood: { lesson: 'L3', type: 'mc', topic: 'Sympathetic',
    prompt: 'True or false: stress only changes your mood, not your body.',
    opts: ['True', 'False'], ans: 1,
    why: 'False. Stress changes the whole body: heart, breathing, muscles, digestion and attention.' },
  q_brake: { lesson: 'L4', type: 'mc', topic: 'Recovery',
    prompt: 'What is the main job of the parasympathetic nervous system?',
    opts: ['Mobilize energy for action', 'Restore balance after the stressor passes', 'Make memories', 'Send pain signals'], ans: 1,
    why: 'It is the brake pedal: it slows the heart, steadies breathing and restarts digestion.' },
  q_help: { lesson: 'L4', type: 'multi', topic: 'Recovery',
    prompt: 'Select ALL the things that can help the "brake" engage.',
    opts: ['Sleep', 'Slow breathing', 'Movement', 'Talking with someone you trust', 'Staying up all night scrolling', 'Ignoring body signals'], ans: [0, 1, 2, 3],
    why: 'Sleep, breathing, movement, support and time are recovery skills. Scrolling all night and ignoring signals cut recovery short.' },
  q_acch: { lesson: 'L5', type: 'match', topic: 'Acute vs. chronic',
    prompt: 'Is each example acute or chronic stress?',
    rows: [{ t: 'Giving a speech', o: ['Acute', 'Chronic'], a: [0] },
           { t: 'Weeks of conflict at home', o: ['Acute', 'Chronic'], a: [1] },
           { t: 'Taking a quiz', o: ['Acute', 'Chronic'], a: [0] },
           { t: 'Months of nonstop overload', o: ['Acute', 'Chronic'], a: [1] }],
    why: 'Acute = short-term demand with recovery after. Chronic = activation without enough recovery.' },
  q_amq: { lesson: 'L5', type: 'mc', topic: 'Acute vs. chronic',
    prompt: 'Which is the most useful question to ask about stress?',
    opts: ['"Do I have stress?"', '"How do I avoid every stressor forever?"', '"Am I recovering?"', '"Who is to blame?"'], ans: 2,
    why: 'Everyone has stress. What matters is whether the system gets enough recovery.' },
  q_chrfx: { lesson: 'L5', type: 'multi', topic: 'Acute vs. chronic',
    prompt: 'Select ALL that can happen with long-lasting stress and too little recovery.',
    opts: ['The amygdala becomes more reactive', 'Sleep may suffer', 'The prefrontal cortex works less well (harder to focus and plan)', 'The body stays on alert', 'Stress hormones disappear permanently'], ans: [0, 1, 2, 3],
    why: 'Chronic stress can make the alarm more sensitive, hurt sleep and thinking, and keep the body on alert. Recovery and coping help the brain adapt back.' },
  q_cope: { lesson: 'L6', type: 'mc', topic: 'Coping',
    prompt: 'Which statement about coping is true?',
    opts: ['Coping means pretending everything is fine', 'Coping helps the brain and body return to a workable state', 'Coping means never feeling stress', 'Coping only matters when stress is chronic'], ans: 1,
    why: 'Coping is not pretending. It helps the brain and body return to a workable state.' },
  q_two: { lesson: 'L6', type: 'match', topic: 'Coping',
    prompt: 'Does each action mainly reduce the demand or improve recovery?',
    rows: [{ t: 'Break a big project into small steps', o: ['Reduces the demand', 'Improves recovery'], a: [0] },
           { t: 'Slow breathing with long exhales', o: ['Reduces the demand', 'Improves recovery'], a: [1] },
           { t: 'Ask a teacher for help or an extension', o: ['Reduces the demand', 'Improves recovery'], a: [0] },
           { t: 'Get a full night of sleep', o: ['Reduces the demand', 'Improves recovery'], a: [1] }],
    why: 'Useful coping does one of two things: reduces the demand or improves recovery.' },
  q_steps: { lesson: 'L6', type: 'order', topic: 'Coping',
    prompt: 'Put the four coping steps in order.',
    items: ['Notice: name the signal', 'Regulate: slow the body', 'Choose: take the next step', 'Recover: restore energy'],
    why: 'Notice, Regulate, Choose, Recover.' },
  q_s1: { lesson: 'L7', type: 'match', topic: 'Scenarios',
    prompt: 'Scenario 1: Before a presentation, your heart races and your hands shake.',
    rows: [{ t: 'What is happening?', o: ['Acute activation: useful and short-term', 'Chronic stress: weeks without recovery', 'Recovery: the brake is on'], a: [0] },
           { t: 'Best coping action', o: ['Slow exhale breathing and rehearse your first sentence', 'Skip sleep to rehearse all night', 'Avoid ever presenting again'], a: [0] }],
    why: 'This is normal acute activation. Regulate (slow breathing) and make the next step small and clear.' },
  q_s2: { lesson: 'L7', type: 'match', topic: 'Scenarios',
    prompt: 'Scenario 2: A student has slept 4 hours a night for two weeks and feels "always on edge."',
    rows: [{ t: 'What is happening?', o: ['Acute activation: useful and short-term', 'Chronic stress: weeks without recovery', 'Recovery: the brake is on'], a: [1] },
           { t: 'Best coping action', o: ['Drink more energy drinks and push through', 'Protect sleep and ask for help trimming the workload', 'Decide it is a personal weakness'], a: [1] }],
    why: 'Short sleep plus ongoing pressure means activation without recovery. Improve recovery (sleep) and reduce demand (ask for help).' },
  q_s3: { lesson: 'L7', type: 'match', topic: 'Scenarios',
    prompt: 'Scenario 3: After an argument, someone scrolls for hours and cannot calm down.',
    rows: [{ t: 'What is happening?', o: ['Recovery: the brake is on', 'Activation continuing: recovery is not happening', 'No stress response at all'], a: [1] },
           { t: 'Best coping action', o: ['Keep scrolling until sleepy', 'Put the phone down, breathe slowly, walk or talk with someone', 'Replay the argument over and over'], a: [1] }],
    why: 'The alarm is still on. Regulate the body (breathing, movement) and use support to restore recovery.' },
  f_amyg: { lesson: 'X', type: 'find', topic: 'Brain map', target: 'amygdala', needsXray: true,
    prompt: 'Find it: click the structure that works like a smoke detector for danger. (Hint: switch to X-ray view.)',
    why: 'The amygdala: two almond-sized clusters deep in the temporal lobe.' },
  f_pfc: { lesson: 'X', type: 'find', topic: 'Brain map', target: 'prefrontal',
    prompt: 'Find it: click the region at the front of the brain that plans, decides and controls impulses.',
    why: 'The prefrontal cortex: the "thinking brain" that stress turns down.' },
  f_hippo: { lesson: 'X', type: 'find', topic: 'Brain map', target: 'hippocampus', needsXray: true,
    prompt: 'Find it: click the seahorse-shaped structure that files new memories. (X-ray view.)',
    why: 'The hippocampus: key for learning and memory, and sensitive to long-term stress hormones.' },
  f_adr: { lesson: 'X', type: 'find', topic: 'Brain map', target: 'adrenals', needsBody: true,
    prompt: 'Find it: switch to Body view and click the glands that release adrenaline and cortisol.',
    why: 'The adrenal glands sit on top of the kidneys.' },
  m_gas: { lesson: 'LAB', type: 'mission', topic: 'Lab missions', title: 'Hit the gas',
    prompt: 'Add stressors until your heart rate stays above 110 bpm for 2 seconds.', hint: 'Try the dog, or stack a few stressors.' },
  m_brake: { lesson: 'LAB', type: 'mission', topic: 'Lab missions', title: 'Press the brake',
    prompt: 'With stress still turned on, use at least 2 coping tools to hold your heart rate under 90 bpm for 4 seconds.', hint: 'Reduce the demand AND improve recovery. Try a chronic stressor or two with several coping tools.' },
  m_sweet: { lesson: 'LAB', type: 'mission', topic: 'Lab missions', title: 'Find the sweet spot',
    prompt: 'A little stress can help! Get the Focus & performance meter above 90% while a stressor is on (try the intensity slider).', hint: 'Too little or too much stress both lower performance. Try "Big game" at a medium level.' },
  m_wear: { lesson: 'LAB', type: 'mission', topic: 'Lab missions', title: 'Wear and tear',
    prompt: 'Use chronic stressors and skip ahead in time until Wear & tear passes 60%.', hint: 'Turn on 2-3 chronic stressors, then press "Skip ahead 1 week" a few times.' },
  m_recover: { lesson: 'LAB', type: 'mission', topic: 'Lab missions', title: 'Recover and adapt',
    prompt: 'After completing "Wear and tear," bring Wear & tear back under 25% with coping tools and time.', hint: 'Remove stressors, add recovery tools, then skip ahead. The brain adapts.' }
};

SB.LESSON_ORDER = ['L1', 'L2', 'L3', 'L4', 'L5', 'L6', 'L7'];
SB.QUESTION_IDS = Object.keys(SB.Q);
SB.GRADES = [[90, 'A'], [80, 'B'], [70, 'C'], [60, 'D'], [0, 'F']];

SB.HELP = `<h2>How to use Stress &amp; the Brain Lab</h2>
<ul><li><b>Move the brain:</b> drag to rotate, scroll or pinch to zoom.</li>
<li><b>Hover</b> any part of the brain or body to see how it applies to real life. <b>Click</b> for the full card.</li>
<li><b>Surface / X-ray</b> shows the outside (lobes) or the deep structures (amygdala, hippocampus...). <b>Brain / Body</b> switches between brain close-up and the whole system.</li>
<li><b>Learn</b> walks through the lessons. <b>Lab</b> lets you add and remove stress and coping tools. <b>Explore</b> is the brain map. <b>Report</b> is your grade.</li>
<li>Answer the <b>Check for understanding</b> questions as you go. You can retry any question as many times as you want. First-try correct earns full credit (1 point); correct after a retry earns half (0.5). Start a new attempt anytime from the Report tab.</li></ul>
<p class="fine">This is a fictional, simplified model for learning, not medical advice. Time is compressed so you can see effects. If stress ever feels like too much, talk with a trusted adult or school counselor. In the U.S. you can call or text 988 any time.</p>`;
