/* Generates CONTENT-MAP.md (every question → source) and prints a coverage + cognitive-level audit.
   Usage: node tools/content-map.js [--write] */
import fs from 'node:fs';
import content from '../content/index.js';
import cfg from '../config.js';
import spec from './coverage-spec.js';
import { subpartsOf } from './util.js';
import { plain } from './plainText.js';

const items = [];
for (const st of content.stations) for (const e of st.entries) for (const it of (e.block || [e])) {
  items.push({ ...it, _station: st, _kind: it.type === 'explore' ? 'explorer' : it.type === 'place' ? it.mode : (it.chat ? 'chat' : it.type) });
}
const byId = Object.fromEntries(items.map(i => [i.id, i]));
const scored = items.filter(i => i.type !== 'explore');

let md = `# CONTENT-MAP.md — what is assessed and where it comes from\n\n`;
md += `> **Important:** the six source files (3 PPTX, 3 DOCX) were not available when this was built, so the "Source" column cites the **lesson and section named in the brief**, not slide or page numbers. Please check each row against your slides. Generated by \`node tools/content-map.js --write\`.\n\n`;
md += `Scored questions: **${scored.length}** · Points possible: **${scored.reduce((s, i) => s + subpartsOf(i, cfg), 0)}** · Stations: **${content.stations.length}**\n\n`;

md += `## 1. Coverage of the brief (section 3)\n\n| # | Brief topic | Assessed by | Items |\n|---|---|---|---|\n`;
const thin = [], missing = [];
for (const row of spec) {
  const ids = row.items.filter(id => byId[id]);
  const bad = row.items.filter(id => !byId[id]);
  if (bad.length) missing.push(`${row.id}: ${bad.join(', ')}`);
  const scoredIds = ids.filter(id => byId[id].type !== 'explore');
  if (scoredIds.length === 1) thin.push(row);
  if (scoredIds.length === 0) missing.push(`${row.id}: no scored item`);
  md += `| ${row.id} | ${row.topic}${row.note ? ` <br><sub>${row.note}</sub>` : ''} | ${row.src} | ${ids.join(', ')} (${scoredIds.length} scored) |\n`;
}
md += `\n### Topics assessed by only one scored item\n\n`;
md += thin.length ? thin.map(r => `* **${r.id}**: ${r.topic} (${r.items.join(', ')})`).join('\n') : 'None.';
md += `\n\n### Not assessed as separate items\n\n* Sleep needs for teens (8–10 hours) appear as an option and in explanations (Station 4, Capstone), not as a stand-alone item.\n* Myths and facts about mental health: handled through the stigma items (Station 9 Barrier Buster, Capstone section 7) rather than a separate myths station.\n* Brain enrichment (prefrontal cortex regulating the amygdala) was cut for time; it appears in the Station 4 explanation only if you re-add it.\n* Quick-fire vocabulary: replaced by match items (a timed mode was deliberately not built).\n\n`;

// cognitive levels
const lv = { recall: 0, apply: 0, analyze: 0 };
scored.forEach(i => { lv[i.level || 'apply']++; });
const tot = scored.length;
md += `## 2. Cognitive level mix (by question count)\n\n| Level | Questions | Share | Target |\n|---|---|---|---|\n| Recall / vocabulary | ${lv.recall} | ${Math.round(lv.recall / tot * 100)}% | ~30% |\n| Apply to a scenario | ${lv.apply} | ${Math.round(lv.apply / tot * 100)}% | ~50% |\n| Analyze / evaluate | ${lv.analyze} | ${Math.round(lv.analyze / tot * 100)}% | ~20% |\n\n`;

md += `## 3. Every question\n\n`;
for (const st of content.stations) {
  md += `### Station: ${st.title}\n\n| ID | Type | Level | Topic | Pts | Source (lesson › section) | Prompt (start) |\n|---|---|---|---|---|---|---|\n`;
  for (const e of st.entries) for (const it of (e.block || [e])) {
    if (it.type === 'explore') { md += `| ${it.id} | explorer | — | ${st.topic} | 0 | ${it.src || st.id} | ${plain(it.title)} (not scored) |\n`; continue; }
    md += `| ${it.id} | ${it.chat ? 'chat step' : it.type === 'place' ? it.mode : it.type} | ${it.level || 'apply'} | ${it.topic || st.topic} | ${subpartsOf(it, cfg)} | ${it.src || ''} | ${plain(it.prompt).slice(0, 90).replace(/\|/g, '/')} |\n`;
  }
  md += '\n';
}
console.log(`items ${tot}; recall ${lv.recall} apply ${lv.apply} analyze ${lv.analyze}`);
console.log('thin coverage (1 scored item):', thin.map(r => r.id).join(', ') || 'none');
console.log('missing:', missing.length ? missing : 'none');
if (missing.length) process.exitCode = 1;
if (process.argv.includes('--write')) fs.writeFileSync(new URL('../CONTENT-MAP.md', import.meta.url), md);
