/* Builds TIMING.md from the content using js/engine/timing.js.
   Usage: node tools/timing.js [--write]   (prints a summary; --write also writes TIMING.md) */
import fs from 'node:fs';
import content from '../content/index.js';
import cfg from '../config.js';
import { estimateSeconds, INTRO_SECONDS } from '../js/engine/timing.js';
import { subpartsOf } from './util.js';

const rows = [];
let total = 0;
const perStation = [];
for (const st of content.stations) {
  let sec = INTRO_SECONDS + 8; // intro card + station-complete card
  const items = [];
  for (const e of st.entries) for (const it of (e.block || [e])) {
    if ((cfg.disabledItems || []).includes(it.id)) continue;
    const s = it.type === 'explore' ? 35 : estimateSeconds(it, content.passages);
    sec += s;
    items.push({ id: it.id, type: it.type === 'place' ? it.mode : it.type, level: it.level || '', sec: s, pts: it.type === 'explore' ? 0 : subpartsOf(it, cfg) });
  }
  perStation.push({ st, sec, items });
  total += sec;
}
const welcome = 120, fin = 60;
const grand = total + welcome + fin;
const min = (s) => (s / 60).toFixed(1);

let md = `# TIMING.md — time budget\n\nEstimated seconds for a **typical** grade 10 student. Generated by \`node tools/timing.js --write\` from the content files, using \`js/engine/timing.js\` (3 words/second reading speed, base seconds per interaction type, +12% for hints and retries, plus reading time for passages and a few seconds for any visual).\n\nThe app's gentle "about N min left" note uses the same estimates. It never locks anyone out.\n\n`;
md += `| # | Station | Questions | Est. minutes |\n|---|---|---|---|\n| 0 | Welcome, class code, how scoring works | — | ${min(welcome)} |\n`;
perStation.forEach((p, i) => {
  const n = p.items.filter(x => x.type !== 'explore').length;
  md += `| ${i + 1} | ${p.st.title} | ${n} | ${min(p.sec)} |\n`;
});
md += `| 11 | Final score + calm next-step card | — | ${min(fin)} |\n| | **Total** | **${perStation.reduce((s, p) => s + p.items.filter(x => x.type !== 'explore').length, 0)}** | **${min(grand)}** |\n\n`;
md += `Target: 45 minutes ±5. ${grand / 60 <= 50 && grand / 60 >= 40 ? '✅ Within range.' : '⚠️ Outside range; adjust items.'}\n\n## Per-item estimates (seconds)\n\n`;
perStation.forEach(p => {
  md += `### ${p.st.title}\n\n| Item | Type | Level | Seconds |\n|---|---|---|---|\n`;
  p.items.forEach(x => { md += `| ${x.id} | ${x.type} | ${x.level} | ${x.sec} |\n`; });
  md += '\n';
});
md += `## How to use pilot data\n\nAfter the 3–5 student pilot (see ROLLOUT.md), compare the students' actual times with this table. If students are consistently faster or slower, change \`WPS\` or the base seconds in \`js/engine/timing.js\`, or add or remove items. Then re-run \`node tools/timing.js --write\`.\n`;

console.log(perStation.map((p, i) => `${i + 1} ${p.st.id}: ${min(p.sec)} min (${p.items.length} entries)`).join('\n'));
console.log(`TOTAL ${min(grand)} min`);
if (process.argv.includes('--write')) fs.writeFileSync(new URL('../TIMING.md', import.meta.url), md);
