/* Wildcats Wellness Quest — default configuration.
 * Teachers: do NOT edit this file. Edit js/teacher-config.js instead (it overrides these defaults).
 */
(function (root) {
  'use strict';
  var W = root.WWQ = root.WWQ || {};

  W.CONFIG = {
    appName: 'Wildcats Wellness Quest',
    subtitle: 'Small Choices, Whole Health',
    school: 'Wildcats',

    // Changing this changes the browser-storage keys, which starts a fresh local record on every device.
    // Only change it between class sets, and only as a deliberate teacher decision (see docs/TEACHER_SETUP.md).
    assessmentVersion: 'wwq-1.0',

    // Scored-attempt policy. "Attempts" includes the first submission.
    // short  = matching / classification / metric meaning / short concept items
    // complex = data interpretation, multi-step calculation, scenario application, evidence evaluation, structured reasoning
    // Short items ship with 2 authored equivalent variants, so their limit cannot exceed 2 unless a 3rd variant exists.
    attemptLimits: { short: 2, complex: 3 },
    // Maximum share of an item's points available on attempt 1, 2, 3 (teacher-selected grading policy).
    caps: [1, 0.9, 0.75],

    // Pacing guidance only. Nothing is ever enforced, timed out or speed-scored.
    timeGuidance: { targetMinutes: 36, rangeMinutes: [30, 40], extendedMultiplier: 1.5, extendedTime: false },
    // Show optional deeper-exploration extras inside missions (never required, never scored).
    extendedExploration: false,

    // 'auto' follows the device's reduced-motion setting; 'on' / 'off' force it for everyone at first load.
    motion: 'auto',

    // Optional letter grade on the results page. Boundaries use the UNROUNDED total.
    letterGrades: {
      enabled: false,
      bands: [
        { min: 90, letter: 'A' }, { min: 80, letter: 'B' }, { min: 70, letter: 'C' },
        { min: 60, letter: 'D' }, { min: 0, letter: 'F' }
      ]
    },

    // Student identification. The alias is typed text, not verified identity.
    identifierLabel: 'Student alias or teacher-approved ID',
    requireIdentifier: true,

    // Teacher reset passcode verifier. Generate with teacher/passcode-setup.html or tools/make-passcode.js.
    // NOTHING is active by default: until a teacher sets this, the reset control stays disabled.
    teacher: {
      configured: false,
      salt: '',
      iterations: 30000,
      verifier: '',
      freeTries: 3,
      cooldownSeconds: 30
    }
  };

  // Teacher overrides (shallow-merged one level deep).
  W.applyConfig = function (over) {
    var C = W.CONFIG;
    Object.keys(over || {}).forEach(function (k) {
      if (over[k] && typeof over[k] === 'object' && !Array.isArray(over[k]) && C[k] && typeof C[k] === 'object') {
        Object.keys(over[k]).forEach(function (j) { C[k][j] = over[k][j]; });
      } else { C[k] = over[k]; }
    });
  };
})(typeof window !== 'undefined' ? window : globalThis);
