'use strict';
// Build everything that is generated.  Run:  node tools/build.js
//   dist/apps-script/Code.gs          PUBLIC engine + Sheets adapter (contains NO questions and NO answers)
//   dist/apps-script/appsscript.json  Apps Script manifest
//   private/KeyData.gs                PRIVATE question bank WITH answers (paste into the same Apps Script project; never commit)
//   private/ANSWER_KEY.md             PRIVATE printable answer key
//   docs/BLUEPRINT.md                 assessment blueprint (no answers)
//   docs/CURRICULUM_ALIGNMENT.md      curriculum alignment matrix (no answers)
//   js/lo-data.js                     objective descriptions for Teacher Mode (public text, no answers)
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const write = (p, s) => { const f = path.join(ROOT, p); fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, s); };
const HAVE_BANK = fs.existsSync(path.join(ROOT, 'authoring', 'index.js'));

// ------------------------------------------------------------------------------------------ Code.gs (public)
function buildCode() {
  const parts = ['shared/core.js', 'shared/seeds.js', 'shared/data.js', 'server/grading.js', 'server/engine.js', 'server/apps-script/adapter.js'];
  const header = '// Gambling: Behind the Odds. Google Apps Script backend (GENERATED by tools/build.js; edit the sources, not this file).\n// Contains NO questions and NO answer key. The private question bank is KeyData.gs.\n// Paste this whole file into Code.gs, and paste KeyData.gs into a second file, in the SAME Apps Script project.\n';
  const body = parts.map((p) => '\n// ===== ' + p + ' =====\n' + read(p)).join('\n');
  write('dist/apps-script/Code.gs', header + body);
  write('dist/apps-script/appsscript.json', JSON.stringify({
    timeZone: 'America/New_York', exceptionLogging: 'STACKDRIVER', runtimeVersion: 'V8',
    oauthScopes: ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/script.container.ui', 'https://www.googleapis.com/auth/script.scriptapp'],
    webapp: { executeAs: 'USER_DEPLOYING', access: 'ANYONE_ANONYMOUS' }
  }, null, 2));
  return header.length + body.length;
}

// ------------------------------------------------------------------------------------------ KeyData.gs (private)
function buildKeyData() {
  const files = ['lib.js', 'ch1.js', 'ch2.js', 'ch3.js', 'ch4.js', 'ch5.js', 'ch6.js', 'index.js'];
  let out = '// PRIVATE. Gambling: Behind the Odds question bank WITH answer keys (GENERATED by tools/build.js).\n// Keep this file ONLY in your Apps Script project. Never put it in a public repository.\n';
  out += 'function u5LoadBank_() {\n  var defs = {\n';
  files.forEach((f) => { out += `    ${JSON.stringify(f)}: function (module, exports, require) {\n${read('authoring/' + f)}\n    },\n`; });
  out += `  };
  var cache = {};
  function req(name) {
    if (name === '../shared/core.js') return U5;
    if (name === '../shared/data.js') return U5D;
    var base = name.replace(/^.*\\//, '');
    if (!cache[base]) { var m = { exports: {} }; cache[base] = m; defs[base](m, m.exports, req); }
    return cache[base].exports;
  }
  return req('./index.js');
}
`;
  write('private/KeyData.gs', out);
  return out.length;
}

// ------------------------------------------------------------------------------------------ docs
function levelName(l) { return { U: 'Remember / Understand', P: 'Apply', N: 'Analyze', E: 'Evaluate' }[l]; }
function describeParts(it) {
  const t = { choice: 'multiple choice', multi: 'select all', number: 'calculation', map: 'matching/classifying', order: 'ordering' };
  return it.parts.map((p) => (p.type === 'map' && p.ui === 'drag' ? 'drag-and-drop sort (select alternative)' : t[p.type] + (p.type === 'number' ? ` (${p.fields.length} field${p.fields.length > 1 ? 's' : ''})` : ''))).join(' + ');
}
function buildDocs() {
  const G = require('../server/grading.js'), T = require('./timing.js'), LO = require('../authoring/lo.js'), bank = require('../authoring');
  const idx = G.buildIndex(bank);
  const inst = (id) => G.instantiate(idx.items[id], { seed: 'blueprint' });
  const SIMS = { coin: 'A. Probability Laboratory', house: 'B. House Edge Investigation', sports: 'C. Sports Analytics Desk', brain: 'D. Neuroscience Lab', adlab: 'E. Ad Investigation Lab', decide: 'F. Story Studio and Decision Lab' };
  const tot = { U: 0, P: 0, N: 0, E: 0 }, chap = [];
  let allTyp = 0, allSlow = 0, nItems = 0, nParts = 0, nTasks = 0;
  bank.chapters.forEach((c) => {
    let typ = 0, slow = 0, pts = 0; const rows = [];
    c.steps.forEach((s) => {
      if (s.kind === 'item') {
        const it = inst(s.id), mt = T.itemMinutes(it, 'typical'), ms = T.itemMinutes(it, 'slow'), sw = it.parts.reduce((a, p) => a + (p.w != null ? p.w : 1), 0), lv = { U: 0, P: 0, N: 0, E: 0 };
        it.parts.forEach((p) => { const v = it.pts * (p.w != null ? p.w : 1) / sw; lv[p.lvl] += v; tot[p.lvl] += v; });
        typ += mt; slow += ms; pts += it.pts; nItems++; nParts += it.parts.length;
        rows.push(`| ${s.id} | ${it.title} | ${describeParts(it)} | ${it.pts} | ${Object.keys(lv).filter((k) => lv[k]).map((k) => k + ' ' + (Math.round(lv[k] * 10) / 10)).join(', ')} | ${mt} / ${ms} | ${(it.lo || []).join(', ')} | ${it.sim ? SIMS[it.sim].split('.')[0] : ''} |`);
      } else {
        const mt = T.stepMinutes(s, 'typical'), ms = T.stepMinutes(s, 'slow'); typ += mt; slow += ms;
        rows.push(`| ${s.id} | *${s.kind === 'sim' ? 'Simulation: ' + SIMS[s.sim] : s.kind === 'brief' ? 'Briefing' : 'Chapter opening'}* | ${s.kind === 'sim' ? 'interactive exploration (feeds the graded items)' : 'reading'} | 0 | | ${mt} / ${ms} | | ${s.sim ? SIMS[s.sim].split('.')[0] : ''} |`);
      }
    });
    chap.push({ c, typ, slow, pts, rows }); allTyp += typ; allSlow += slow;
  });
  nTasks = nParts;
  const pct = (k) => (Math.round(tot[k] * 10) / 10);
  let md = `# Assessment Blueprint: Gambling: Behind the Odds

*Generated by \`tools/build.js\` from the question bank. Contains no answers.*

## Summary

| Item | Value |
|---|---|
| Scored items (graded activities) | **${nItems}** |
| Individually checked responses (parts) | **${nParts}** |
| Total points | **${Math.round(chap.reduce((a, x) => a + x.pts, 0))}** |
| Estimated working time, typical student | **${Math.round(allTyp)} min** |
| Estimated working time, slower reader | **${Math.round(allSlow)} min** |
| Hard limit (enforced by the server) | **90 min** from the moment the student presses Begin |
| Attempts per item | 3, with credit 100% / 85% / 75% / 0% |

### Honest note on timing and item count
The time figures are computed by \`tools/timing.js\` from the actual words, tables and response fields in each item (reading speed and per-response time constants are listed in that file). They are **estimates, not measurements**. A first draft of this bank measured about 115 minutes with the same model, so the items were deliberately shortened until the typical estimate came to about one hour and the slower-reader estimate stayed below the 90-minute limit. That trade-off is why the bank has ${nItems} items (${nParts} checked responses) rather than 40+. Pilot with one real class, then adjust. Adding items raises the time.

### Cognitive-level distribution (share of the 100 points)

| Level | Target | This bank |
|---|---:|---:|
| Remember / Understand | 15 | ${pct('U')} |
| Apply | 30 | ${pct('P')} |
| Analyze | 35 | ${pct('N')} |
| Evaluate | 20 | ${pct('E')} |

Each part of each item is tagged with a level. An item's points are split among its parts by weight (\`w\`), and the table is the weighted sum. A test (\`tests/bank.test.js\`) fails if any level drifts more than 3 points from its target.

### Scoring rule (identical for every item)
Pressing **Check answer** is one attempt. An attempt earns accuracy *f* (the weighted fraction of the item's parts that are right; always 0 or 1 for a single-answer item). Credit for that attempt is the attempt multiplier (1.00, 0.85, 0.75 for attempts 1-3) times *f*. The item's credit is the **best** attempt credit. An item locks when it is fully correct, when attempt 3 is used, or when no later attempt could raise the credit already earned. Blank or malformed answers never use an attempt. Unanswered items earn 0.

## Chapters
`;
  chap.forEach((x) => {
    md += `\n### Chapter ${x.c.id}: ${x.c.title}\n*${x.c.subtitle}*\n\nVisual identity: \`${x.c.theme}\` | points: **${x.pts}** | target ${x.c.minutes} min | estimate (typical / slower reader): **${x.typ.toFixed(1)} / ${x.slow.toFixed(1)} min**\n\n| Step | Title | Type | Pts | Levels | Min (typ / slow) | Objectives | Sim |\n|---|---|---|---:|---|---|---|---|\n${x.rows.join('\n')}\n`;
  });
  md += `\n## Simulations\n\n| Sim | Where | What is graded from it |\n|---|---|---|\n| A. Probability Laboratory | Chapter 2 | the student's own seeded coin sequence (heads in 20 flips, percent heads, how percent and count gap behave as flips grow) |\n| B. House Edge Investigation | Chapter 2 | the student's own seeded High/Low dice run (balance after 200 rounds versus the expected balance) |\n| C. Sports Analytics Desk | Chapter 4 | parlay probability and expected value from the fictional slate; the effect of adding legs |\n| D. Neuroscience Lab | Chapter 3 | reward pathway, variable reward, near-miss data, loss chasing, teen-brain timeline |\n| E. Ad Investigation Lab | Chapter 5 | technique, audience and missing information in six fictional ads; the social feed |\n| F. Story Studio and Decision Lab | Chapter 6 | warning signs in four vignettes, the 5-step decision model, refusal skills, help resources |\n`;
  write('docs/BLUEPRINT.md', md);

  // ---- curriculum alignment matrix
  const used = {};
  idx.order.forEach((id) => { const it = inst(id); (it.lo || []).forEach((l) => { (used[l] = used[l] || []).push(id); }); });
  let am = `# Curriculum Alignment Matrix

*Generated by \`tools/build.js\`. Learning objectives were extracted from all 20 files in the uploaded Unit 5 folder. "Source" cites the file and slide or section that teaches the objective. Contains no answers.*

| Objective | Chapter | What students should be able to do | Taught in (source) | Assessed by |
|---|---:|---|---|---|
`;
  Object.keys(LO.list).forEach((code) => { const o = LO.list[code]; am += `| **${code}** | ${o.ch} | ${o.t} | ${o.src.join('; ')} | ${(used[code] || []).join(', ')} |\n`; });
  am += `\n## Coverage by uploaded file\n\n| Uploaded file | Used for |\n|---|---|\n`;
  const FILES = [
    ['Day 1: How Gambling Works (lesson plan), Gambling Probability slides, Guided Notes', 'Chapters 1-2: definition of gambling, probability, odds, house advantage, gambler’s fallacy, Law of Large Numbers, coin and dice labs, High/Low house-edge game, American roulette'],
    ['Day 1: Prediction Markets Video Guide', 'Chapter 1 (EventX item) and Chapter 4 (building a book): who is on the other side, fees, "trade" framing. *The video itself was not available; only the guide’s questions were used.*'],
    ['Day 2: Psychology lesson plan, Beat the Odds slides', 'Chapter 3: reward pathway, variable reinforcement, tolerance, teen brain, near misses, chasing losses'],
    ['Day 2: Gambling Brain Lab Station Packet', 'Chapter 3 and Simulation D: the four stations (the Station 1 spinner is a fair game, EV = 0; Station 4 EV = -1/6)'],
    ['Day 2: Sports Betting and Lottery Odds handout', 'Chapter 4: break-even rates, vig, "pros" win rates, parlay hold, lottery odds, regressive spending'],
    ['Day 3: Marketing lesson plan, slides, packet, mock slogans', 'Chapter 5 and Simulation E: six mock ad cards reproduced as written, slogans, tactics, worksheet questions, PSA rubric'],
    ['Day 4: Healthy Decision-Making lesson plan, slides, Two-Reader Vignettes', 'Chapter 6 and Simulation F: warning signs, consequences, 5-step model, refusal skills, help resources, the four vignettes'],
    ['Unit 5 Inquiry-Based Summative; Unit 5 Summative Assessment', 'Assessment expectations: four content areas, Game A/B expected-value style, "I’m due", Malik, risk-free, social posts, "Can you cover me?" and the final synthesis question'],
    ['Day 1/2/5 link documents', 'Lucky Rush Casino, Parlay Lab and House Edge apps: fictional league and teams are reused from Parlay Lab for continuity']
  ];
  FILES.forEach((r) => { am += `| ${r[0]} | ${r[1]} |\n`; });
  write('docs/CURRICULUM_ALIGNMENT.md', am);
  write('js/lo-data.js', '/* GENERATED by tools/build.js: learning-objective text for Teacher Mode (no answers). */\nwindow.U5_LO = ' + JSON.stringify(LO.list) + ';\n');

  // ---- printable answer key (private)
  let ak = '# PRIVATE: Answer key and explanations\n\n*Do not publish. Items marked "(varies)" use numbers that differ per student; the example below is one student\'s version. Teacher Mode shows the same key.*\n';
  bank.chapters.forEach((c) => {
    ak += `\n## Chapter ${c.id}: ${c.title}\n`;
    c.steps.filter((s) => s.kind === 'item').forEach((s) => {
      const it = G.instantiate(idx.items[s.id], { seed: 'answer-key' }), varies = typeof idx.items[s.id].def === 'function';
      ak += `\n### ${s.id}: ${it.title} (${it.pts} pts${varies ? ', varies' : ''})\n${it.prompt}\n\n`;
      G.formatKey(it).forEach((k) => { ak += `- **Answer:** ${k.text}\n`; });
      ak += `- **Explanation:** ${it.explain}\n- **Hints:** (1) ${it.hints[0]} (2) ${it.hints[1]}\n- **Objectives:** ${(it.lo || []).join(', ')}\n`;
    });
  });
  write('private/ANSWER_KEY.md', ak);
  return { nItems, nParts, allTyp, allSlow };
}

const sz = buildCode();
console.log('built dist/apps-script/Code.gs (' + Math.round(sz / 1024) + ' KB) and appsscript.json');
if (HAVE_BANK) {
  const kb = buildKeyData();
  console.log('built private/KeyData.gs (' + Math.round(kb / 1024) + ' KB)');
  const r = buildDocs();
  console.log('built docs/BLUEPRINT.md, docs/CURRICULUM_ALIGNMENT.md, private/ANSWER_KEY.md, js/lo-data.js:', r.nItems, 'items,', r.nParts, 'parts, est.', Math.round(r.allTyp), 'min typical /', Math.round(r.allSlow), 'min slow');
  if (fs.existsSync(path.join(ROOT, '.vault-pass'))) { const v = require('./vault.js'); console.log('re-locked vault/authoring.vault (' + v.lock() + ' files)'); }
} else console.log('authoring/ not present: only the public Code.gs was built. Run: node tools/vault.js unlock');
