'use strict';
// Builds shared/seeds.js: vetted per-student simulation seeds.  Run:  node tools/seeds.js
// Why: each student's lab uses a fixed pseudo-random stream so the server can re-compute any number the
// student reads from their own lab.  A raw random seed could show a "weird" run (e.g. exactly 10 heads in 20,
// or a 1,000-flip run that is further from 50% than the 20-flip run), which would contradict the lesson.
// So we only keep seeds whose data show the intended phenomena.
const fs = require('fs');
const path = require('path');
const U5 = require('../shared/core.js');

function coinOk(seed) {
  const s20 = U5.coinStats(seed, 20), s100 = U5.coinStats(seed, 100), s1000 = U5.coinStats(seed, 1000);
  const dev20 = Math.abs(s20.pctHeads - 50), dev100 = Math.abs(s100.pctHeads - 50), dev1000 = Math.abs(s1000.pctHeads - 50);
  const gap20 = Math.abs(s20.heads - s20.tails), gap1000 = Math.abs(s1000.heads - s1000.tails);
  if (dev20 < 5 || dev20 > 15) return false;                 // 20 flips: 7-9 or 11-13 heads (never exactly 10, never extreme)
  if (dev1000 > 2.2 || dev1000 < 0.4) return false;          // 1000 flips: close to, but not exactly, 50%
  if (dev1000 >= dev20 - 3) return false;                    // the larger run is clearly closer in percent
  if (gap1000 < gap20 + 6) return false;                     // ...while the head/tail COUNT gap is larger
  if (dev100 > 12) return false;
  if (s1000.longest < 8 || s1000.longest > 12) return false; // a memorable streak exists
  return true;
}
function houseOk(seed) {
  const r = U5.houseRun(seed, 200, 'high');
  const r20 = r.series[20], r10 = r.series[10];
  // mix: most students end below start; some end above; most are ahead at round 10 (short-term luck) 
  return r.balance >= 55 && r.balance <= 125 && r10 >= 95;
}
const coin = [], houseBelow = [], houseAbove = [];
for (let s = 1; s < 200000 && (coin.length < 64 || houseBelow.length < 52 || houseAbove.length < 12); s++) {
  if (coin.length < 64 && coinOk(s)) coin.push(s);
  if (houseOk(s)) {
    const b = U5.houseRun(s, 200, 'high').balance;
    if (b < 100 && houseBelow.length < 52) houseBelow.push(s);
    else if (b >= 100 && houseAbove.length < 12) houseAbove.push(s);
  }
}
const house = [];
// interleave so a modulo pick gives the intended ~80/20 split
let bi = 0, ai = 0;
while (house.length < 64 && (bi < houseBelow.length || ai < houseAbove.length)) {
  for (let k = 0; k < 4 && bi < houseBelow.length && house.length < 64; k++) house.push(houseBelow[bi++]);
  if (ai < houseAbove.length && house.length < 64) house.push(houseAbove[ai++]);
}
const out = `/* GENERATED by tools/seeds.js: vetted simulation seeds (not secret). Do not edit. */
(function (root) {
  'use strict';
  var SEEDS = ${JSON.stringify({ coin, house })};
  if (typeof module === 'object' && module && module.exports) module.exports = SEEDS;
  root.U5_SEEDS = SEEDS;
})(typeof globalThis !== 'undefined' ? globalThis : (typeof self !== 'undefined' ? self : this));
`;
fs.writeFileSync(path.join(__dirname, '..', 'shared', 'seeds.js'), out);
console.log('coin seeds', coin.length, 'house seeds', house.length, '(below start:', houseBelow.length, 'above:', houseAbove.length + ')');
const sample = coin.slice(0, 4).map(s => ({ s, h20: U5.coinStats(s, 20).heads, p1000: U5.coinStats(s, 1000).pctHeads, long: U5.coinStats(s, 1000).longest }));
console.log(sample);
