'use strict';
// Reference register. `verified` records HOW far each reference was checked. The builder's network
// could not fetch the agency pages directly (egress blocked), so facts were checked only against search-result
// excerpts of the pages. The teacher must open each URL and confirm before classroom use (docs/SOURCES.md).
const ACCESS = '2026-10-07';
const R = [
  { id: 'airnow', org: 'U.S. EPA / AirNow', title: 'Air Quality Index (AQI) Basics', url: 'https://www.airnow.gov/aqi/aqi-basics/', date: 'Not retrieved', claim: 'Six AQI categories and ranges: Good 0-50, Moderate 51-100, Unhealthy for Sensitive Groups 101-150, Unhealthy 151-200, Very Unhealthy 201-300, Hazardous 301+; higher AQI means greater health concern; sensitive groups affected first.', tasks: ['M3-U2', 'M6-U2', 'M6-U5'], status: 'Category ranges confirmed from search-result excerpt; page not fetched' },
  { id: 'epauv', org: 'U.S. EPA', title: 'UV Index Scale', url: 'https://www.epa.gov/sunsafety/uv-index-scale-0', date: 'Not retrieved', claim: 'UV Index 8-10 Very High and 11+ Extreme; protection includes shade, hat, sunglasses, protective clothing, SPF 30+ sunscreen reapplied about every 2 hours, and limiting midday sun. No individual burn clock is given or used.', tasks: ['M3-U3'], status: 'Confirmed from search-result excerpts (EPA snapshot and NWS UV index page); page not fetched' },
  { id: 'niosh', org: 'CDC / NIOSH', title: 'Understand Noise Exposure', url: 'https://www.cdc.gov/niosh/noise/prevent/understand.html', date: 'Not retrieved', claim: 'NIOSH recommended exposure limit (REL) 85 dBA averaged over 8 hours with a 3 dBA exchange rate (time halves per 3 dBA). It is an occupational recommendation and not a guarantee of safety.', tasks: ['M3-U1', 'M3-U4'], status: 'REL and exchange rate confirmed from search-result excerpt; page not fetched' },
  { id: 'nws', org: 'National Weather Service', title: 'Heat information (Heat Index)', url: 'https://www.weather.gov/lwx/heat', date: 'Not retrieved', claim: 'Heat index categories (caution, extreme caution, danger, extreme danger) and that values are for shade and light wind; direct sun can add up to about 15 °F. Category edges differ slightly between excerpts, so tasks use only a value (98 °F) inside "extreme caution" under either edge and state no cancel threshold.', tasks: ['M3-U5'], status: 'Confirmed from search-result excerpts of NWS chart material; page not fetched. Verify category edges.' },
  { id: 'cdcwater', org: 'CDC', title: 'Drinking Water Advisories: An Overview', url: 'https://www.cdc.gov/water-emergency/about/drinking-water-advisories-an-overview.html', date: 'Not retrieved', claim: 'Boil-water, do-not-drink and do-not-use advisories differ; boiling kills germs but does not remove chemicals; follow the advisory instructions.', tasks: ['M3-U6'], status: 'Confirmed from search-result excerpt; page not fetched' },
  { id: 'ftc', org: 'U.S. Federal Trade Commission', title: 'Disclosures 101 for Social Media Influencers', url: 'https://www.ftc.gov/business-guidance/resources/disclosures-101-social-media-influencers', date: 'Not retrieved', claim: 'Material connections (such as payment or free products) should be disclosed clearly and conspicuously; abbreviations such as "sp" are not adequate disclosures.', tasks: ['M5-U2'], status: 'Confirmed from search-result excerpts of secondary law-firm summaries; FTC page not fetched. Verify wording.' },
  { id: 'gas1', org: 'Google', title: 'Web Apps (Apps Script guide)', url: 'https://developers.google.com/apps-script/guides/web', date: 'Not retrieved', claim: 'Apps Script web app deployment, access and execute-as settings.', tasks: ['Deployment docs'], status: 'Not fetched; setup instructions are written from general knowledge and must be checked against the current Google UI' },
  { id: 'gas2', org: 'Google', title: 'HTML Service (Apps Script guide)', url: 'https://developers.google.com/apps-script/guides/html', date: 'Not retrieved', claim: 'HtmlService, templates and google.script.run.', tasks: ['Deployment docs'], status: 'Not fetched' }
];
const ORIGINAL = [
  { id: 'cls', title: 'Original classroom data: fictional disparities table (Riverview, East Junction, Pine Hills, Lakeview)', tasks: ['M4-U1', 'M4-U2', 'M4-U3', 'M4-U4'] },
  { id: 'gen', title: 'Fictional generated scenarios: Riverbend profile details, picnic outbreak table, SparkUp post, source cards, district practice log, Eastbrook County', tasks: ['M1-*', 'M2-*', 'M5-*', 'M6-*'] }
];
module.exports = { ACCESS, REFERENCES: R, ORIGINAL };
