/* THE HOUSE EDGE — Teacher panel, Teacher Summary and CLASSROOM DEBRIEF presentation mode. */
(function (root) {
  'use strict';
  var HE = root.HE = root.HE || {}, C = HE.CONFIG, E = HE.Engine, P = HE.Progress, UI = HE.UI, Ch = HE.Charts, QE = HE.QE, Sim = HE.Sim, PL = HE.Parlay;
  var $ = UI.$, $$ = UI.$$, esc = UI.esc, fmt = E.fmt, sg = E.signed, pc = E.pct;
  var D = HE.Debrief = {};

  /* =====================================================================
     TEACHER SUMMARY CONTENT
     ===================================================================== */
  var SUMMARY = {
    objectives: ['Distinguish a PERSONAL RESULT from the EXPECTED RESULT of a game.', 'Compute and interpret probability, expected value, return to player (RTP) and house edge.', 'Explain why one win (or one loss) is one sample, and why large samples reveal the pattern (Law of Large Numbers).', 'Explain why each added parlay leg lowers the chance that the whole ticket wins, and what bookmaker margin does.', 'Recognize cognitive biases (gambler\'s fallacy, hot hand, illusion of control, near-miss effect, loss chasing, selective memory, sunk cost) and interface design features that shape the experience without changing the odds.'],
    misconceptions: ['"After a streak, the other outcome is due" (gambler\'s fallacy).', '"A winning streak proves skill or a working system."', '"RTP tells me what I personally will get back."', '"The house has to win every bet / every player must lose." (Not true: individual players can finish ahead.)', '"A huge payout means a good bet." (Payout must be weighed by probability.)', '"A near miss means I was close to winning," or "my next spin is more likely to hit."', '"I need to win back what I lost." (loss chasing / sunk cost)', '"Parlays are just several chances to win." (They require ALL legs.)'],
    takeaways: ['A person can win in the short term while playing a game with negative expected value. Both facts are true.', 'Expected value is a long-run average, not a prediction for one session.', 'One result is one sample. Look at the full distribution, the amount wagered and the probabilities.', 'Flashy presentation changes the experience, not the probabilities.', 'Understand the game before the game plays you.'],
    followups: ['If the expected value per spin is −1.05, why can the first 20 spins still be profitable?', 'What would you need to know to decide whether a friend\'s "winning system" works?', 'Why might bettors remember wins more than losses? Who benefits from that?', 'Parlay legs are rarely truly independent. How would positive correlation change the combined probability?', 'Why do you think the house-edge experiment still produced winners at 10%?'],
    vocab: [['Probability', 'How likely an outcome is, from 0 to 1 (or 0% to 100%).'], ['Independent events', 'Outcomes that do not affect each other.'], ['Expected value (EV)', 'The probability-weighted average outcome over many repetitions.'], ['House edge', 'The expected share of each wager the operator keeps in the long run (1 − RTP).'], ['RTP (return to player)', 'Expected tokens returned per token wagered over many wagers.'], ['Variance', 'How spread out individual results are around the expected value.'], ['Parlay', 'One bet combining several legs; all must win.'], ['Law of Large Numbers', 'Averages over many trials tend to settle near the expected value.'], ['Sample', 'A single observed result (or a set of them).'], ['Selection bias', 'When the examples we see are not representative because of how they were chosen.']],
    reactions: ['"But I won, so it works!" Honor the result, then ask about wagers, distribution and expectation.', '"This is rigged." The configuration is visible in Teacher Mode and X-Ray: individual spins are not manipulated.', '"Lucky student" excitement or "unlucky student" frustration. Both are single samples; use the 10,000-player lab.', 'Students sometimes read the plain Game B as "boring" and the flashy Game A as "better." That is the design lesson.'],
    clarify: ['Do NOT teach "every gambler loses." Teach "individual outcomes vary; expected value describes the average across repeated play."', 'This simulation uses randomized JavaScript outcomes; it does not describe how every commercial machine works.', 'The simplified parlay calculation assumes independence.', 'Hot-hand research in real sports is nuanced; in a fair coin process there is no hot hand by definition.', 'The activity never asks students about their own or family gambling.', 'Confirm the helpline number on ncpgambling.org before class.'],
    extensions: ['Have students recompute EV for the Prism Wheel (18 red, 18 black, 2 green) and Twin Dice.', 'Change a probability or payout in config.js and predict, then test, the effect on RTP.', 'Spreadsheet Monte Carlo: simulate 1,000 players with RAND().', 'Media-literacy task: critique a fictional "I turned 50 into 1,200" post using the checklist from Discussion 7.', 'Probability trees for a 3-leg parlay with correlated legs.']
  };
  D.SUMMARY = SUMMARY;

  /* =====================================================================
     TEACHER PANEL
     ===================================================================== */
  function li(a) { return '<ul>' + a.map(function (x) { return '<li>' + esc(x) + '</li>'; }).join('') + '</ul>'; }
  function modelsHtml() {
    var h = '<h4>Game models (centrally configured in js/config.js)</h4>';
    Object.keys(C.games).forEach(function (k) {
      var g = E.game(k); h += '<h5>' + esc(g.name) + ' <small>RTP ' + pc(g.rtp, 2) + ' · house edge ' + pc(g.edge, 2) + ' · EV per token ' + fmt(g.ev, 4) + ' · SD per token ' + fmt(g.sd, 2) + '</small></h5><table class="vision"><thead><tr><th>Outcome</th><th>Probability</th><th>Return ×</th><th>Net per token</th></tr></thead><tbody>' + g.outcomes.map(function (o) { return '<tr><td>' + esc(o.label) + '</td><td>' + pc(o.p, 2) + '</td><td>' + fmt(o.ret, 2) + '</td><td>' + sg(o.ret - 1, 2) + '</td></tr>'; }).join('') + '</tbody></table>';
    });
    h += '<h4>Sportsbook (fictional)</h4><p>Leg price = (1 − margin) ÷ true probability, margin = ' + pc(C.sports.margin, 1) + '. Slate true probabilities:</p><table class="vision"><thead><tr><th>Game</th><th>Home</th><th>P(home)</th><th>Away</th><th>Offered ×</th></tr></thead><tbody>' + C.sports.slate.map(function (g) { return '<tr><td>' + g.id + '</td><td>' + esc(C.sports.teams[g.home].name) + '</td><td>' + pc(g.pHome, 0) + '</td><td>' + esc(C.sports.teams[g.away].name) + '</td><td>' + fmt(PL.legOdds(g.pHome), 2) + ' / ' + fmt(PL.legOdds(1 - g.pHome), 2) + '</td></tr>'; }).join('') + '</tbody></table>';
    h += '<h4>Simulation assumptions</h4>' + li(['Outcomes are drawn with a seeded-from-crypto xorshift-style generator (mulberry32). Each draw maps one uniform random number onto the cumulative probability ranges in config.js.', 'The SAME outcome tables drive gameplay, the X-Ray layers, EV tables, the Monte Carlo engine, and every chart.', 'Spins are independent. Nothing is adjusted to make students win or lose.', 'Zone 2 / Zone 7: every simulated player repeats the student\'s exact sequence of wagers on the same game.', 'Zone 8: the student\'s strategy object is run by the same function for the student and for 10,000 simulated players.', 'Near break-even = within ±' + pc(C.sim.breakEvenBandPct, 0) + ' of tokens wagered.', 'Parlay probabilities assume independent legs.', 'Reels, wheel and dice graphics are decoration chosen to match the already-drawn outcome.']);
    return h;
  }
  function answerKey() {
    var h = '<table class="vision"><thead><tr><th>ID</th><th>Concept</th><th>Question</th><th>Correct</th></tr></thead><tbody>';
    HE.QUESTIONS.forEach(function (q) {
      var cv = typeof q.correct === 'function' ? q.correct() : q.correct, ans = q.choices ? (q.choices.filter(function (c) { return c.id === cv; })[0] || { text: cv }).text : (q.type === 'numeric' ? fmt(cv, 3) : cv);
      if (q.type === 'poll') ans = '(opinion: no wrong answer)';
      h += '<tr><td>' + q.id + '</td><td>' + q.concept + '</td><td>' + esc(typeof q.prompt === 'function' ? q.prompt() : q.prompt) + '</td><td>' + esc(ans) + '</td></tr>';
    });
    return h + '</tbody></table>';
  }
  D.teacherPanel = function () {
    var tabs = [['overview', 'Overview'], ['models', 'Math models'], ['mastery', 'Mastery'], ['discuss', 'Discussion'], ['summary', 'Teacher summary'], ['sources', 'Sources'], ['settings', 'Settings & demo']];
    var qcount = HE.QUESTIONS.length, total = P.allSteps().length;
    var pane = {};
    pane.overview = '<h4>Learning objectives</h4>' + li(SUMMARY.objectives) + '<h4>Estimated completion time</h4><p>About <b>30–40 minutes</b> for most students (target 20–40). Required activities cannot be skipped. Unlimited attempts on every question.</p><h4>Concepts covered</h4><p>' + C.concepts.map(function (c) { return '<span class="cchip">' + c.name + '</span>'; }).join(' ') + '</p><h4>Flow</h4><ol>' + C.zones.map(function (z) { return '<li><b>' + esc(z.title) + '</b> — ' + esc(z.sub) + '</li>'; }).join('') + '</ol><p>Then: completion screen → My Gambling Literacy Report → Exit Ticket → Classroom Debrief.</p><div class="btn-row"><button class="btn primary big" id="tpDebrief">START CLASSROOM DEBRIEF</button></div>';
    pane.models = modelsHtml();
    pane.mastery = '<h4>Mastery requirements</h4><p>Completion = ' + total + ' required steps (' + qcount + ' questions in the bank). A zone unlocks only after the previous zone is complete. Analyst levels are earned from steps, never from token balance.</p>' + C.zones.map(function (z) { return '<h5>' + (z.num ? 'Zone ' + z.num + ': ' : '') + esc(z.title) + '</h5>' + li(P.zoneSteps(z.id).map(function (s) { return s[1]; })); }).join('') + '<h4>Analyst levels</h4>' + li(C.levels.map(function (L) { return 'Level ' + L.n + ' — ' + L.name + (L.vision ? ' (' + L.vision + ')' : ''); })) + '<details><summary><b>Show answer key (teacher only)</b></summary>' + answerKey() + '</details>';
    pane.discuss = '<h4>Suggested discussion questions</h4>' + li(SUMMARY.followups.concat(['Can a person win at gambling even if the game has a house advantage?', 'Why does hearing about someone\'s big win tell us so little?', 'What would you advertise if you wanted a game to look exciting? What would you leave out?'])) + '<div class="btn-row"><button class="btn primary" id="tpDebrief2">START CLASSROOM DEBRIEF</button></div>';
    pane.summary = '<h4>Expected misconceptions</h4>' + li(SUMMARY.misconceptions) + '<h4>Important mathematical takeaways</h4>' + li(SUMMARY.takeaways) + '<h4>Vocabulary</h4><dl>' + SUMMARY.vocab.map(function (v) { return '<dt>' + esc(v[0]) + '</dt><dd>' + esc(v[1]) + '</dd>'; }).join('') + '</dl><h4>Common student reactions</h4>' + li(SUMMARY.reactions) + '<h4>Important clarification points</h4>' + li(SUMMARY.clarify) + '<h4>Suggested follow-up questions</h4>' + li(SUMMARY.followups) + '<h4>Suggested extension activities</h4>' + li(SUMMARY.extensions) + '<div class="btn-row"><button class="btn primary big" id="tpDebrief3">START CLASSROOM DEBRIEF</button></div><p class="dim">No student data is collected or aggregated. This static site has no database; each student\'s work stays in their own browser.</p>';
    pane.sources = '<ol class="srcs">' + C.sources.map(function (s) { return '<li>' + esc(s.title) + ' <a href="' + s.url + '" target="_blank" rel="noopener">open ↗</a><br><small>' + esc(s.use) + '<br><i>Status: ' + esc(s.verified) + '</i></small></li>'; }).join('') + '</ol>';
    pane.settings = '<h4>Teacher Demo Mode</h4><p>Lets you jump between zones for classroom demonstration. Students follow standard progression when it is OFF. <i>This is a convenience switch, not a security feature.</i></p><label class="check"><input type="checkbox" id="tpDemo"' + (P.demo() ? ' checked' : '') + '> Teacher Demo Mode (unlock all zones)</label><div class="jump" id="tpJump"></div><h4>Optional settings</h4><label class="check"><input type="checkbox" id="tpName"' + (P.pref('nameLine') ? ' checked' : '') + '> Show an optional name field on the report, exit ticket and printouts (names are stored only on this device)</label><label class="check"><input type="checkbox" id="tpMotion"' + (P.pref('reduceMotion') ? ' checked' : '') + '> Reduce motion (also respected automatically from the device setting)</label><h4>Privacy</h4><p>Everything is stored with localStorage on the student\'s own Chromebook. No analytics, accounts, servers or external requests.</p>';
    var body = '<div class="tabs" role="tablist">' + tabs.map(function (t, i) { return '<button role="tab" class="tab' + (i ? '' : ' on') + '" data-t="' + t[0] + '" aria-selected="' + (!i) + '">' + t[1] + '</button>'; }).join('') + '</div>' + tabs.map(function (t, i) { return '<div class="tabpane' + (i ? ' hidden' : '') + '" data-p="' + t[0] + '">' + pane[t[0]] + '</div>'; }).join('');
    var m = UI.modal({ title: 'TEACHER PANEL', body: body, wide: true, cls: 'teacher' });
    $$('.tab', m.el).forEach(function (t) { t.addEventListener('click', function () { $$('.tab', m.el).forEach(function (x) { x.classList.toggle('on', x === t); x.setAttribute('aria-selected', x === t); }); $$('.tabpane', m.el).forEach(function (p) { p.classList.toggle('hidden', p.dataset.p !== t.dataset.t); }); }); });
    ['tpDebrief', 'tpDebrief2', 'tpDebrief3'].forEach(function (id) { var b = $('#' + id, m.el); if (b) b.addEventListener('click', function () { m.close(); HE.App.show('debrief'); }); });
    var jump = $('#tpJump', m.el); C.zones.forEach(function (z) { var b = UI.el('<button class="btn" type="button">' + (z.num ? z.num + '. ' : '★ ') + esc(z.title) + '</button>'); b.addEventListener('click', function () { if (!P.demo()) { UI.toast('Turn on Teacher Demo Mode first.'); return; } m.close(); HE.App.show(z.id); }); jump.appendChild(b); });
    var jb = UI.el('<button class="btn" type="button">Report</button>'); jb.addEventListener('click', function () { if (!P.demo()) { UI.toast('Turn on Teacher Demo Mode first.'); return; } m.close(); HE.App.show('report'); }); jump.appendChild(jb);
    var jc = UI.el('<button class="btn" type="button">Completion screen</button>'); jc.addEventListener('click', function () { if (!P.demo()) { UI.toast('Turn on Teacher Demo Mode first.'); return; } m.close(); HE.App.show('complete'); }); jump.appendChild(jc);
    $('#tpDemo', m.el).addEventListener('change', function () { P.pref('demo', this.checked); HE.App.refresh(); UI.toast(this.checked ? 'Teacher Demo Mode ON: all zones unlocked.' : 'Teacher Demo Mode OFF: normal progression restored.'); });
    $('#tpName', m.el).addEventListener('change', function () { P.pref('nameLine', this.checked); });
    $('#tpMotion', m.el).addEventListener('change', function () { P.pref('reduceMotion', this.checked); document.documentElement.classList.toggle('reduce-motion', this.checked); });
  };

  /* =====================================================================
     CLASSROOM DEBRIEF (presentation mode)
     ===================================================================== */
  var STD = C.sim.standardSession, std = null;
  function stdSim() { var w = []; for (var i = 0; i < STD.spins; i++) w.push(STD.wager); return Sim.run(10000, function (rng) { return E.playSeq(STD.game, w, rng, 0); }); }
  function show(el) { if (el) el.classList.remove('hidden'); }
  function btnGroup(stage, opts, correct, onPick) {
    var g = UI.el('<div class="dchoices" role="group"></div>'); stage.appendChild(g);
    opts.forEach(function (o, i) { var b = UI.el('<button type="button" class="dchoice" data-id="' + o[0] + '"><span>' + String.fromCharCode(65 + i) + '</span>' + esc(o[1]) + '</button>'); b.addEventListener('click', function () { $$('.dchoice', g).forEach(function (x) { x.classList.remove('sel'); }); b.classList.add('sel'); if (onPick) onPick(o[0]); }); g.appendChild(b); });
    return { mark: function () { $$('.dchoice', g).forEach(function (b) { b.classList.toggle('right', correct.indexOf(b.dataset.id) >= 0); b.classList.toggle('dim', correct.indexOf(b.dataset.id) < 0); }); } };
  }
  var TEN = [-120, -80, -250, 900, -75, -310, 40, -150, -60, -200];
  var SLIDES = [
    { t: 'DISCUSSION 1', build: function (st) {
      st.innerHTML = '<div class="dq">Can a person win at gambling even if the game has a house advantage?</div><div class="dans hidden">YES.</div><p class="dtxt hidden">Short-term individual outcomes can include wins. House advantage describes expected outcomes across repeated wagering.</p><div id="d1s"></div>';
      return { reveals: [function () { show($('.dans', st)); }, function () { show($('.dtxt', st)); }], sim: function () { std = stdSim(); $('#d1s', st).innerHTML = '<p class="dstat">In 10,000 simulated players (' + STD.spins + ' spins of ' + STD.wager + ' tokens on Neon Orchard): <b>' + pc(std.pctProfit, 1) + '</b> finished ahead, yet the average result was <b>' + sg(std.mean, 1) + '</b> tokens.</p>'; }, xray: function () { var g = E.game(STD.game); $('#d1s', st).innerHTML = '<p class="dstat">X-RAY: RTP <b>' + pc(g.rtp, 1) + '</b> · house edge <b>' + pc(g.edge, 1) + '</b> · expected net per ' + STD.wager + '-token spin <b>' + sg(g.ev * STD.wager, 2) + '</b>.</p>'; } };
    } },
    { t: 'DISCUSSION 2', build: function (st) {
      var pts = ['We may not know how much they wagered.', 'We may not know their previous losses.', 'We are seeing one person\'s outcome.', 'Large wins are more memorable and shareable than ordinary losses.', 'One observation cannot establish expected value.'];
      st.innerHTML = '<div class="dq">Why might hearing about someone\'s 5,000-token win tell us very little about whether gambling is profitable?</div><ul class="dlist">' + pts.map(function (p) { return '<li class="hidden">' + esc(p) + '</li>'; }).join('') + '</ul>';
      return { reveals: pts.map(function (_, i) { return function () { show($$('.dlist li', st)[i]); }; }), sim: null, xray: null };
    } },
    { t: 'DISCUSSION 3', build: function (st) {
      st.innerHTML = '<div class="dq">Which player tells us more about the mathematics of the game?</div><div class="dplayers"><div class="pl a"><small>PLAYER A</small><b>+800 tokens</b></div><div class="pl b"><small>PLAYER B</small><b>−300 tokens</b></div></div><div id="d3c"></div><div class="dans hidden">BOTH ARE INDIVIDUAL SAMPLES.</div><p class="dtxt hidden">What would tell us more?</p><div class="dans hidden">THOUSANDS OF REPEATED TRIALS.</div><canvas id="d3cv" data-h="260" class="hidden" role="img" aria-label="Distribution with Player A and Player B marked"></canvas><p class="dstat" id="d3s"></p>';
      var grp = btnGroup($('#d3c', st), [['a', 'PLAYER A'], ['b', 'PLAYER B'], ['n', 'NEITHER']], ['n']);
      var ans = $$('.dans', st), tx = $('.dtxt', st);
      return { reveals: [function () { grp.mark(); show(ans[0]); }, function () { show(tx); }, function () { show(ans[1]); }], sim: function () { std = std || stdSim(); var b = Sim.bounds(std, [800, -300]), h = Sim.histogram(std.nets, b.lo, b.hi, C.sim.bins), pa = Sim.position(std, 800), pb = Sim.position(std, -300), cv = $('#d3cv', st); show(cv); Ch.hist(cv, { counts: h.counts, lo: b.lo, hi: b.hi, color: Ch.COL.b, markers: [{ x: 800, label: 'PLAYER A', color: Ch.COL.d }, { x: -300, label: 'PLAYER B', color: Ch.COL.c }, { x: std.mean, label: 'average', color: Ch.COL.a, dash: true }] }); $('#d3s', st).innerHTML = 'Among 10,000 simulated players (' + STD.spins + ' spins × ' + STD.wager + '): +800 is better than <b>' + pc(pa.below, 2) + '</b> of them; −300 is better than <b>' + pc(pb.below, 1) + '</b>. Average: <b>' + sg(std.mean, 1) + '</b>. Both players are real possibilities in the same game.'; }, xray: null };
    } },
    { t: 'DISCUSSION 4 · THE PARLAY CHALLENGE', build: function (st) {
      st.innerHTML = '<div class="dq">What happens to the probability that EVERY prediction is correct?</div><div class="parrows" id="d4"></div><div class="dans hidden">Then why does the potential payout become so attractive?</div><ul class="dlist hidden"><li>Risk versus reward: rarer outcomes pay more.</li><li>Combined probability: the legs multiply.</li><li>Bookmaker pricing: each leg is priced a little below fair, and the margin compounds.</li><li>Large advertised payouts attract attention. The tiny probability is rarely advertised.</li></ul><p class="dtxt" id="d4x"></p>';
      var rows = $('#d4', st); for (var n = 1; n <= 6; n++) { var r = PL.reference(n); rows.insertAdjacentHTML('beforeend', '<div class="prow"><b>' + n + (n === 1 ? ' LEG' : ' LEGS') + '</b><div class="pbar"><i data-w="' + (r.prob * 100) + '"></i></div><span class="pp">' + pc(r.prob, r.prob < .1 ? 2 : 1) + '</span><span class="pay">pays ' + fmt(r.offeredMult, 1) + '×</span></div>'); }
      $$('.pbar i', st).forEach(function (i) { i.style.width = '100%'; });
      function anim() { $$('.pbar i', st).forEach(function (i) { i.style.width = i.dataset.w + '%'; }); }
      return { reveals: [anim, function () { show($('.dans', st)); show($('.dlist', st)); }], sim: anim, xray: function () { var r = PL.reference(6); $('#d4x', st).innerHTML = 'X-RAY: a fair 6-leg payout would be <b>' + fmt(r.fairMult, 0) + '×</b>; the fictional book offers <b>' + fmt(r.offeredMult, 1) + '×</b>. Expected return per token: <b>' + fmt(r.rtp, 3) + '</b> (edge ' + pc(r.edge, 1) + '). ' + esc(C.text.independence); } };
    } },
    { t: 'DISCUSSION 5 · REMOVE THE LIGHTS', build: function (st) {
      st.innerHTML = '<div class="dq">Which one would people probably want to play longer?</div><div class="ab big"><div class="mockA"><b>GAME A</b><div class="ml">★ ★ ◆</div><i>BIG WIN! +500 ✦ ✦ ✦</i><small>lights · sound · confetti</small></div><div class="mockB"><b>GAME B</b><p>Result: No match.<br>Return: 0. Net: −10.<br>Balance: 990.</p></div></div><div class="dans hidden">SAME ODDS. SAME PAYOUTS. SAME EXPECTED VALUE.</div><p class="dtxt hidden">What changed?</p><div class="dans hidden">THE EXPERIENCE.</div><p class="dtxt hidden">Discuss: interface design, sound, animation, celebration, attention, emotion. Researchers study these links, and effects vary by person.</p><div id="d5s"></div>';
      var a = $$('.dans', st), t = $$('.dtxt', st);
      return { reveals: [function () { show(a[0]); }, function () { show(t[0]); }, function () { show(a[1]); show(t[1]); }], sim: function () { var A = Sim.run(10000, function (r) { return E.playN('slots', 10, 20, r); }), B = Sim.run(10000, function (r) { return E.playN('slots', 10, 20, r); }); $('#d5s', st).innerHTML = '<p class="dstat">10,000 simulated 20-spin sessions each. Game A average <b>' + sg(A.mean, 1) + '</b> · Game B average <b>' + sg(B.mean, 1) + '</b> · expected <b>' + sg(E.game('slots').ev * 200, 1) + '</b>. Finished ahead: A <b>' + pc(A.pctProfit, 1) + '</b>, B <b>' + pc(B.pctProfit, 1) + '</b>. Same math; any gap is randomness.</p>'; }, xray: function () { var g = E.game('slots'); $('#d5s', st).innerHTML = '<p class="dstat">Both games read: <code>' + esc(g.outcomes.map(function (o) { return o.id + ' p=' + o.p + ' ×' + o.ret; }).join(' | ')) + '</code></p>'; } };
    } },
    { t: 'DISCUSSION 6 · WHAT WOULD YOU ADVERTISE?', build: function (st) {
      st.innerHTML = '<div class="dq">If you wanted to make this game look exciting, which player\'s result would you show?</div><div class="ten">' + TEN.map(function (v, i) { return '<div class="tn' + (i === 3 ? ' star' : '') + '"><small>Player ' + (i + 1) + '</small><b class="' + (v > 0 ? 'pos' : 'neg') + '">' + sg(v) + '</b></div>'; }).join('') + '</div><div class="dans hidden">THIS IS WHY ONE WINNER DOESN\'T TELL THE WHOLE STORY.</div><div class="dans hidden">LOOK AT THE DISTRIBUTION.</div><canvas id="d6cv" data-h="300" class="hidden" role="img" aria-label="Bar chart of the ten results"></canvas><ul class="dlist hidden"><li>Selection bias: we see the examples someone chose to show.</li><li>Survivorship-style reasoning: we hear from the winners, not the many who lost.</li><li>Salience: large wins are more noticeable and more memorable.</li></ul><p class="dstat" id="d6s"></p>';
      var a = $$('.dans', st), mean = TEN.reduce(function (x, y) { return x + y; }, 0) / TEN.length;
      return { reveals: [function () { show(a[0]); $$('.tn', st).forEach(function (x, i) { x.classList.toggle('dimmed', i !== 3); }); }, function () { show(a[1]); var cv = $('#d6cv', st); show(cv); Ch.hbars(cv, { items: TEN.map(function (v, i) { return { label: 'Player ' + (i + 1), value: v, color: v > 0 ? Ch.COL.d : Ch.COL.c }; }), fmt: function (v) { return sg(v, 0); } }); $('#d6s', st).innerHTML = '<b>' + TEN.filter(function (v) { return v > 0; }).length + '</b> of 10 finished ahead; the average of all ten is <b>' + sg(mean, 1) + '</b>.'; }, function () { show($('.dlist', st)); }], sim: null, xray: null };
    } },
    { t: 'DISCUSSION 7 · THE SCREENSHOT PROBLEM', build: function (st) {
      var opts = ['How much the person previously lost', 'How many wagers they made', 'How unusual the result was', 'Whether other players lost', 'The probability of the outcome', 'The expected value of the game'];
      st.innerHTML = '<div class="dq">What information is missing?</div><div class="shot"><div class="shot-h">● fictional post</div><b>I JUST TURNED 50 TOKENS INTO 1,200!!!</b><div class="shot-f">♥ 4.2k · 🔁 1.1k</div></div><div class="dchoices multi" id="d7c" role="group" aria-label="Missing information">' + opts.map(function (o) { return '<button type="button" class="dchoice" aria-pressed="false">' + esc(o) + '</button>'; }).join('') + '<button type="button" class="dchoice all hidden">ALL OF THE ABOVE</button></div><div class="dans hidden">A screenshot of a winning result is incomplete evidence.</div>';
      $$('#d7c .dchoice', st).forEach(function (b) { b.addEventListener('click', function () { b.classList.toggle('sel'); b.setAttribute('aria-pressed', b.classList.contains('sel')); }); });
      return { reveals: [function () { $$('#d7c .dchoice:not(.all)', st).forEach(function (b) { b.classList.add('right'); }); show($('.dchoice.all', st)); $('.dchoice.all', st).classList.add('right'); show($('.dans', st)); }], sim: null, xray: null };
    } },
    { t: 'DISCUSSION 8 · THE FINAL QUESTION', build: function (st) {
      st.innerHTML = '<div class="dq">What is the best way to think about a gambling win?</div><div id="d8c"></div><div class="dans hidden" id="d8a"></div>';
      var grp = btnGroup($('#d8c', st), [['A', '"Winning proves the system works."'], ['B', '"Winning means I\'m skilled."'], ['C', '"Winning means I should increase my wager."'], ['D', '"A win is one outcome. I still need to understand the probabilities and expected value."']], ['D']);
      return { reveals: [function () { grp.mark(); }, function () { var a = $('#d8a', st); show(a); a.className = 'dans analyst'; a.innerHTML = ''; UI.sequence(a, ['ANALYST THINKING', '“I don\'t ask only: <b>DID SOMEONE WIN?</b>”', '“I ALSO ASK:”', 'WHAT WERE THE ODDS?', 'HOW MUCH WAS WAGERED?', 'WHAT WAS THE EXPECTED VALUE?', 'WHAT HAPPENS ACROSS THOUSANDS OF TRIALS?'], 1100); }], sim: null, xray: null };
    } }
  ];

  D.start = function (main) {
    document.body.classList.add('present'); var idx = 0, cur = null, rv = 0;
    main.innerHTML = '<div class="deck" id="deck"><div class="deck-top"><span id="dTitle"></span><span class="dim" id="dCount"></span></div><div class="stage" id="dStage" aria-live="polite"></div><div class="deck-bar"><button class="btn" id="dPrev">◀ Prev</button><button class="btn" id="dNext">Next ▶</button><button class="btn primary" id="dReveal">Reveal answer (R)</button><button class="btn" id="dSim">Run simulation (S)</button><button class="btn" id="dX">X-Ray (X)</button><button class="btn ghost" id="dFull">Full screen</button><button class="btn ghost" id="dExit">Exit (Esc)</button></div></div>';
    var stage = $('#dStage', main);
    function go(i) {
      idx = Math.max(0, Math.min(SLIDES.length - 1, i)); rv = 0; std = null; stage.innerHTML = ''; var s = SLIDES[idx]; $('#dTitle', main).textContent = s.t; $('#dCount', main).textContent = (idx + 1) + ' / ' + SLIDES.length;
      var box = UI.el('<div class="slide"></div>'); stage.appendChild(box); cur = s.build(box);
      $('#dPrev', main).disabled = idx === 0; $('#dNext', main).disabled = idx === SLIDES.length - 1; $('#dSim', main).disabled = !cur.sim; $('#dX', main).disabled = !cur.xray; upd();
    }
    function upd() { var b = $('#dReveal', main); b.disabled = rv >= cur.reveals.length; b.textContent = rv >= cur.reveals.length ? 'All revealed' : 'Reveal answer (R)' + (cur.reveals.length > 1 ? ' ' + (rv + 1) + '/' + cur.reveals.length : ''); }
    function reveal() { if (rv < cur.reveals.length) { cur.reveals[rv++](); UI.sound('click'); upd(); } }
    $('#dPrev', main).addEventListener('click', function () { go(idx - 1); }); $('#dNext', main).addEventListener('click', function () { go(idx + 1); });
    $('#dReveal', main).addEventListener('click', reveal); $('#dSim', main).addEventListener('click', function () { if (cur.sim) cur.sim(); }); $('#dX', main).addEventListener('click', function () { if (cur.xray) cur.xray(); });
    $('#dFull', main).addEventListener('click', function () { var d = document.documentElement; if (d.requestFullscreen) d.requestFullscreen().catch(function () {}); });
    function exit() { document.removeEventListener('keydown', key); document.body.classList.remove('present'); if (document.fullscreenElement && document.exitFullscreen) document.exitFullscreen(); try { history.replaceState(null, '', '#'); } catch (e) {} HE.App.show(P.complete100() ? 'complete' : (C.zoneById(P.state.zone) && P.zoneUnlocked(P.state.zone) ? P.state.zone : P.firstIncompleteZone())); }
    $('#dExit', main).addEventListener('click', exit);
    function key(e) {
      if (!document.body.classList.contains('present') || document.querySelector('.modal-back')) return; var t = e.target && e.target.tagName; if (t === 'INPUT' || t === 'TEXTAREA') return;
      if (e.key === 'ArrowRight') go(idx + 1); else if (e.key === 'ArrowLeft') go(idx - 1); else if (e.key === 'r' || e.key === 'R') reveal(); else if ((e.key === 's' || e.key === 'S') && cur.sim) cur.sim(); else if ((e.key === 'x' || e.key === 'X') && cur.xray) cur.xray(); else if (e.key === 'Escape') exit();
    }
    document.addEventListener('keydown', key); document.querySelector('.hud-note'); go(0);
    $('#hud').setAttribute('aria-hidden', 'false');
  };
})(window);
