#!/usr/bin/env node
// Generates docs/ANSWER_KEY.md and docs/COVERAGE_MATRIX.md FROM THE LIVE CONTENT, so teacher materials always match what the app scores.
//   node tools/gen-docs.js
const fs = require('fs'), path = require('path');
const { load } = require('../tests/load');
const W = load(), P = W.Policy, S = W.Sim, DOCS = path.join(__dirname, '../docs');
const clean = s => String(s == null ? '' : s).replace(/\*\*/g, '').replace(/\|/g, '/').replace(/\n+/g, ' ');
const dem = it => { const v = it.variants[0], tw = v.parts.reduce((s, p) => s + p.w, 0), o = { F: 0, A: 0, D: 0 }; v.parts.forEach(p => { o[p.d || it.d] += it.pts * p.w / tw; }); return o; };
const fmt = n => (Math.round(n * 100) / 100).toString();
const optLabel = (p, id) => { const o = p.opts.find(x => x.id === id); return o ? clean(o.t) : id; };

/* ------------------------------------------------------------------ ANSWER KEY */
let k = [];
k.push('# Answer key, compatibility matrices and rationales', '', '> **Teacher-only reference. Generated by `node tools/gen-docs.js` from the live content, so it always matches what the app scores.** Client-side keys are inspectable by a technically capable student; see README "Honest technical limits."', '');
k.push('## How scoring works', '', '- 100 automatically scored points, 0 teacher-graded points, no external grading.', '- `earned = rubric fraction x item points x attempt cap` (cap 100% / 90% / 75% for attempts 1 / 2 / 3). The best earned value across permitted attempts is kept; only the final total is rounded.', '- Credit is per option (0 to 1). **Multi-select** parts: credit = sum of chosen options\' credit / best possible sum. **Compatibility (dependent) parts**: the credit of an option depends on the student\'s earlier selection (matrix below). `depCap`: if the anchor part earned 0, dependent parts are multiplied by that factor.', '- Variants are equivalent transfer versions with the same part structure and point maximum; attempt 1 uses variant A, attempt 2 variant B, attempt 3 variant C (short items have two variants).', '');
const byM = {}; W.ITEMS.forEach(i => (byM[i.m] = byM[i.m] || []).push(i));
Object.keys(byM).forEach(m => {
  const mi = W.MISSION[m]; k.push(`## Mission ${m}: ${mi.title} (${byM[m].reduce((s, i) => s + i.pts, 0)} points)`, '');
  byM[m].forEach(it => {
    const d = dem(it), tw = it.variants[0].parts.reduce((s, p) => s + p.w, 0);
    k.push(`### ${it.id}: ${clean(it.topic)}`, '', `- Stage ${it.st} | **${it.pts} pt${it.pts === 1 ? '' : 's'}** | class \`${it.cls}\` (${P.limitFor(it)} attempts by default) | demand F/A/D = ${fmt(d.F)}/${fmt(d.A)}/${fmt(d.D)}`, `- Source: ${clean(it.src)}`, `- Rationale shown after finalization: ${clean(it.why)}`, `- General hint (no answer revealed): ${clean(it.hint)}`, '');
    it.variants.forEach((v, vi) => {
      k.push(`#### Variant ${'ABC'[vi]} (\`${v.id}\`, used on attempt ${vi + 1})`, '');
      if (v.ctx) k.push(`Prompt: ${clean(v.ctx)}`, '');
      if (v.vis && v.vis.type === 'post') k.push(`Post: ${clean(v.vis.post.handle)} - "${clean(v.vis.post.text)}" | Author: ${clean(v.vis.post.tabs.author)} | Evidence: ${clean(v.vis.post.tabs.evidence)} | Purpose: ${clean(v.vis.post.tabs.purpose)} | Independent: ${clean(v.vis.post.tabs.indep)}`, '');
      if (v.vis && v.vis.type === 'finalcase') { const c = W.FINALCASES[v.vis.idx]; k.push(`Case ${c.who}: post "${clean(c.post.text)}"; responsibilities: ${clean(c.resp)}; goal: ${clean(c.goal)}`, ''); }
      v.parts.forEach(p => {
        k.push(`**${clean(p.label)}** (${p.type}${p.type === 'multi' ? `, pick ${p.pick}` : ''}, weight ${p.w}, ${p.d || it.d === 'F' ? p.d || it.d : p.d || it.d}${p.dep ? `, depends on \`${[].concat(p.dep).join('+')}\`, depCap ${p.depCap === undefined ? 'none' : p.depCap}` : ''})`, '');
        if (p.type === 'num') { k.push(`- Correct value: **${p.key}**`, ''); return; }
        if (!p.dep) { k.push('| Credit | Option |', '|---|---|'); p.opts.slice().sort((a, b) => b.c - a.c).forEach(o => k.push(`| ${o.c} | ${clean(o.t)} |`)); k.push(''); }
        else {
          const anchors = [].concat(p.dep).map(d => v.parts.find(q => q.id === d)); const keys = Object.keys(p.matrix);
          k.push('Compatibility matrix (credit per option, given the anchor selection):', '', '| Anchor selection | Credited options |', '|---|---|');
          keys.forEach(kk => { const row = p.matrix[kk]; const label = anchors.length === 1 ? optLabel(anchors[0], kk) : kk; const cr = Object.keys(row).filter(id => row[id] > 0).map(id => `${clean(p.opts.find(o => o.id === id).t)} = ${row[id]}`).join('; ') || '(none)'; k.push(`| ${label} | ${cr} |`); });
          const covered = new Set(keys); const miss = anchors[0].opts.filter(o => !covered.has(o.id)).map(o => clean(o.t)); if (miss.length) k.push(`| (any other anchor selection: ${miss.join(' / ')}) | (none: 0 credit) |`);
          k.push('');
        }
        const h = p.hint; if (h) k.push(`Part hint: ${clean(h)}`, '');
      });
      if (v.branches) { k.push('Branch outcomes shown after submission (plausible, non-humiliating):', ''); Object.keys(v.branches).forEach(id => k.push(`- ${clean(v.parts.find(p => p.id === 'p').opts.find(o => o.id === id).t)}: ${clean(v.branches[id])}`)); k.push(''); }
    });
  });
});
k.push('## Computed simulation keys', '', 'All Mission 6 keys are computed from `js/sim.js` and the fixed case weeks. Summary:', '', '| Case week | Daily totals (Mon-Sun) | Running total | Domain subtotals (raw / % of own max) | Greatest day | Weakest (normalized) | Lowest raw |', '|---|---|---|---|---|---|---|');
Object.keys(W.CASEWEEKS).forEach(id => { const w = S.makeWeek(W.CASEWEEKS[id].rows), c = S.compute(w), g = S.greatestDay(w), wk = S.weakestDomain(w), lr = S.lowestRawDomain(w); k.push(`| ${W.CASEWEEKS[id].name} | ${c.dayTotals.join(', ')} | ${c.running.join(', ')} | ${S.DOMAINS.map(d => `${d.n} ${c.domainWeek[d.id]}/${S.domWeekMax(d.id)} (${(c.normalized[d.id] * 100).toFixed(1)}%)`).join('; ')} | ${S.DAY_NAMES[g.days[0]]} (${g.signed[0]}) | ${S.DOM[wk.ids[0]].n} | ${S.DOM[lr.ids[0]].n} |`); });
k.push('', 'Model checks (verified by `tests/content-tests.js`): all-A week = +245, all-B = 0, all-C = -245; daily maximum 35; domain weekly maxima Physical 56, Mental 49, Emotional 49, Social 56, Environmental 35. Ties are handled explicitly (`S.greatestDay`, `S.weakestDomain` return every tied day/domain); the three case weeks have unique answers.', '');
k.push('## Jordan\'s 12 playable decisions (unscored)', '', '| # | Day | Category (weight) | A / B / C options | Baseline grade |', '|---|---|---|---|---|');
const jw = W.CASEWEEKS.jordan.rows; W.DECISIONS.forEach((d, i) => k.push(`| ${i + 1} | ${S.DAYS[d.day]} | ${S.CAT[d.cat].n} (${S.CAT[d.cat].w}) | A: ${clean(d.opts.A)} / B: ${clean(d.opts.B)} / C: ${clean(d.opts.C)} | ${jw[d.cat][d.day]} |`));
fs.writeFileSync(path.join(DOCS, 'ANSWER_KEY.md'), k.join('\n') + '\n');

/* ------------------------------------------------------------------ COVERAGE MATRIX */
const ids = (...re) => W.ITEMS.filter(i => re.some(r => new RegExp(r).test(i.id)));
const SRC = { dim: 'Dimensions_of_Wellness (3).pptx', met: 'Wildcats_Health_Metrics (3).pptx', hab: 'Day3_Self_Assessment_Habit_Change (3).pptx', med: 'Wildcats_Health_Media_Literacy (2).pptx', pers: 'Wildcats_Personal_Responsibility (3).pptx', ws: 'Health_by_a_Thousand_Choices_Worksheet (2).docx' };
const rows = [
  ['Five dimensions: Physical, Mental, Emotional, Social, Environmental (content of each)', SRC.dim, '1.1 Sort the situations (10 cards, two per dimension; 2 equivalent cards each)', ids('^m1\\.c'), 'Primary dimension chosen from a concrete situation, not label-to-definition matching.'],
  ['Wellness is active and ongoing; strength in one domain can coexist with difficulty in another', SRC.dim, '1.2 Overlap Lab; guide text; 3.1 ratings; 6.4 overlooked domain', ids('^m3\\.ratings', '^m6\\.over'), 'Assessed through strengths vs growth areas and "a positive total can hide a weak domain."'],
  ['Dimensions overlap / ripple effects (poor sleep affects focus, mood, relationships)', SRC.dim, '1.2 Overlap Lab (unscored); 1.3 Ripple effect; 7.2 CER', ids('^m1\\.ripple', '^m7\\.cer'), 'Defensible alternative connections are accepted; explanation must match the chosen connection.'],
  ['Recognize measurements: height, weight, temperature, pulse, breathing, blood pressure, BMI, glucose, cholesterol', SRC.met, '2.x reference panel lists all nine; 2.1 uses six measurement options (incl. temperature)', ids('^m2\\.match'), 'All nine appear in the panel/options; graded recognition covers the five main metrics. Height/weight/breathing are not separately graded (recognition only).'],
  ['What the five main metrics measure (BP, resting HR, BMI, fasting glucose, total cholesterol)', SRC.met, '2.1 What is being measured?', ids('^m2\\.match'), 'Context-embedded descriptions, not definition matching.'],
  ['General adult references (BP <120/80, resting HR 60-100, BMI 18.5-24.9, glucose <100, cholesterol <200) with current clinical context', SRC.met + ' + AHA/NIDDK/MedlinePlus/CDC (docs/SOURCE_REGISTER.md)', '2.2 Read the check-up (embedded reference panel; AHA BP categories; units and conditions shown)', ids('^m2\\.read'), 'Adult-only cases; broad one-sided limits are not treated as "lower is better."'],
  ['Adult cutoffs are never applied to teens; youth BMI uses age/sex percentiles; BMI is a limited screening tool', SRC.met + ' + CDC', 'Reference panel; 2.2 case 3 (BMI) ; optional practice po.bmi (unscored)', ids('^m2\\.read\\.3'), 'Teen interpretation is taught in the panel and practiced in optional practice. It is not a scored recall item because scored cases are adults only (by design).'],
  ['Unusual reading = reason for follow-up, not diagnosis; context, trends, family history, clinician; lower is not always better', SRC.met, '2.2 (part 2 of each case); 2.4 follow-up question', ids('^m2\\.read', '^m2\\.intake\\.2'), 'Misconception distractors: "lower is always better", "one reading diagnoses."'],
  ['Habits and health outcomes (activity, nutrition, sleep, stress, routine care, sedentary, tobacco, alcohol) without guaranteed numbers', SRC.met, '2.3 Habits and health measures', ids('^m2\\.life'), 'Supported, hedged statements vs exact-number promises.'],
  ['Intake: a metric and its purpose, daily habits, family history, a lifestyle factor, a follow-up question', SRC.met, '2.4 Intake desk', ids('^m2\\.intake'), 'No student body measurements or medical history are collected anywhere.'],
  ['Self-assessment 1-5; strengths, growth areas, one realistic next step; ratings are information', SRC.hab, '3.1 Read the ratings', ids('^m3\\.ratings'), 'No grading of anyone for rating themselves low.'],
  ['Habit loop: cue -> routine -> reward', SRC.hab, '3.2 Repair the habit loop', ids('^m3\\.loop'), 'Classroom model, not a claim every behavior follows one mechanism.'],
  ['Strategies: start small, habit stacking, environment design, tracking', SRC.hab, '3.3 Strategies; 3.5 builder (tracking, feasible amount)', ids('^m3\\.strat\\.1', '^m3\\.smartbuild', '^m3\\.loop'), ''],
  ['Roadblocks: all-or-nothing thinking, motivation dips, unclear cues, oversized goals; a missed day does not erase progress', SRC.hab, '3.3 Strategies; 3.2 (unclear cue); 3.4 (oversized goal)', ids('^m3\\.strat\\.2', '^m3\\.loop', '^m3\\.smartfix'), ''],
  ['Variation in habit formation; challenge the "21 days" claim (Lally 2009/2010; Singh 2024)', SRC.hab + ' + research (docs/SOURCE_REGISTER.md)', '3.3 Strategies', ids('^m3\\.strat\\.3'), 'No exact statistic is graded; study average is not a deadline.'],
  ['SMART = Specific, Measurable, Achievable, Relevant, Time-bound: recognize AND construct', SRC.hab, '3.4 SMART repair; 3.5 SMART builder; 7.1 goal repair', ids('^m3\\.smart', '^m7\\.d3'), 'Construction from selectable components with a keyed compatibility matrix; not unrestricted writing.'],
  ['Media literacy: identify the claim; author/credentials, evidence, purpose, independent verification', SRC.med, '4.1-4.5 five posts with Author/Evidence/Purpose/Independent tabs; 4.6 checklist', ids('^m4\\.'), 'Credible, Questionable and Not Credible variants exist for every case type.'],
  ['Five case types: fad diet, supplement ad, influencer claim, manipulated before/after photo, AI/deepfake advice', SRC.med, '4.1 fad diet; 4.2 supplement; 4.3 influencer; 4.4 before/after; 4.5 AI/deepfake', ids('^m4\\.c'), 'Fifteen labeled-fictional posts (3 per type).'],
  ['Red flags: miracle/instant/guaranteed, testimonials vs research, product/affiliate incentives, fear/urgency, unverifiable sources, polish', SRC.med, '4.x evidence options; 4.6 checklist', ids('^m4\\.'), 'Sales motive warrants scrutiny but does not alone prove falsity; polish/AI alone do not decide truth.'],
  ['STOP: State, Think, Observe, Pick (exact acronym); two+ options; immediate vs long-term consequences; defend a choice', SRC.pers, '5.1 and 5.2 situations; 5.3 justification; 6.6 revision; 7.1 decision', ids('^m5\\.', '^m6\\.stop', '^m7\\.d2'), 'Multiple responsible choices accepted; responsibility is not perfection or total control.'],
  ['Taught scenarios: late-night gaming; skipping meals; school stress; scrolling; energy drinks; argument; peer pressure to vape; ride from someone who has been drinking', SRC.pers, 'A pool: gaming, meals, school stress. B pool: ride, vape pressure, argument. Justification: energy drink, scrolling, stress/movement. Sim decisions also cover sleep, scrolling, energy drink, vape pressure, conflict', ids('^m5\\.'), 'No substance use is simulated as entertainment.'],
  ['Safe alternative ride and seeking appropriate support', SRC.pers, '5.2 variant A (ride); variants B/C support-seeking options', ids('^m5\\.b'), ''],
  ['Health by a Thousand Choices: 20 categories, weights, A/B/C, domain subtotals, daily total, running total, +/-35/day, +/-245/week', SRC.ws, '6.1 playable week (12 decisions); full 140-entry log inspectable', ids('^m6\\.'), 'Weights preserved exactly (js/sim.js); points are fictional teaching weights.'],
  ['Calculate a domain subtotal, a daily total, a running total', SRC.ws, '6.2 Calculate', ids('^m6\\.calc'), ''],
  ['Interpret the trajectory and the greatest daily effect', SRC.ws, '6.3 Trajectory', ids('^m6\\.traj'), 'Unique greatest day in every case week; ties handled in code.'],
  ['Domains have different maxima; normalized vs raw; overlooked domain', SRC.ws, '6.4 Overlooked domain', ids('^m6\\.over'), 'Maxima trap: lowest raw domain differs from weakest normalized domain in Jordan\'s and Eli\'s weeks.'],
  ['Repeated +/-1 choices accumulate', SRC.ws, '6.5 Small choices, big sums', ids('^m6\\.pm1'), ''],
  ['Worksheet simplifications vs verified guidance (7-9 h sleep, 30 min movement vs CDC 8-10 h, 60 min)', SRC.ws + ' + CDC', '6.1 rule boxes on the sleep and movement decisions', [], 'Labeled as worksheet scoring rules; clarification shown, not graded as complete teen guidance (docs/CONTENT_NOTES.md).'],
  ['Whole-person balance, accumulation, cross-domain effects, resuming after setbacks', SRC.ws, '6.1 ripple notes; 6.3 Jordan recovery; 6.4; 7.2', ids('^m6\\.traj', '^m6\\.over', '^m7\\.cer'), ''],
  ['Integrated transfer: misleading post + conflicting responsibilities + wellness pattern + goal', 'All five decks + worksheet', '7.1 three decisions; 7.2 CER', ids('^m7\\.'), 'Three equivalent integrated cases; CER scored with a compatibility key.']
];
let c = [];
c.push('# Coverage matrix, scoring blueprint and cognitive-demand audit', '', '> Generated by `node tools/gen-docs.js` from the live content.', '', '**Source files.** The six source files (decks and worksheet) were **not supplied** to the build, so slide numbers could not be inspected. Rows are mapped to the file name and the curriculum specification section; **slide-level references are unverified.** No slide content was invented. Teachers should add slide numbers during the pilot review.', '');
c.push('## 1. Scoring blueprint', '', '| Mission | Title | Items | Points | Blueprint | Pacing target (min) |', '|---|---|---|---|---|---|');
const bp = { 1: 12, 2: 16, 3: 18, 4: 18, 5: 14, 6: 16, 7: 6 }; let tp = 0;
Object.keys(byM).forEach(m => { const pts = byM[m].reduce((s, i) => s + i.pts, 0); tp += pts; c.push(`| ${m} | ${W.MISSION[m].title} | ${byM[m].length} | ${pts} | ${bp[m]} ${pts === bp[m] ? '(match)' : '(MISMATCH)'} | ${W.MISSION[m].est} |`); });
c.push(`| | **Total** | ${W.ITEMS.length} | **${tp}** | 100 | ${W.estTotal()} (incl. 2 min launch) |`, '', 'Manual-review points: **0**. Teacher-graded points: **0**. Required unscored activities (count toward completion only): ' + W.ACTIVITIES.map(a => a.title).join('; ') + '.', '');
c.push('## 2. Coverage matrix', '', '| # | Objective / topic | Source file (slide unverified) | Activity | Scored evidence (items) | Points | Cognitive demand F/A/D | Answer rationale / notes |', '|---|---|---|---|---|---|---|---|');
rows.forEach((r, i) => { const items = r[3], pts = items.reduce((s, it) => s + it.pts, 0), d = items.reduce((o, it) => { const x = dem(it); o.F += x.F; o.A += x.A; o.D += x.D; return o; }, { F: 0, A: 0, D: 0 }); c.push(`| ${i + 1} | ${r[0]} | ${r[1]} | ${r[2]} | ${items.length ? items.map(x => x.id).join(', ') : '(unscored: clarification)'} | ${items.length ? fmt(pts) : 0} | ${fmt(d.F)}/${fmt(d.A)}/${fmt(d.D)} | ${r[4]} |`); });
c.push('', 'Points can appear in more than one row when an item assesses more than one objective; row totals are not additive.', '', 'Instructional content intentionally **not** graded as recall: logistical slide directions, historical trivia, exact habit-timing statistics, SMART history, and prevalence percentages from the slides (original studies not verified; see CONTENT_NOTES.md).', '');
c.push('## 3. Cognitive-demand audit', '', 'Design targets (not empirical difficulty): about 25 F (foundational), 55 A (application in context), 20 D (analysis, evaluation, construction). Tagged at the part level in the content files.', '');
const tot = { F: 0, A: 0, D: 0 }; W.ITEMS.forEach(it => { const d = dem(it); tot.F += d.F; tot.A += d.A; tot.D += d.D; });
c.push('| Level | Points | Target |', '|---|---|---|', `| Foundational (recognition, procedures) | ${fmt(tot.F)} | ~25 |`, `| Application in context | ${fmt(tot.A)} | ~55 |`, `| Analysis / evaluation / construction | ${fmt(tot.D)} | ~20 |`, `| Knowledge used in context (A + D) | ${fmt(tot.A + tot.D)} | at least 70 |`, '');
c.push('| Item | Pts | Class | F | A | D | Topic |', '|---|---|---|---|---|---|---|');
W.ITEMS.forEach(it => { const d = dem(it); c.push(`| ${it.id} | ${it.pts} | ${it.cls} | ${fmt(d.F)} | ${fmt(d.A)} | ${fmt(d.D)} | ${clean(it.topic)} |`); });
c.push('', '## 4. Attempt classes', '', '| Class | Items | Points | Default attempts |', '|---|---|---|---|');
['short', 'complex'].forEach(cl => { const it = W.ITEMS.filter(i => i.cls === cl); c.push(`| ${cl} | ${it.length} | ${it.reduce((s, i) => s + i.pts, 0)} | ${W.CONFIG.attemptLimits[cl]} |`); });
c.push('', '## 5. Misconception distractors by design', '', '- One healthy domain means total wellness (3.1, 6.4, 7.2)', '- Lower readings are always better (2.2 heart rate, glucose, BMI)', '- Repeating one post counts as independent verification (4.x evidence options)', '- Missing one day ruins a habit (3.3)', '- A specific goal is automatically fully SMART (3.4, 3.5, 7.1)', '- The largest running total means every domain is thriving (6.3, 6.4)', '- A single reading is a diagnosis (2.2)', '- Ads / AI / polish alone decide credibility (4.x, 7.1)', '');
fs.writeFileSync(path.join(DOCS, 'COVERAGE_MATRIX.md'), c.join('\n') + '\n');
console.log('Wrote docs/ANSWER_KEY.md (' + Math.round(fs.statSync(path.join(DOCS, 'ANSWER_KEY.md')).size / 1024) + ' KB) and docs/COVERAGE_MATRIX.md');
